"""Script to build the comprehensive 105+ record authentic Gujarati knowledge base.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
ROOT_DIR = Path(__file__).resolve().parent.parent

# Load initial 23 records from build_kb.py and add the remaining 82+ verified records
from src.build_kb import KNOWLEDGE_RECORDS as BASE_RECORDS

ADDITIONAL_RECORDS = [
    # =========================================================================
    # ADDITIONAL HISTORICAL PLACES & HERITAGE (24-38)
    # =========================================================================
    {
        "id": "hist_13",
        "category": "Historical Places",
        "title": "ભદ્રનો કિલ્લો - અમદાવાદ (Bhadra Fort Ahmedabad)",
        "title_en": "Bhadra Fort",
        "district": "Ahmedabad",
        "question_gu": "અમદાવાદના ભદ્રના કિલ્લાનો ઇતિહાસ અને ભદ્રકાળી માતાનું મંદિર જણાવો.",
        "question_hi": "अहमदाबाद के भद्र किले का इतिहास और भद्रकाली मंदिर के बारे में बताएं।",
        "question_mr": "अहमदाबादच्या भद्र किल्ल्याचा इतिहास आणि भद्रकाली मंदिर याविषयी सांगा.",
        "question_en": "Tell me about Bhadra Fort and Bhadrakali Temple in Ahmedabad.",
        "question_roman_gu": "Ahmedabad na Bhadra killa no itihas ane Bhadrakali mandir vishe janavo.",
        "answer_gu": "ભદ્રનો કિલ્લો અમદાવાદ શહેરની સ્થાપના સાથે ઈ.સ. ૧૪૧૧માં સુલતાન અહમદ શાહ દ્વારા સાબરમતી નદીના કિનારે બનાવવામાં આવ્યો હતો. આ કિલ્લાનું નામ મરાઠા શાસન દરમિયાન સ્થપાયેલા પ્રસિદ્ધ 'ભદ્રકાળી માતાજીના મંદિર' પરથી પડ્યું છે. કિલ્લામાં ભવ્ય દરબાર હોલ, શાહી મહેલ, મસ્જિદ અને ઘડિયાળ વાળો ટાવર (Clock Tower) આવેલા છે. કિલ્લાનો મુખ્ય પ્રવેશદ્વાર 'તીન દરવાજા' (Teen Darwaza) તરીકે ઓળખાય છે, જે અમદાવાદના કોટ વિસ્તારની ઐતિહાસિક શાન છે.",
        "short_answer_gu": "અમદાવાદમાં ૧૪૧૧માં સુલતાન અહમદ શાહે બંધાવેલો કિલ્લો, જ્યાં પ્રસિદ્ધ ભદ્રકાળી માતાનું મંદિર અને તીન દરવાજા આવેલા છે.",
        "short_answer_en": "Bhadra Fort was built in 1411 by Sultan Ahmad Shah on the banks of Sabarmati, housing the historic Bhadrakali Temple and Teen Darwaza.",
        "short_answer_hi": "१४११ में सुल्तान अहमद शाह द्वारा निर्मित भद्र किला अहमदाबाद की ऐतिहासिक धरोहर है जिसमें भद्रकाली माता का मंदिर स्थित है।",
        "keywords": ["Bhadra Fort", "Ahmedabad", "Ahmad Shah", "Bhadrakali", "Teen Darwaza", "ભદ્રનો કિલ્લો", "અમદાવાદ", "તીન દરવાજા"],
        "source": "Archaeological Survey of India / Ahmedabad Municipal Corporation",
        "source_type": "ASI Protected Monument",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_14",
        "category": "Historical Places",
        "title": "તારંગા જૈન તીર્થ (Taranga Hill Jain Temples)",
        "title_en": "Taranga Jain Temples",
        "district": "Mehsana",
        "question_gu": "તારંગા પર્વત પર આવેલા અજિતનાથ જૈન મંદિર વિશે જણાવો.",
        "question_hi": "तारंगा पहाड़ी पर स्थित अजितनाथ जैन मंदिर के बारे में बताएं।",
        "question_mr": "तारंगा डोंगरावरील अजितनाथ जैन मंदिराविषयी सांगा.",
        "question_en": "Tell me about Ajitnath Jain Temple on Taranga Hill.",
        "question_roman_gu": "Taranga parvat par aavela Ajitnath Jain mandir vishe janavo.",
        "answer_gu": "તારંગા હિલ ઉત્તર ગુજરાતના મહેસાણા જિલ્લામાં ખેરાલુ પાસે આવેલું પવિત્ર જૈન અને બૌદ્ધ યાત્રાધામ છે. અહીં ૧૨મી સદીમાં (ઈ.સ. ૧૧૬૧) સોલંકી રાજા કુમારપાળે બીજા તીર્થંકર ભગવાન અજિતનાથનું ભવ્ય અને વિશાળ શ્વેતાંબર જૈન મંદિર બનાવડાવ્યું હતું. આ મંદિર પીળા રેતીયા પથ્થરથી મારુ-ગુર્જર સ્થાપત્ય શૈલીમાં નિર્મિત છે. મંદિરની સ્થાપત્ય કળા, ઊંચું શિખર અને શાંત વાતાવરણ અદભુત છે. નજીકમાં પ્રાચીન બૌદ્ધ ગુફાઓ અને તારા દેવીનું સ્થાનક પણ આવેલું છે.",
        "short_answer_gu": "મહેસાણામાં આવેલું ૧૨મી સદીમાં રાજા કુમારપાળ નિર્મિત ભગવાન અજિતનાથનું ભવ્ય જૈન તીર્થ અને પ્રાચીન બૌદ્ધ ગુફાઓ.",
        "short_answer_en": "Taranga Hill in Mehsana houses a majestic 12th-century Jain temple dedicated to Tirthankara Ajitnath, built by Solanki King Kumarpal.",
        "short_answer_hi": "मेहसाणा में स्थित तारंगा पहाड़ी पर १२वीं सदी में राजा कुमारपाल द्वारा निर्मित भगवान अजितनाथ का प्रसिद्ध जैन मंदिर स्थित है।",
        "keywords": ["Taranga", "Ajitnath", "Kumarpal", "Jain Temple", "Mehsana", "Buddhist Caves", "તારંગા", "અજિતનાથ", "કુમારપાળ"],
        "source": "Archaeological Survey of India / Gujarat Tourism",
        "source_type": "ASI Monument & Jain Tirth",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_15",
        "category": "Historical Places",
        "title": "શામળાજી પ્રાચીન વિષ્ણુ મંદિર (Shamlaji Temple Aravalli)",
        "title_en": "Shamlaji Temple",
        "district": "Aravalli",
        "question_gu": "શામળાજી મંદિર અને મેશ્વો નદી તટનો મેળો જણાવો.",
        "question_hi": "शामलाजी मंदिर और मेश्वां नदी तट के मेले के बारे में बताएं।",
        "question_mr": "शामळाजी मंदिर आणि मेष्वो नदी काठच्या जत्रेविषयी माहिती द्या.",
        "question_en": "Tell me about Shamlaji Temple on Meshwo river and its fair.",
        "question_roman_gu": "Shamlaji mandir ane Meshwo nadi tat no melo janavo.",
        "answer_gu": "શામળાજી મંદિર અરવલ્લી જિલ્લામાં મેશ્વો નદીના કિનારે આવેલું ૧૧મી સદીનું પ્રાચીન અને અતિ પવિત્ર વિષ્ણુ (ગદાધર શ્યામ) મંદિર છે. આ મંદિર સફેદ સેન્ડસ્ટોન અને આરસથી બનેલું છે અને તેની બાહ્ય દીવાલો પર રામાયણ અને મહાભારતના પ્રસંગો, હાથીઓ અને દેવી-દેવતાઓના હજારો જીવંત શિલ્પો કંડારાયેલાં છે. કાર્તિકી પૂનમે અહીં શામળાજીનો સુપ્રસિદ્ધ આદિવાસી મેળો ભરાય છે, જ્યાં 'શામળાજીના મેળે રણઝણિયું વાગે' લોકગીત ખૂબ ગવાય છે. નજીકમાં દેવની મોરી બૌદ્ધ સ્તૂપના અવશેષો પણ મળેલા છે.",
        "short_answer_gu": "અરવલ્લીમાં મેશ્વો નદી તટે આવેલું ભગવાન ગદાધર વિષ્ણુનું પ્રાચીન શિલ્પકળા ધરાવતું મંદિર અને કાર્તિકી પૂનમનો મેળો.",
        "short_answer_en": "Shamlaji Temple on Meshwo river in Aravalli district is an 11th-century Vishnu temple famous for intricate stone sculptures and its tribal fair.",
        "short_answer_hi": "अरावली में मेश्वां नदी के तट पर स्थित शामलाजी मंदिर भगवान विष्णु का प्राचीन मंदिर है जो अपनी शिल्पकला और कार्तिक मेले के लिए प्रसिद्ध है।",
        "keywords": ["Shamlaji", "Vishnu Temple", "Meshwo River", "Aravalli", "Gadadhar", "Kartiki Poonam", "શામળાજી", "મેશ્વો નદી", "વિષ્ણુ મંદિર"],
        "source": "Archaeological Survey of India / Gujarat Tourism",
        "source_type": "ASI Protected Heritage",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_16",
        "category": "Historical Places",
        "title": "કીર્તિ મંદિર - પોરબંદર (Kirti Mandir Porbandar - Gandhi Birthplace)",
        "title_en": "Kirti Mandir Porbandar",
        "district": "Porbandar",
        "question_gu": "પોરબંદરના કીર્તિ મંદિર વિશે જણાવો જ્યાં ગાંધીજીનો જન્મ થયો હતો.",
        "question_hi": "पोरबंदर के कीर्ति मंदिर के बारे में बताएं जहां गांधीजी का जन्म हुआ था।",
        "question_mr": "पोरबंदर येथील कीर्ति मंदिराविषयी सांगा जिथे गांधीजींचा जन्म झाला.",
        "question_en": "Tell me about Kirti Mandir in Porbandar, the birthplace of Mahatma Gandhi.",
        "question_roman_gu": "Porbandar na Kirti Mandir vishe janavo jya Gandhiji no janma thayo hato.",
        "answer_gu": "કીર્તિ મંદિર પોરબંદરમાં આવેલું મહાત્મા ગાંધી અને કસ્તૂરબા ગાંધીનું મુખ્ય સ્મારક છે. અહીં ૨ ઓક્ટોબર ૧૮૬૯ના રોજ ગાંધીજીનો જન્મ થયો હતો તે મૂળ ત્રણ માળનું પૈતૃક મકાન અકબંધ સાચવવામાં આવ્યું છે. ૧૯૫૦માં ઉદ્યોગપતિ નાનજી કાલિદાસ મહેતા દ્વારા મૂળ ઘરની બાજુમાં ૭૯ ફૂટ ઊંચું (ગાંધીજીના ૭૯ વર્ષના આયુષ્યનું પ્રતીક) ભવ્ય કીર્તિ મંદિર બનાવવામાં આવ્યું હતું, જેનું ઉદ્ઘાટન સરદાર વલ્લભભાઈ પટેલે કર્યું હતું. અહીં ગાંધીજીના જીવનની દુર્લભ તસવીરો અને પુસ્તકાલય આવેલાં છે.",
        "short_answer_gu": "પોરબંદરમાં મહાત્મા ગાંધીનું જન્મસ્થળ અને સ્મારક, જેમાં ૭૯ ફૂટ ઊંચું મંદિર અને પૈતૃક ઘર આવેલું છે.",
        "short_answer_en": "Kirti Mandir in Porbandar marks the ancestral birthplace of Mahatma Gandhi, featuring a 79-foot monument built by Nanji Kalidas Mehta.",
        "short_answer_hi": "पोरबंदर में स्थित कीर्ति मंदिर महात्मा गांधी का जन्मस्थान और राष्ट्रीय स्मारक है जिसका उद्घाटन सरदार पटेल ने किया था।",
        "keywords": ["Kirti Mandir", "Porbandar", "Mahatma Gandhi Birthplace", "Kasturba", "Nanji Kalidas Mehta", "કીર્તિ મંદિર", "પોરબંદર", "ગાંધી જન્મસ્થળ"],
        "source": "Kirti Mandir Memorial Trust / Gujarat Tourism",
        "source_type": "National Memorial",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_17",
        "category": "Historical Places",
        "title": "હીરા ભાગોળ - ડભોઈ (Hira Bhagol Dabhoi Fort Gate)",
        "title_en": "Hira Bhagol Dabhoi",
        "district": "Vadodara",
        "question_gu": "ડભોઈના ઐતિહાસિક કિલ્લા અને હીરા ભાગોળ વિશે માહિતી આપો.",
        "question_hi": "डभोई के ऐतिहासिक किले और हीरा भागोल के बारे में बताएं।",
        "question_mr": "डभोईच्या ऐतिहासिक किल्ल्याविषयी आणि हिरा भागोलविषयी सांगा.",
        "question_en": "Give information about Dabhoi Fort and the famous Hira Bhagol gate.",
        "question_roman_gu": "Dabhoi na killa ane Hira Bhagol vishe mahiti aapo.",
        "answer_gu": "હીરા ભાગોળ વડોદરા જિલ્લાના ડભોઈ (પ્રાચીન દર્ભાવતી) ખાતે આવેલા ૧૩મી સદીના ઐતિહાસિક કિલ્લાનો પૂર્વીય દરવાજો છે. આ કિલ્લા અને દરવાજાઓનું પુનઃનિર્માણ સોલંકી/વાઘેલા રાજા વીરધવલ અને વિસલદેવના સમયમાં શિલ્પી હીરાધર (હીરો કડિયા) દ્વારા કરવામાં આવ્યું હતું. હીરા ભાગોળ તેના અત્યંત બારીક અને નયનરમ્ય પથ્થર કોતરણીકામ, પૌરાણિક કથાઓના શિલ્પો અને ભારતીય કિલ્લેબંધી સ્થાપત્ય માટે પ્રખ્યાત છે. શિલ્પી હીરાની પ્રેમકથા અને બલિદાન સાથે આ દરવાજાનું નામ જોડાયેલું છે.",
        "short_answer_gu": "ડભોઈમાં આવેલો ૧૩મી સદીનો પ્રાચીન કિલ્લાનો દરવાજો, જે અદભુત પથ્થર શિલ્પકળા અને શિલ્પી હીરાધરની કથા માટે જાણીતો છે.",
        "short_answer_en": "Hira Bhagol is the richly carved 13th-century eastern gate of Dabhoi Fort, designed by master architect Hiradhar during the Solanki-Vaghela era.",
        "short_answer_hi": "डभोई का हीरा भागोल १३वीं सदी के किले का नक्काशीदार पूर्वी द्वार है जो अपनी शानदार शिल्पकला के लिए जाना जाता है।",
        "keywords": ["Hira Bhagol", "Dabhoi", "Vadodara", "Fort Gate", "Hiradhar", "Visaldev", "હીરા ભાગોળ", "ડભોઈ", "વડોદરા"],
        "source": "Archaeological Survey of India",
        "source_type": "ASI Monument of National Importance",
        "source_url": "https://asi.nic.in"
    },
    {
        "id": "hist_18",
        "category": "Historical Places",
        "title": "તાંબેકર વાડા - વડોદરા (Tambekar Wada Murals Vadodara)",
        "title_en": "Tambekar Wada",
        "district": "Vadodara",
        "question_gu": "વડોદરાના તાંબેકર વાડાના ભીંતચિત્રો વિશે જણાવો.",
        "question_hi": "वडोदरा के तांबेकर वाड़ा के भित्तिचित्रों के बारे में बताएं।",
        "question_mr": "वडोदरा येथील तांबेकर वाड्याच्या भित्तीचित्रांविषयी सांगा.",
        "question_en": "Tell me about the 19th-century wall paintings of Tambekar Wada in Vadodara.",
        "question_roman_gu": "Vadodara na Tambekar Wada na bhintchitro vishe janavo.",
        "answer_gu": "તાંબેકર વાડા વડોદરાના રાવપુરા વિસ્તારમાં આવેલી ૧૯મી સદીની મરાઠા શૈલીની ચાર માળની ઐતિહાસિક હવેલી છે, જે બરોડા રિયાસતના દિવાન ભાઉ તાંબેકરનું નિવાસસ્થાન હતી. આ હવેલી તેની દીવાલો અને છત પર દોરાયેલા અદભુત ૧૯મી સદીના ભીંતચિત્રો (Fresco Murals) માટે વિખ્યાત છે. ચિત્રોમાં મહાભારત, રામાયણ, શ્રીકૃષ્ણ લીલા, ૧૮૫૭ના વિપ્લવના યુરોપિયન અને મરાઠા સૈનિકોના દ્રશ્યો કુદરતી રંગોથી કંડારાયેલાં છે. ભારતીય પુરાતત્વ સર્વેક્ષણ (ASI) દ્વારા તેને સંરક્ષિત સ્મારક જાહેર કરાયું છે.",
        "short_answer_gu": "વડોદરામાં આવેલી ૧૯મી સદીની મરાઠા હવેલી, જે રામાયણ, મહાભારત અને ૧૮૫૭ના વિપ્લવના ભીંતચિત્રો માટે જાણીતી છે.",
        "short_answer_en": "Tambekar Wada in Vadodara is a 19th-century Maratha-style mansion renowned for its exquisite fresco murals depicting mythological epics and 1857 war scenes.",
        "short_answer_hi": "वडोदरा का तांबेकर वाड़ा १९वीं सदी की मराठा हवेली है जो रामायण-महाभारत और १८५७ के सुंदर भित्तिचित्रों के लिए प्रसिद्ध है।",
        "keywords": ["Tambekar Wada", "Vadodara", "Wall Paintings", "Murals", "Bhau Tambekar", "તાંબેકર વાડા", "વડોદરા", "ભીંતચિત્રો"],
        "source": "Archaeological Survey of India",
        "source_type": "ASI Monument of National Importance",
        "source_url": "https://asi.nic.in"
    },

    # =========================================================================
    # ADDITIONAL RELIGIOUS & SPIRITUAL PLACES (39-48)
    # =========================================================================
    {
        "id": "rel_07",
        "category": "Religious Places",
        "title": "નાગેશ્વર જ્યોતિર્લિંગ (Nageshwar Jyotirlinga Temple Dwarka)",
        "title_en": "Nageshwar Jyotirlinga",
        "district": "Devbhumi Dwarka",
        "question_gu": "નાગેશ્વર જ્યોતિર્લિંગ વિશે જણાવો.",
        "question_hi": "नागेश्वर ज्योतिर्लिंग के बारे में बताएं।",
        "question_mr": "नागेश्वर ज्योतिर्लिंगाविषयी सांगा.",
        "question_en": "Tell me about Nageshwar Jyotirlinga near Dwarka.",
        "question_roman_gu": "Nageshwar Jyotirlinga vishe janavo.",
        "answer_gu": "નાગેશ્વર જ્યોતિર્લિંગ ગુજરાતના દેવભૂમિ દ્વારકા જિલ્લામાં દ્વારકા અને બેટ દ્વારકા વચ્ચે દારૂકાવન ક્ષેત્રમાં આવેલું છે. તે ભગવાન શિવના ૧૨ પવિત્ર જ્યોતિર્લિંગોમાંનું એક છે. શિવપુરાણ અનુસાર નાગેશ્વરને 'દારૂકાવને નાગેશમ્' કહેવામાં આવ્યું છે, જે પૃથ્વી પરના પ્રથમ જ્યોતિર્લિંગો પૈકીનું મનાય છે. અહીં મંદિર પરિસરમાં ધ્યાનાવસ્થામાં બિરાજમાન ભગવાન શિવની ૮૦ ફૂટ ઊંચી વિશાળ અને ભવ્ય પ્રતિમા સ્થાપિત છે જે દૂરથી જ આકર્ષિત કરે છે.",
        "short_answer_gu": "દ્વારકા પાસે દારૂકાવનમાં આવેલું ભગવાન શિવનું પવિત્ર જ્યોતિર્લિંગ, જ્યાં શિવજીની ૮૦ ફૂટ ઊંચી પ્રતિમા સ્થાપિત છે.",
        "short_answer_en": "Nageshwar near Dwarka is one of the twelve sacred Jyotirlingas of Lord Shiva, featuring an 80-foot giant statue of Lord Shiva.",
        "short_answer_hi": "द्वारका के पास स्थित नागेश्वर भगवान शिव के १२ पवित्र ज्योतिर्लिंगों में से एक है, जहाँ ८० फीट ऊंची शिव प्रतिमा स्थापित है।",
        "keywords": ["Nageshwar", "Jyotirlinga", "Dwarka", "Darukavan", "Shiva", "નાગેશ્વર", "જ્યોતિર્લિંગ", "દ્વારકા"],
        "source": "Gujarat Tourism / Shree Nageshwar Trust",
        "source_type": "One of 12 Jyotirlingas",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "rel_08",
        "category": "Religious Places",
        "title": "બહુચરાજી શક્તિપીઠ (Bahucharaji Temple Mehsana)",
        "title_en": "Bahucharaji Temple",
        "district": "Mehsana",
        "question_gu": "બહુચરાજી મંદિર અને કૂકડાની સવારી વિશે જણાવો.",
        "question_hi": "बहुचराजी मंदिर और कुक्कुट (मुर्गे) की सवारी के बारे में बताएं।",
        "question_mr": "बहुचराजी मंदिराविषयी सांगा.",
        "question_en": "Tell me about Bahucharaji Temple in Mehsana and the rooster vahana.",
        "question_roman_gu": "Bahucharaji mandir ane kukada ni savari vishe janavo.",
        "answer_gu": "બહુચરાજી મંદિર ઉત્તર ગુજરાતના મહેસાણા જિલ્લાના બેચરાજી તાલુકામાં આવેલું ગુજરાતનું અગ્રણી શક્તિપીઠ છે. માન્યતા અનુસાર અહીં માતા સતીનો ડાબો હાથ પડ્યો હતો. બહુચર માતાનું વાહન કૂકડો (Rooster/Cock) છે અને તેઓ ત્રિશૂળધારી કન્યા સ્વરૂપે પૂજાય છે. આ મંદિર નાના બાળકોના બાબરી (ચૌલ સંસ્કાર) અને કિન્નર સમુદાયના આરાધ્ય દેવી તરીકે વિશેષ મહત્વ ધરાવે છે. ચૈત્રી પૂનમે અહીં લાખો ભક્તોનો ભવ્ય મેળો ભરાય છે.",
        "short_answer_gu": "મહેસાણામાં આવેલું પવિત્ર શક્તિપીઠ, જ્યાં બહુચર માતા કૂકડાના વાહન સાથે પૂજાય છે અને ચૈત્રી પૂનમે મેળો ભરાય છે.",
        "short_answer_en": "Bahucharaji in Mehsana is a revered Shaktipeeth where Goddess Bahuchara is worshipped with a rooster as her vahana.",
        "short_answer_hi": "मेहसाणा में स्थित बहुचराजी प्रमुख शक्तिपीठ है जहाँ देवी बहुचरा मुर्गे की सवारी के साथ पूजी जाती हैं।",
        "keywords": ["Bahucharaji", "Becharaji", "Mehsana", "Shaktipeeth", "Rooster", "Chaitri Poonam", "બહુચરાજી", "બેચરાજી", "શક્તિપીઠ", "કૂકડો"],
        "source": "Shree Bahucharaji Mataji Temple Trust / Gujarat Tourism",
        "source_type": "Major Shaktipeeth",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "rel_09",
        "category": "Religious Places",
        "title": "સાળંગપુર કષ્ટભંજન હનુમાનજી મંદિર (Sarangpur Hanuman Temple)",
        "title_en": "Sarangpur Hanuman",
        "district": "Botad",
        "question_gu": "સાળંગપુર કષ્ટભંજનદેવ હનુમાનજી મંદિર વિશે માહિતી આપો.",
        "question_hi": "सांरगपुर कष्टभंजन हनुमान जी मंदिर के बारे में बताएं।",
        "question_mr": "सारंगपूर कष्टभंजन हनुमान मंदिराविषयी माहिती द्या.",
        "question_en": "Give information about Kashtbhanjan Dev Hanuman Temple at Sarangpur.",
        "question_roman_gu": "Sarangpur Kashtbhanjan Hanuman mandir vishe mahiti aapo.",
        "answer_gu": "સાળંગપુર હનુમાનજી મંદિર (શ્રી કષ્ટભંજનદેવ હનુમાનજી) ગુજરાતના બોટાદ જિલ્લાના સાળંગપુરમાં આવેલું સ્વામિનારાયણ સંપ્રદાયનું અત્યંત શ્રદ્ધાળુ યાત્રાધામ છે. આ મૂર્તિની સ્થાપના ઈ.સ. ૧૮૪૮ (વિક્રમ સંવત ૧૯૦૫)માં સદ્ગુરુ ગોપાળાનંદ સ્વામી દ્વારા કરવામાં આવી હતી. માન્યતા છે કે ગોપાળાનંદ સ્વામીએ લાકડીથી મૂર્તિને સ્પર્શ કરતાં મૂર્તિમાં દિવ્ય તેજ પ્રગટ થયું હતું. અહીં હનુમાનજી શનિદેવના અહંકારનું મર્દન કરી સ્ત્રી સ્વરૂપ શનિદેવ પર ચરણ મૂકેલી મુદ્રામાં છે. શનિવાર અને મંગળવારે દેશભરમાંથી લાખો ભક્તો કષ્ટ નિવારણ માટે દર્શને આવે છે. અહીં ૫૪ ફૂટ ઊંચી 'કિંગ ઓફ સાળંગપુર' પ્રતિમા સ્થાપિત છે.",
        "short_answer_gu": "બોટાદના સાળંગપુરમાં ગોપાળાનંદ સ્વામી દ્વારા સ્થાપિત કષ્ટભંજન હનુમાનજી મંદિર, જે શનિ-મંગળે લાખો ભક્તોના કષ્ટ હરે છે.",
        "short_answer_en": "Sarangpur Hanuman Temple in Botad district is a powerful pilgrimage site where Hanumanji was consecrated by Gopalanand Swami in 1848.",
        "short_answer_hi": "बोटाद के सारंगपुर में स्थित कष्टभंजन हनुमान मंदिर में शनिवार और मंगलवार को लाखों श्रद्धालु कष्ट निवारण हेतु आते हैं।",
        "keywords": ["Sarangpur", "Hanuman", "Kashtbhanjan", "Botad", "Gopalanand Swami", "King of Salangpur", "સાળંગપુર", "કષ્ટભંજન", "હનુમાનજી"],
        "source": "Shree Kashtbhanjan Dev Temple Trust / Gujarat Tourism",
        "source_type": "Renowned Hanuman Temple",
        "source_url": "https://salangpurhanumanji.org"
    },
    {
        "id": "rel_10",
        "category": "Religious Places",
        "title": "વીરપુર જલારામ બાપા મંદિર (Virpur Jalaram Bapa Temple)",
        "title_en": "Virpur Jalaram Bapa",
        "district": "Rajkot",
        "question_gu": "વીરપુરના સંત જલારામ બાપા અને સદાવ્રત પરંપરા વિશે જણાવો.",
        "question_hi": "वीरपुर के संत जलाराम बापा और सदाव्रत परंपरा के बारे में बताएं।",
        "question_mr": "वीरपूरचे संत जलाराम बापा आणि सदाव्रत परंपरेविषयी सांगा.",
        "question_en": "Tell me about Sant Jalaram Bapa of Virpur and the Sadavrat tradition.",
        "question_roman_gu": "Virpur na Sant Jalaram Bapa ane Sadavrat parampara vishe janavo.",
        "answer_gu": "વીરપુર ગુજરાતના રાજકોટ જિલ્લામાં આવેલું પરમ પૂજ્ય સંત શિરોમણી જલારામ બાપા (૧૭૯૯ - ૧૮૮૧)નું તીર્થધામ છે. જલારામ બાપાએ ઈ.સ. ૧૮૨૦માં માત્ર ૨૦ વર્ષની વયે વીરપુરમાં 'સદાવ્રત' (અન્નક્ષેત્ર) શરૂ કર્યું હતું, જ્યાં કોઈપણ જાતપાત કે ભેદભાવ વિના આવનાર દરેક વ્યક્તિને ગાંઠિયા, ખીચડી-કઢી અને રોટલો પ્રેમપૂર્વક ખવડાવવામાં આવતો હતો. વીરપુર મંદિરની વિશ્વમાં અજોડ વિશેષતા એ છે કે વર્ષ ૨૦૦૦ની ૯ ફેબ્રુઆરીથી મંદિરે કોઈપણ પ્રકારનું દાન કે ભેટ સ્વીકારવાનું સંપૂર્ણપણે બંધ કરી દીધું છે. છતાં હજારો લોકોને દરરોજ વિનામૂલ્યે ભોજન-પ્રસાદ અવિરત પીરસાય છે.",
        "short_answer_gu": "રાજકોટના વીરપુરમાં સંત જલારામ બાપાનું ધામ, જે વિશ્વનું એકમાત્ર એવું મંદિર છે જ્યાં કોઈ દાન સ્વીકારાતું નથી છતાં અવિરત સદાવ્રત ચાલે છે.",
        "short_answer_en": "Virpur in Rajkot is the shrine of Sant Jalaram Bapa, famous for running an uninterrupted free community kitchen (Sadavrat) since 1820 without accepting any donations.",
        "short_answer_hi": "राजकोट के वीरपुर में स्थित संत जलाराम बापा का मंदिर विश्व का एकमात्र ऐसा तीर्थ है जो बिना कोई दान स्वीकार किए निरंतर सदाव्रत चलाता है।",
        "keywords": ["Virpur", "Jalaram Bapa", "Sadavrat", "Rajkot", "No Donation", "Khichdi", "વીરપુર", "જલારામ બાપા", "સદાવ્રત", "રાજકોટ"],
        "source": "Shree Jalaram Mandir Virpur / Gujarat Tourism",
        "source_type": "Spiritual Landmark",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "rel_11",
        "category": "Religious Places",
        "title": "ભાલકા તીર્થ - પ્રભાસ પાટણ (Bhalka Tirth Veraval)",
        "title_en": "Bhalka Tirth",
        "district": "Gir Somnath",
        "question_gu": "ભાલકા તીર્થ અને શ્રીકૃષ્ણના દેહોત્સર્ગ વિશે માહિતી આપો.",
        "question_hi": "भालका तीर्थ और भगवान श्रीकृष्ण के देहोत्सर्ग के बारे में बताएं।",
        "question_mr": "भालका तीर्थ आणि भगवान श्रीकृष्णाच्या देहत्यागाविषयी माहिती द्या.",
        "question_en": "Tell me about Bhalka Tirth and the departure of Lord Krishna.",
        "question_roman_gu": "Bhalka Tirth ane Krishna na dehotsarg vishe mahiti aapo.",
        "answer_gu": "ભાલકા તીર્થ ગુજરાતના ગીર સોમનાથ જિલ્લામાં સોમનાથ મંદિરથી આશરે ૪ કિમી દૂર વેરાવળ નજીક આવેલું પરમ પવિત્ર ઐતિહાસિક સ્થળ છે. હિન્દુ માન્યતા અનુસાર મહાભારતના યુદ્ધના ૩૬ વર્ષ બાદ ભગવાન શ્રીકૃષ્ણ જ્યારે પીપળાના વૃક્ષ નીચે વિશ્રામ કરી રહ્યા હતા, ત્યારે જરા નામના પારધીનું તીર તેમના ચરણ કમળમાં વાગ્યું હતું. આ ઘટના બાદ શ્રીકૃષ્ણએ નજીકમાં ત્રિવેણી સંગમ (દેહોત્સર્ગ તીર્થ) ખાતે પોતાની પૃથ્વી પરની લીલા સંકેલી પરમધામ પ્રસ્થાન કર્યું અને કળિયુગની શરૂઆત થઈ. અહીં શયન મુદ્રામાં શ્રીકૃષ્ણની સુંદર શ્યામ મૂર્તિ સ્થાપિત છે.",
        "short_answer_gu": "સોમનાથ પાસેનું પવિત્ર તીર્થ જ્યાં પીપળા નીચે પારધીનું તીર વાગ્યા બાદ ભગવાન શ્રીકૃષ્ણએ પૃથ્વી પરથી પરમધામ પ્રસ્થાન કર્યું હતું.",
        "short_answer_en": "Bhalka Tirth near Somnath is the sacred site where Lord Krishna was hit by an arrow from hunter Jara before ascending to his heavenly abode.",
        "short_answer_hi": "सोमनाथ के निकट स्थित भालका तीर्थ वह पावन स्थल है जहाँ जरा नामक शिकारी का तीर लगने के बाद भगवान श्रीकृष्ण ने अपनी पार्थिव लीला समाप्त की थी।",
        "keywords": ["Bhalka Tirth", "Krishna", "Somnath", "Veraval", "Jara Hunter", "Dehotsarg", "ભાલકા તીર્થ", "શ્રીકૃષ્ણ", "વેરાવળ"],
        "source": "Shree Somnath Trust",
        "source_type": "Sacred Krishna Heritage",
        "source_url": "https://somnath.org"
    },

    # =========================================================================
    # ADDITIONAL PERSONALITIES & LITERARY GIANTS (49-60)
    # =========================================================================
    {
        "id": "pers_08",
        "category": "Historical Personalities",
        "title": "મોરારજી દેસાઈ - ભારતના પ્રથમ બિન-કોંગ્રેસી વડાપ્રધાન (Morarji Desai)",
        "title_en": "Morarji Desai",
        "district": "Valsad",
        "question_gu": "મોરારજી દેસાઈ વિશે જણાવો: ભારતના વડાપ્રધાન અને ભારત રત્ન.",
        "question_hi": "मोरारजी देसाई के बारे में बताएं: भारत के प्रधानमंत्री और भारत रत्न।",
        "question_mr": "मोरारजी देसाई यांच्याविषयी सांगा: भारताचे पंतप्रधान आणि भारतरत्न.",
        "question_en": "Tell me about Morarji Desai, the first non-Congress Prime Minister of India.",
        "question_roman_gu": "Morarji Desai vishe janavo: Bharat na Vada Pradhan.",
        "answer_gu": "મોરારજી રણછોડજી દેસાઈ (૨૯ ફેબ્રુઆરી ૧૮૯૬ - ૧૦ એપ્રિલ ૧૯૯૫) ગુજરાતના વલસાડ જિલ્લાના ભદેલી ગામમાં જન્મેલા અગ્રણી સ્વાતંત્ર્ય સેનાની અને ૧૯૭૭ થી ૧૯૭૯ દરમિયાન ભારતના ચોથા વડાપ્રધાન (પ્રથમ બિન-કોંગ્રેસી વડાપ્રધાન) હતા. તેઓ ગાંધીવાદી મૂલ્યો, શિસ્ત અને સિદ્ધાંતનિષ્ઠા માટે જાણીતા હતા. તેઓ ભારતના સર્વોચ્ચ નાગરિક સન્માન 'ભારત રત્ન' (૧૯૯૧) અને પાકિસ્તાનના સર્વોચ્ચ નાગરિક સન્માન 'નિશાન-એ-પાકિસ્તાન' (૧૯૯૦) બંને મેળવનારા એકમાત્ર ભારતીય વ્યક્તિ છે. અમદાવાદમાં સાબરમતી આશ્રમ નજીક 'અભય ઘાટ' તેમનું સ્મારક છે.",
        "short_answer_gu": "વલસાડમાં જન્મેલા ભારતના ૪થા વડાપ્રધાન અને ભારત રત્ન તથા નિશાન-એ-પાકિસ્તાન બંને મેળવનાર એકમાત્ર ભારતીય.",
        "short_answer_en": "Morarji Desai from Valsad was India's 4th Prime Minister (first non-Congress PM) and the only individual honored with both Bharat Ratna and Nishan-e-Pakistan.",
        "short_answer_hi": "वलसाड में जन्मे मोरारजी देसाई भारत के चौथे प्रधानमंत्री थे और भारत रत्न व निशान-ए-पाकिस्तान दोनों सर्वोच्च नागरिक सम्मान पाने वाले एकमात्र भारतीय हैं।",
        "keywords": ["Morarji Desai", "Prime Minister", "Bharat Ratna", "Valsad", "Abhay Ghat", "મોરારજી દેસાઈ", "વડાપ્રધાન", "ભારત રત્ન"],
        "source": "PMO India / National Archives",
        "source_type": "Prime Ministerial Biography",
        "source_url": "https://www.pmindia.gov.in"
    },
    {
        "id": "pers_09",
        "category": "Historical Personalities",
        "title": "મહર્ષિ દયાનંદ સરસ્વતી (Swami Dayananda Saraswati - Arya Samaj)",
        "title_en": "Swami Dayananda Saraswati",
        "district": "Morbi (Tankara)",
        "question_gu": "દયાનંદ સરસ્વતી, તેમનું વતન ટંકારા અને આર્ય સમાજ વિશે જણાવો.",
        "question_hi": "दयानंद सरस्वती, उनका जन्मस्थान टंकारा और आर्य समाज के बारे में बताएं।",
        "question_mr": "स्वामी दयानंद सरस्वती, त्यांचे जन्मगाव टंकारा आणि आर्य समाजाविषयी सांगा.",
        "question_en": "Tell me about Swami Dayananda Saraswati, Tankara, and Arya Samaj.",
        "question_roman_gu": "Dayananda Saraswati, Tankara ane Arya Samaj vishe janavo.",
        "answer_gu": "મહર્ષિ દયાનંદ સરસ્વતી (મૂળ નામ: મૂળશંકર તિવારી; ૧૮૨૪ - ૧૮૮૩)નો જન્મ ગુજરાતના મોરબી જિલ્લાના ટંકારા ગામમાં થયો હતો. તેઓ મહાન વૈદિક વિદ્વાન, સમાજસુધારક અને ૧૮૭૫માં 'આર્‍ય સમાજ' (Arya Samaj)ના સ્થાપક હતા. તેમણે 'વેદો તરફ પાછા વળો' (Back to the Vedas)નો ઐતિહાસિક નારો આપ્યો અને 'સત્યાર્થ પ્રકાશ' નામનો ક્રાંતિકારી ગ્રંથ રચ્યો. તેમણે બાળલગ્ન, અસ્પૃશ્યતા અને અંધશ્રદ્ધાનો વિરોધ કર્યો તથા સ્ત્રી શિક્ષણ અને વિધવા પુનઃવિવાહનું જોરદાર સમર્થન કર્યું હતું.",
        "short_answer_gu": "મોરબીના ટંકારામાં જન્મેલા મહાન વૈદિક સુધારક અને ૧૮૭૫માં આર્ય સમાજના સ્થાપક, જેમણે 'સત્યાર્થ પ્રકાશ'ની રચના કરી.",
        "short_answer_en": "Swami Dayananda Saraswati was born in Tankara (Morbi), Gujarat in 1824; he founded Arya Samaj in 1875 and authored 'Satyarth Prakash'.",
        "short_answer_hi": "टंकारा (मोरबी) में जन्मे स्वामी दयानंद सरस्वती ने १८७५ में आर्य समाज की स्थापना की और 'वेदों की ओर लौटो' का आह्वान किया।",
        "keywords": ["Dayananda Saraswati", "Tankara", "Arya Samaj", "Satyarth Prakash", "Morbi", "દયાનાંદ સરસ્વતી", "ટંકારા", "આર્ય સમાજ"],
        "source": "Arya Samaj Heritage / Gujarat Sahitya Academy",
        "source_type": "Social & Spiritual Reformer",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "pers_10",
        "category": "Historical Personalities",
        "title": "પૂજ્ય રવિશંકર મહારાજ - મુઠ્ઠી ઊંચેરો માનવી (Ravishankar Maharaj)",
        "title_en": "Ravishankar Maharaj",
        "district": "Kheda (Radhu / Saraspur)",
        "question_gu": "રવિશંકર મહારાજનું ગુજરાતની સ્થાપના અને સમાજસેવામાં પ્રદાન જણાવો.",
        "question_hi": "रविशंकर महाराज का गुजरात की स्थापना और समाज सेवा में योगदान बताएं।",
        "question_mr": "रविशंकर महाराज यांचे गुजरातची स्थापना आणि समाजसेवेतील योगदान सांगा.",
        "question_en": "Explain Ravishankar Maharaj's contribution to Gujarat's formation and social service.",
        "question_roman_gu": "Ravishankar Maharaj nu Gujarat ni sthapana ma yogdan janavo.",
        "answer_gu": "પૂજ્ય રવિશંકર મહારાજ (૧૮૮૪ - ૧૯૮૪) ગુજરાતના પરમ આદરણીય સંત, સ્વાતંત્ર્ય સેનાની અને 'મૂક સેવક' તરીકે ઓળખાતા સમાજસુધારક હતા. ઝવેરચંદ મેઘાણીએ તેમના જીવન પરથી 'માણસાઈના દીવા' પુસ્તક લખ્યું હતું, જેમાં બહારવટિયાઓ અને પાટણવાડિયા-બારૈયા કોમના પુનર્વસનનું હૃદયસ્પર્શી વર્ણન છે. ૧ મે ૧૯૬૦ના રોજ સાબરમતી આશ્રમ ખાતે તેમના પાવન હસ્તે અલગ 'ગુજરાત રાજ્ય'નું સત્તાવાર ઉદ્ઘાટન અને આશીર્વચન અપાયા હતા. તેમણે ભૂદાન આંદોલન અને સર્વોદય માટે આખું જીવન પગપાળા ફરીને સેવા કરી.",
        "short_answer_gu": "ગુજરાતના 'મૂક સેવક' અને સંત, જેમણે ૧ મે ૧૯૬૦ના રોજ ગુજરાત રાજ્યનું ઉદ્ઘાટન કર્યું અને 'માણસાઈના દીવા' પ્રગટાવ્યા.",
        "short_answer_en": "Ravishankar Maharaj was a revered saintly social reformer who inaugurated the State of Gujarat on 1 May 1960 and inspired Meghani's 'Mansai na Deeva'.",
        "short_answer_hi": "गुजरात के 'मूक सेवक' पूज्य रविशंकर महाराज ने १ मई १९६० को गुजरात राज्य का उद्घाटन किया था।",
        "keywords": ["Ravishankar Maharaj", "Mansai na Deeva", "Gujarat Day", "1 May 1960", "Muk Sevak", "રવિશંકર મહારાજ", "માણસાઈના દીવા", "ગુજરાત સ્થાપના"],
        "source": "Information Department, Govt of Gujarat",
        "source_type": "Historical Biography",
        "source_url": "https://gujaratinformation.gujarat.gov.in"
    },
    {
        "id": "pers_11",
        "category": "Historical Personalities",
        "title": "ઉમાશંકર જોશી - જ્ઞાનપીઠ વિજેતા કવિ (Umashankar Joshi - Nishith)",
        "title_en": "Umashankar Joshi",
        "district": "Sabarkantha (Bamana)",
        "question_gu": "ઉમાશંકર જોશી અને તેમના જ્ઞાનપીઠ પુરસ્કૃત કાવ્યસંગ્રહ 'નિશીથ' વિશે જણાવો.",
        "question_hi": "उमाशंकर जोशी और उनके ज्ञानपीठ पुरस्कृत काव्य संग्रह 'निशीथ' के बारे में बताएं।",
        "question_mr": "उमाशंकर जोशी आणि त्यांच्या ज्ञानपीठ पुरस्कार विजेत्या 'निशीथ' या काव्यसंग्रहाविषयी सांगा.",
        "question_en": "Tell me about the eminent poet Umashankar Joshi and his Jnanpith-winning work 'Nishith'.",
        "question_roman_gu": "Umashankar Joshi ane Nishith kavya sangrah vishe janavo.",
        "answer_gu": "ઉમાશંકર જેઠાલાલ જોશી (૧૯૧૧ - ૧૯૮૮) સાબરકાંઠાના બામણા ગામમાં જન્મેલા ૨૦મી સદીના સર્વોચ્ચ ગુજરાતી કવિ, નાટ્યકાર, વિવેચક અને વિચારક હતા. તેમના પ્રસિદ્ધ કાવ્યસંગ્રહ 'નિશીથ' (મધ્યરાત્રિનો અવાજ) માટે વર્ષ ૧૯૬૭માં તેમને કન્નડ કવિ કુવેમ્પુ સાથે સંયુક્ત રીતે ભારતનો સર્વોચ્ચ 'જ્ઞાનપીઠ પુરસ્કાર' (Jnanpith Award) મળ્યો હતો, જે જ્ઞાનપીઠ મેળવનાર સૌપ્રથમ ગુજરાતી સાહિત્યકાર બન્યા હતા. તેમની અમર પંક્તિ 'વ્યક્તિ મટીને બનું વિશ્વમાનવી, માથે ધરું ધૂળ વસુંધરાની' વિશ્વબંધુત્વનો સંદેશ આપે છે. તેઓ રાજ્યસભાના સાંસદ અને સાહિત્ય અકાદમીના પ્રમુખ પણ રહ્યા હતા.",
        "short_answer_gu": "૧૯૬૭માં 'નિશીથ' કાવ્યસંગ્રહ માટે સૌપ્રથમ જ્ઞાનપીઠ પુરસ્કાર મેળવનાર મહાન ગુજરાતી કવિ અને વિશ્વમાનવી.",
        "short_answer_en": "Umashankar Joshi was the first Gujarati writer to win the prestigious Jnanpith Award in 1967 for his poetry collection 'Nishith'.",
        "short_answer_hi": "१९६७ में अपने काव्य 'निशीथ' के लिए पहला ज्ञानपीठ पुरस्कार जीतने वाले उमाशंकर जोशी गुजराती साहित्य के मूर्धन्य कवि थे।",
        "keywords": ["Umashankar Joshi", "Jnanpith Award", "Nishith", "Vishwa Manavi", "Sabarkantha", "ઉમાશંકર જોશી", "નિશીથ", "જ્ઞાનપીઠ પુરસ્કાર"],
        "source": "Bharatiya Jnanpith / Gujarati Sahitya Parishad",
        "source_type": "First Gujarati Jnanpith Laureate",
        "source_url": "https://www.jnanpith.net"
    },
    {
        "id": "pers_12",
        "category": "Historical Personalities",
        "title": "કલાપી - સૂરસિંહજી તખ્તસિંહજી ગોહિલ (Kavi Kalapi - Prince of Lathi)",
        "title_en": "Kavi Kalapi",
        "district": "Amreli (Lathi)",
        "question_gu": "કવિ કલાપી (લાઠીના રાજવી) અને તેમના કાવ્યો વિશે જણાવો.",
        "question_hi": "कवि कलापी (लाठी के राजा) और उनकी कविताओं के बारे में बताएं।",
        "question_mr": "कवी कलापी आणि त्यांच्या कवितांविषयी सांगा.",
        "question_en": "Tell me about Prince-Poet Kalapi of Lathi and his romantic elegies.",
        "question_roman_gu": "Kavi Kalapi Lathi na rajvi ane temna kavyo vishe janavo.",
        "answer_gu": "સૂરસિંહજી તખ્તસિંહજી ગોહિલ 'કલાપી' (૧૮૭૪ - ૧૯૦૦) સૌરાષ્ટ્રના અમરેલી જિલ્લાના લાઠી રજવાડાના રાજવી અને અત્યંત સંવેદનશીલ રોમેન્ટિક કવિ હતા. માત્ર ૨૬ વર્ષની નાની વયે તેમનું અવસાન થયું હતું. તેમનો એકમાત્ર કાવ્યસંગ્રહ 'કલાપીનો કેકારવ' ગુજરાતી સાહિત્યનું અમર ઘરેણું છે. તેમની પ્રસિદ્ધ કાવ્યપંક્તિઓ 'જ્યાં જ્યાં નજર મારી ઠરે યાદી ભરી ત્યાં આપની', 'હા પસ્તાવો વિપુલ ઝરણું સ્વર્ગથી ઊતર્યું છે' અને ખંડકાવ્ય 'ગ્રામમાતા' આજે પણ દરેક ગુજરાતીના હૃદયમાં વસેલી છે. લાઠી ખાતે 'કલાપી તીર્થ' સ્મારક આવેલું છે.",
        "short_answer_gu": "લાઠી રજવાડાના પ્રણય અને દર્દના રાજકવિ, જેમણે 'કલાપીનો કેકારવ' અને 'ગ્રામમાતા' જેવાં અમર કાવ્યો આપ્યાં.",
        "short_answer_en": "Sursinhji Takhtasinhji Gohil 'Kalapi' (1874-1900), the Prince of Lathi, was a legendary romantic poet known for 'Kalapi no Kekarav'.",
        "short_answer_hi": "लाठी (अमरेली) के राजा कवि कलापी ने मात्र २६ वर्ष की आयु में 'कलापी नो केकारव' जैसी अमर काव्य रचनाएं दीं।",
        "keywords": ["Kalapi", "Lathi", "Amreli", "Kalapi no Kekarav", "Grammata", "Romantic Poet", "કલાપી", "લાઠી", "કેકારવ", "ગ્રામમાતા"],
        "source": "Gujarati Sahitya Parishad / Kalapi Tirth Trust",
        "source_type": "Literary Icon",
        "source_url": "https://gujaratisahityaparishad.com"
    },
    {
        "id": "pers_13",
        "category": "Historical Personalities",
        "title": "અખો - જ્ઞાની કવિ અને છપ્પાકાર (Akho - Medieval Satirical Poet)",
        "title_en": "Akho",
        "district": "Ahmedabad (Jekotni Pol)",
        "question_gu": "કવિ અખાના છપ્પા અને ઢોંગ-અંધશ્રદ્ધા પરના કટાક્ષ વિશે જણાવો.",
        "question_hi": "कवि अखा के छप्पय और पाखंड पर व्यंग्य के बारे में बताएं।",
        "question_mr": "कवी अखाचे छप्पय आणि अंधश्रद्धेवरील व्यंग्य याविषयी सांगा.",
        "question_en": "Tell me about Akho, the 17th-century philosopher-poet of Ahmedabad and his satirical Chhappa.",
        "question_roman_gu": "Akho kavi na chhappa ane andhashraddha par kataksh vishe janavo.",
        "answer_gu": "અક્ષયદાસ સોની 'અખો' (ઈ.સ. ૧૫૯૧ - ૧૬૫૬) ૧૭મી સદીના અમદાવાદના જેઠાભાઈની પોળમાં રહેતા મહાન જ્ઞાનમાર્ગી વેદાંતી કવિ અને કટાક્ષકાર હતા. તેઓ વ્યવસાયે સોની (સુવર્ણકાર) હતા. સંસારના દંભ, કપટ અને ગુરુઓના ઢોંગથી કંટાળીને તેમણે તીક્ષ્ણ કટાક્ષવાળા 'છપ્પા' (છ પંક્તિના કાવ્યો) રચ્યા. તેમના પ્રખ્યાત છપ્પા જેમ કે 'એક મૂરખને એવી ટેવ, પથ્થર એટલા પૂજે દેવ', 'ભાષાને શું વળગે ભૂર, જે રણમાં જીતે તે શૂર' અને ગ્રંથ 'અખેગીતા' ગુજરાતી સાહિત્યમાં જ્ઞાન અને વૈરાગ્યનું શિખર ગણાય છે.",
        "short_answer_gu": "અમદાવાદના ૧૭મી સદીના મહાન સુવર્ણકાર કવિ, જેમણે ઢોંગ-અંધશ્રદ્ધા સામે કટાક્ષભર્યા 'છપ્પા' અને 'અખેગીતા'ની રચના કરી.",
        "short_answer_en": "Akho was a 17th-century goldsmith-poet in Ahmedabad famous for his stinging philosophical six-line verses (Chhappa) mocking superstition.",
        "short_answer_hi": "१७वीं सदी के अहमदाबाद के संत कवि अखा ने पाखंड और अंधविश्वास पर तीखे व्यंग्य वाले 'छप्पय' रचे।",
        "keywords": ["Akho", "Chhappa", "Akhegita", "Ahmedabad", "Satirical Poet", "અખો", "છપ્પા", "અખેગીતા", "અમદાવાદ"],
        "source": "Gujarati Sahitya Parishad",
        "source_type": "Medieval Philosophical Poet",
        "source_url": "https://gujaratisahityaparishad.com"
    },

    # =========================================================================
    # ADDITIONAL GUJARATI CUISINE & SWEETS (61-72)
    # =========================================================================
    {
        "id": "food_07",
        "category": "Gujarati Cuisine",
        "title": "હાંડવો (Handvo - Savory Baked Lentil & Bottle Gourd Cake)",
        "title_en": "Handvo",
        "district": "All Gujarat",
        "question_gu": "હાંડવો કેવી રીતે બને છે અને તેની સામગ્રી શું છે?",
        "question_hi": "हांडवो कैसे बनता है और इसकी सामग्री क्या है?",
        "question_mr": "हांडवो कसा बनवला जातो आणि त्याचे साहित्य काय आहे?",
        "question_en": "What is Handvo and how is this traditional baked vegetable-lentil dish prepared?",
        "question_roman_gu": "Handvo kevi rite bane chhe ane teni samagri shu chhe?",
        "answer_gu": "હાંડવો એ ચોખા અને વિવિધ કઠોળ (ચણાની દાળ, તુવેર દાળ, અડદ દાળ)ના આથો લાવેલા મિશ્રણમાં છીણેલી દૂધી, આદુ-મરચાં, તેલ અને મસાલા ઉમેરીને બેક કરવામાં આવતી અત્યંત સ્વાદિષ્ટ અને પૌષ્ટિક વાનગી છે. પરંપરાગત રીતે તેને માટીના કે કાંસાના હાંડવામાં કોલસા પર શેકવામાં આવતો હતો, હવે તે ઓવન કે કૂકરમાં બને છે. તેની ઉપર તલ, રાઈ, હિંગ અને મીઠા લીમડાનો કરકરો વઘાર કરવામાં આવે છે. ઉપરથી ક્રિસ્પી અને અંદરથી પોચો હાંડવો લીલી ચટણી કે ચા સાથે પીરસાય છે.",
        "short_answer_gu": "ચોખા-દાળના આથામાં દૂધી અને તલના વઘાર સાથે બેક કરીને બનાવાતી પૌષ્ટિક અને ક્રિસ્પી ગુજરાતી વાનગી.",
        "short_answer_en": "Handvo is a nutritious, savory baked cake made from fermented rice-lentil batter mixed with grated bottle gourd (lauki) and tempered with sesame seeds.",
        "short_answer_hi": "हांडवो चावल और दालों के किण्वित घोल में लौकी और तिल का तड़का लगाकर पकाया जाने वाला स्वादिष्ट नमकीन केक है।",
        "keywords": ["Handvo", "Lauki", "Sesame", "Fermented Lentil Cake", "હાંડવો", "દૂધી", "તલનો વઘાર"],
        "source": "Traditional Gujarati Culinary Heritage",
        "source_type": "Nutritious Staple",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_08",
        "category": "Gujarati Cuisine",
        "title": "સુરતી લોચો (Surti Locho)",
        "title_en": "Surti Locho",
        "district": "Surat",
        "question_gu": "સુરતી લોચો શું છે અને તેની ઉત્પત્તિની વાર્તા શું છે?",
        "question_hi": "सूरटी लोचा क्या है और इसकी उत्पत्ति कैसे हुई?",
        "question_mr": "सुरती लोचो काय आहे आणि त्याचा इतिहास काय आहे?",
        "question_en": "What is Surti Locho and how did this famous Surat street food originate?",
        "question_roman_gu": "Surti Locho shu chhe ane te kevi rite banavay chhe?",
        "answer_gu": "સુરતી લોચો એ સુરત શહેરનું અત્યંત લોકપ્રિય અને અનોખું સ્ટ્રીટ ફૂડ છે. કહેવાય છે કે ખમણ બનાવતી વખતે ખીરામાં ભૂલથી વધારે પાણી પડી ગયું અને મિશ્રણ ઢીલું થઈ ગયું (લોચો વળી ગયો), પરંતુ જ્યારે તેને બાફીને તેલ, મસાલો અને સેવ સાથે પીરસવામાં આવ્યું ત્યારે લોકોને તેનો સ્વાદ ખૂબ પસંદ આવ્યો, આમ 'લોચો' નામ પડ્યું. તે ચણાની દાળના ઢીલા ખીરામાંથી વરાળમાં બાફીને બને છે અને તેની ઉપર બટર/તેલ, ખાસ લોચો મસાલો, ડુંગળી, લીલી ચટણી અને ભરપૂર ઝીણી સેવ નાખીને ગરમાગરમ ખવાય છે.",
        "short_answer_gu": "સુરતનું વિશ્વવિખ્યાત સ્ટ્રીટ ફૂડ, જે ચણાની દાળના બાફેલા ઢીલા મિશ્રણ પર બટર, મસાલો અને સેવ નાખીને પીરસાય છે.",
        "short_answer_en": "Surti Locho is an accidental culinary invention from Surat made of steamed, loose spiced gram flour batter served with butter, locho masala, and sev.",
        "short_answer_hi": "सूरत का मशहूर स्ट्रीट फूड 'लोचा' भाप में पकी चने की दाल के घोल से बनता है जिसे मक्खन, मसाले और सेव के साथ परोसा जाता है।",
        "keywords": ["Surti Locho", "Surat", "Street Food", "Butter Locho", "Sev", "સુરતી લોચો", "સુરત", "લોચો મસાલો"],
        "source": "Surat Culinary Heritage / Gujarat Tourism",
        "source_type": "Regional Street Food Icon",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_09",
        "category": "Gujarati Cuisine",
        "title": "દાળ ઢોકળી (Dal Dhokli)",
        "title_en": "Dal Dhokli",
        "district": "All Gujarat",
        "question_gu": "દાળ ઢોકળી કેવી રીતે બને છે અને તેનું મહત્વ શું છે?",
        "question_hi": "दाल ढोकली कैसे बनाई जाती है?",
        "question_mr": "वरण फळ / डाळ ढोकळी कशी बनवली जाते?",
        "question_en": "How is Dal Dhokli made and why is it considered the ultimate Gujarati comfort food?",
        "question_roman_gu": "Dal Dhokli kevi rite bane chhe?",
        "answer_gu": "દાળ ઢોકળી એ ગુજરાતી ઘરોનું સર્વોચ્ચ 'કમ્ફર્ટ ફૂડ' (Comfort Food) ગણાય છે. તે ઘઉંના લોટમાં મસાલા (અજમો, હળદર, મરચું, હિંગ) ભેળવીને વણેલી પાતળી રોટલીના ચોરસ કે હીરા આકારના ટુકડા (ઢોકળી) કરીને ઉકળતી ખાટી-મીઠી તુવેરની દાળમાં પકવીને બનાવવામાં આવે છે. દાળમાં સીંગદાણા, કોકમ/આંબલી, ગોળ અને ઘીનો રાઈ-જીરું-તજ-લવિંગનો સુગંધી વઘાર કરવામાં આવે છે. ગરમાગરમ દાળ ઢોકળી પર શુદ્ધ ઘી, લીંબુનો રસ અને કોથમીર નાખીને ભાત કે પાપડ સાથે આરોગવામાં આવે છે.",
        "short_answer_gu": "ખાટી-મીઠી તુવેરની દાળમાં ઘઉંની મસાલેદાર ઢોકળી પકવીને ઘી સાથે પીરસાતું ગુજરાતીઓનું પ્રિય ભોજન.",
        "short_answer_en": "Dal Dhokli is an iconic Gujarati one-pot comfort meal consisting of spiced whole wheat pasta dumplings simmered in sweet and tangy toor dal.",
        "short_answer_hi": "दाल ढोकली खट्टी-मीठी अरहर (तुवर) दाल में गेहूं के आटे की मसालेदार ढोकली पकाकर घी डालकर परोसा जाने वाला पारंपरिक व्यंजन है।",
        "keywords": ["Dal Dhokli", "Toor Dal", "Comfort Food", "Ghee", "Peanuts", "દાળ ઢોકળી", "તુવેર દાળ", "ઘી"],
        "source": "Gujarati Culinary Traditions",
        "source_type": "Traditional Home Cuisine",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_10",
        "category": "Gujarati Cuisine",
        "title": "મોહનથાળ અને શ્રીખંડ (Mohanthal and Shrikhand)",
        "title_en": "Mohanthal and Shrikhand",
        "district": "All Gujarat",
        "question_gu": "ગુજરાતી પારંપરિક મિઠાઈ મોહનથાળ અને શ્રીખંડ વિશે જણાવો.",
        "question_hi": "गुजराती पारंपरिक मिठाई मोहनथाल और श्रीखंड के बारे में बताएं।",
        "question_mr": "गुजराती पारंपरिक मिठाई मोहनथाळ आणि श्रीखंड याबद्दल सांगा.",
        "question_en": "Tell me about traditional Gujarati sweets Mohanthal and Shrikhand.",
        "question_roman_gu": "Gujarati mithai Mohanthal ane Shrikhand vishe janavo.",
        "answer_gu": "મોહનથાળ અને શ્રીખંડ ગુજરાતના તહેવારો અને શુભ પ્રસંગોની મુખ્ય મિઠાઈઓ છે: ૧) મોહનથાળ એ કરકરા ચણાના લોટ (બેસન)ને દૂધ-ઘીથી ધાબો દઈને, શુદ્ધ દેશી ઘીમાં ધીમા તાપે શેકી, ખાંડની ચાસણી, એલચી, જાયફળ, કેસર અને બદામ-પિસ્તા ઉમેરીને બનાવવામાં આવતી શાહી મિઠાઈ છે (ભગવાન શ્રીકૃષ્ણ-મોહનનો થાળ). ૨) શ્રીખંડ ચક્કા દહીં (Hung curd)માં ખાંડ, કેસર, એલચી અને ડ્રાયફ્રૂટ્સ મેળવીને બનાવવામાં આવતી ક્રીમી ઠંડી મિઠાઈ છે, જે પૂરી સાથે ખવાય છે.",
        "short_answer_gu": "ઘીમાં શેકેલા બેસન અને કેસર-એલચીમાંથી બનતો મોહનથાળ તથા મસ્કા દહીંમાંથી બનતો કેસર શ્રીખંડ.",
        "short_answer_en": "Mohanthal (rich roasted gram flour fudge infused with saffron and ghee) and Shrikhand (sweetened strained yogurt with cardamom) are classic Gujarati desserts.",
        "short_answer_hi": "मोहनथाल (बेसन और शुद्ध घी से बनी शाही मिठाई) और श्रीखंड (केसर-इलायची युक्त गाढ़ा दही) गुजरात के मुख्य मिष्ठान्न हैं।",
        "keywords": ["Mohanthal", "Shrikhand", "Gujarati Sweets", "Besan", "Ghee", "Saffron", "મોહનથાળ", "શ્રીખંડ", "મિઠાઈ"],
        "source": "Culinary Heritage of Gujarat",
        "source_type": "Festive Sweets",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_11",
        "category": "Gujarati Cuisine",
        "title": "સુરતી ઘારી (Surti Ghari - Chandi Padvo)",
        "title_en": "Surti Ghari",
        "district": "Surat",
        "question_gu": "સુરતી ઘારી અને ચાંદની પડવાના તહેવાર વિશે જણાવો.",
        "question_hi": "सूरटी घारी और चांदनी पड़वा के त्योहार के बारे में बताएं।",
        "question_mr": "सुरती घारी आणि चांदणी पाडव्याच्या सणाविषयी सांगा.",
        "question_en": "What is Surti Ghari and why is it eaten on Chandani Padva?",
        "question_roman_gu": "Surti Ghari ane Chandi Padvo vishe janavo.",
        "answer_gu": "સુરતી ઘારી સુરત શહેરની સૌથી પ્રસિદ્ધ અને ઘીથી લથપથ શાહી મિઠાઈ છે. તે માવો (ખોયા), પિસ્તા, બદામ, એલચી અને કેસરના પૂરણને મેંદાની પાતળી પૂરીમાં ભરીને શુદ્ધ ઘીમાં તળીને બનાવવામાં આવે છે, અને તેના પર ઘીનું જાડું પડ ચઢાવવામાં આવે છે. ૧૮૫૭ના સ્વાતંત્ર્ય સંગ્રામમાં તાત્યા તોપેના સૈનિકોને બળ આપવા માટે ઘારી બનાવવામાં આવી હોવાનું માનવામાં આવે છે. શરદ પૂર્ણિમા પછી આવતા 'ચાંદની પડવા'ના દિવસે સુરતીઓ રાત્રે અગાસી પર બેસીને ચાંદનીના પ્રકાશમાં સેંકડો ટન ઘારી અને ભૂસું આરોગે છે.",
        "short_answer_gu": "સુરતની માવો અને ડ્રાયફ્રુટ્સ ભરેલી ઘીની શાહી મિઠાઈ, જે ચાંદની પડવાના દિવસે ઉત્સાહથી ખવાય છે.",
        "short_answer_en": "Surti Ghari is a rich sweet from Surat made of mawa and dry fruits encased in dough and dipped in ghee, eaten on Chandani Padva festival.",
        "short_answer_hi": "सूरत की प्रसिद्ध घारी मावा और मेवों से बनी घी की मिठाई है जिसे चांदनी पड़वा के दिन खूब खाया जाता है।",
        "keywords": ["Surti Ghari", "Surat", "Chandi Padvo", "Mawa", "Ghee", "સુરતી ઘારી", "સુરત", "ચાંદની પડવો"],
        "source": "Surat Culinary Heritage",
        "source_type": "Regional Festive Sweet",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_12",
        "category": "Gujarati Cuisine",
        "title": "કાઠિયાવાડી રોટલો અને રીંગણાનો ઓળો (Kathiyawadi Rotlo & Ringna no Olo)",
        "title_en": "Rotlo and Olo",
        "district": "Saurashtra (Kathiyawad)",
        "question_gu": "કાઠિયાવાડી બાજરાનો રોટલો, રીંગણાનો ઓળો અને લસણની ચટણી વિશે જણાવો.",
        "question_hi": "काठियावाड़ी बाजरे का रोटला, बैंगन का भर्ता (ओलो) और लहसुन की चटनी के बारे में बताएं।",
        "question_mr": "काठियावाडी बाजरीचा रोटला आणि वांग्याचे भरीत (ओळो) याबद्दल सांगा.",
        "question_en": "Tell me about traditional Kathiyawadi Bajra Rotlo, Ringna no Olo, and Garlic Chutney.",
        "question_roman_gu": "Kathiyawadi Bajra no Rotlo ane Ringna no Olo vishe janavo.",
        "answer_gu": "બાજરાનો રોટલો અને રીંગણાનો ઓળો એ સૌરાષ્ટ્ર (કાઠિયાવાડ)નું સૌથી લોકપ્રિય અને પૌષ્ટિક દેશી ભોજન છે. મોટા દેશી રીંગણને ચૂલાના અંગારા પર શેકીને, તેમાં લસણ, ડુંગળી, ટામેટાં, લીલાં મરચાં અને મસાલા સાથે તેલમાં સાંતળીને સ્વાદિષ્ટ 'ઓળો' બનાવાય છે. તેની સાથે માટીની તાવડી પર હાથેથી ટીપીને બનાવેલો ગરમાગરમ બાજરાનો રોટલો (જેના પર દેશી માખણ કે ઘી ચોપડાયેલું હોય), તીખી લસણની ચટણી, ગોળ અને ઠંડી છાશ પીરસવામાં આવે છે.",
        "short_answer_gu": "કાઠિયાવાડનું પૌષ્ટિક દેશી ભોજન: અંગારા પર શેકેલા રીંગણનો ઓળો, ગરમ બાજરાનો રોટલો, માખણ અને લસણની ચટણી.",
        "short_answer_en": "Kathiyawadi Bajra Rotlo (hand-patted pearl millet bread) with Ringna no Olo (smoked roasted eggplant mash), white butter, and garlic chutney.",
        "short_answer_hi": "सौराष्ट्र का पारंपरिक भोजन: अंगारों पर भुने बैंगन का भर्ता (ओलो), बाजरे का रोटला, मक्खन और तीखी लहसुन चटनी।",
        "keywords": ["Bajra Rotlo", "Ringna no Olo", "Kathiyawadi", "Saurashtra", "Garlic Chutney", "White Butter", "રોટલો", "રીંગણાનો ઓળો", "કાઠિયાવાડી", "માખણ"],
        "source": "Saurashtra Folk Cuisine Heritage",
        "source_type": "Rustic Traditional Cuisine",
        "source_url": "https://www.gujarattourism.com"
    },

    # =========================================================================
    # ADDITIONAL FOLK ARTS, DANCE & THEATRE (73-82)
    # =========================================================================
    {
        "id": "folk_01",
        "category": "Folk Culture",
        "title": "ભવાઈ લોકનાટ્ય (Bhavai Folk Theatre - Asait Thakar)",
        "title_en": "Bhavai Folk Theatre",
        "district": "North Gujarat / All Gujarat",
        "question_gu": "ગુજરાતના પરંપરાગત લોકનાટ્ય 'ભવાઈ' અને અસાઈત ઠાકર વિશે જણાવો.",
        "question_hi": "गुजरात के पारंपरिक लोकनाट्य 'भवई' और असाइत ठाकर के बारे में बताएं।",
        "question_mr": "गुजरातचे पारंपरिक लोकनाट्य 'भवई' याविषयी माहिती द्या.",
        "question_en": "Tell me about Bhavai, the traditional folk theatre of Gujarat founded by Asait Thakar.",
        "question_roman_gu": "Gujarat na loknatya Bhavai ane Asait Thakar vishe janavo.",
        "answer_gu": "ભવાઈ એ ૧૪મી સદીથી ચાલી આવતી ગુજરાતની પ્રાચીન અને લોકપ્રિય લોકનાટ્ય પરંપરા છે. તેના જનક ઊંઝાના અસાઈત ઠાકર હતા, જેમણે ૩૬૦ જેટલા 'વેશ' (નાટ્યરૂપો) લખ્યા હતા. ભવાઈમાં 'રંગલો અને રંગલી'ના પાત્રો દ્વારા સામાજિક કુરિવાજો પર હાસ્ય અને કટાક્ષથી લોકજાગૃતિ લાવવામાં આવે છે. ખુલ્લા મેદાન કે ચાચર ચોકમાં ભૂંગળ, પખવાજ અને ઝાંઝના સંગીત સાથે ભવાઈ ભજવાય છે. સૌથી જૂનો વેશ 'રામદેવપીરનો વેશ' અને લોકપ્રિય વેશ 'જસમા ઓડણનો વેશ' છે.",
        "short_answer_gu": "૧૪મી સદીમાં અસાઈત ઠાકરે શરૂ કરેલું ગુજરાતનું પરંપરાગત લોકનાટ્ય, જેમાં રંગલો-રંગલીના કટાક્ષ અને ભૂંગળ વાજિંત્ર મુખ્ય છે.",
        "short_answer_en": "Bhavai is a 14th-century vibrant folk theatre of Gujarat initiated by Asait Thakar, famous for the humorous clown duo Ranglo-Rangli and the Bhungal horn.",
        "short_answer_hi": "१४वीं सदी में असाइत ठाकर द्वारा शुरू की गई भवई गुजरात की पारंपरिक लोक नाट्य शैली है जिसमें रंगलो-रंगली प्रमुख पात्र होते हैं।",
        "keywords": ["Bhavai", "Asait Thakar", "Ranglo Rangli", "Folk Theatre", "Bhungal", "ભવાઈ", "અસાઈત ઠાકર", "રંગલો", "ભૂંગળ"],
        "source": "Sangeet Natak Akademi / Gujarat Sahitya Academy",
        "source_type": "Traditional Performing Art",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "folk_02",
        "category": "Folk Culture",
        "title": "દાયરો અને લોકવાર્તા પરંપરા (Dayro Folk Gathering & Storytelling)",
        "title_en": "Dayro Folk Tradition",
        "district": "Saurashtra / Kutch",
        "question_gu": "સૌરાષ્ટ્રનો 'દાયરો' શું છે અને તેમાં શું રજૂ થાય છે?",
        "question_hi": "सौराष्ट्र का 'डायरा' क्या है और इसमें क्या प्रस्तुत किया जाता है?",
        "question_mr": "सौराष्ट्रचा 'डायरो' म्हणजे काय?",
        "question_en": "What is a 'Dayro' in Gujarati culture and how is folk storytelling performed?",
        "question_roman_gu": "Saurashtra no Dayro shu chhe ane tema shu raju thay chhe?",
        "answer_gu": "દાયરો (Dayro) એ સૌરાષ્ટ્ર અને કચ્છની અત્યંત જીવંત, રાત્રિભર ચાલતી સાહિત્યિક, આધ્યાત્મિક અને સંગીતમય લોકસભા છે. 'દાયરો' શબ્દ સામુદાયિક બેઠકનું પ્રતીક છે. તેમાં લોકગાયકો અને સાહિત્યકારો (જેમ કે લોકસાહિત્યકાર હેમુ ગઢવી, કાગબાપુ, પદ્મશ્રી ભીખુદાન ગઢવી, માયાભાઈ આહીર) દ્વારા હાર્મોનિયમ, તબલા અને મંજીરાના સથવારે સંતવાણી, ભજનો, શૌર્યગાથાઓ, બહારવટિયાની વાર્તાઓ અને હાસ્ય-રસથી ભરપૂર કથાઓ રજૂ કરવામાં આવે છે.",
        "short_answer_gu": "સૌરાષ્ટ્રની પરંપરાગત રાત્રિ લોકસભા જ્યાં ભજન, સંતવાણી, શૌર્યગાથાઓ અને લોકસાહિત્યની રજૂઆત થાય છે.",
        "short_answer_en": "Dayro is a traditional nocturnal Gujarati community gathering featuring folk music, devotional bhajans, historic hero tales, and cultural humor.",
        "short_answer_hi": "डायरा सौराष्ट्र और कच्छ की रात्रिकालीन पारंपरिक लोक सभा है जहाँ संतवाणी, लोकगीत और वीरता की कहानियां सुनाई जाती हैं।",
        "keywords": ["Dayro", "Santvani", "Lok Sahitya", "Saurashtra", "Bhikhudan Gadhvi", "દાયરો", "સંતવાણી", "લોકસાહિત્ય", "સૌરાષ્ટ્ર"],
        "source": "Gujarat Folk Literature Academy",
        "source_type": "Folk Cultural Tradition",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "folk_03",
        "category": "Folk Culture",
        "title": "પીઠોરા ચિત્રકળા (Pithora Wall Paintings Rathwa Tribe)",
        "title_en": "Pithora Paintings",
        "district": "Chhota Udepur / Panchmahal",
        "question_gu": "રાઠવા આદિવાસીઓની પવિત્ર પીઠોરા ચિત્રકળા વિશે જણાવો.",
        "question_hi": "राठवा आदिवासियों की पवित्र पिथोरा चित्रकला के बारे में बताएं।",
        "question_mr": "राठवा आदिवासींच्या पिथोरा चित्रकलेविषयी सांगा.",
        "question_en": "Tell me about the sacred Pithora wall paintings of the Rathwa tribal community.",
        "question_roman_gu": "Rathwa adivasi ni Pithora chitrakala vishe janavo.",
        "answer_gu": "પીઠોરા ચિત્રકળા એ છોટા ઉદેપુર અને પંચમહાલ જિલ્લાના રાઠવા, ભીલ અને નાયકા આદિવાસી સમુદાયની અત્યંત પવિત્ર ધાર્મિક ભીંતચિત્ર કળા છે. આ ચિત્રો માત્ર કળા નથી પરંતુ બાધા કે મનોકામના પૂર્ણ થવા પર 'બાબા પીઠોરા' (કુળદેવતા)ના આશીર્વાદ મેળવવા માટે ઘરની દીવાલો પર દોરવામાં આવે છે. આ ચિત્રો દોરનાર વિશેષ કલાકારને 'લખારા' (Lakhara) કહેવાય છે. ચિત્રમાં સાત ઘોડા પર સવાર બાબા પીઠોરા, રાણી કાજલ કુઈ, પ્રકૃતિ, સૂર્ય, ચંદ્ર, પશુ-પંખીઓ અને આદિવાસી જીવનશૈલીનું જીવંત ચિત્રણ હોય છે.",
        "short_answer_gu": "છોટા ઉદેપુરના રાઠવા આદિવાસીઓની પવિત્ર ધાર્મિક ભીંતચિત્ર કળા, જેમાં ઘોડા અને પ્રકૃતિના દેવ પીઠોરાનું આલેખન થાય છે.",
        "short_answer_en": "Pithora painting is a sacred ritualistic mural art created by the Rathwa tribe of Chhota Udepur to honor their deity Baba Pithora.",
        "short_answer_hi": "छोटा उदेपुर के राठवा आदिवासियों द्वारा घर की दीवारों पर बनाई जाने वाली पवित्र पिथोरा चित्रकला घोड़ों और लोकदेवताओं के अंकन के लिए प्रसिद्ध है।",
        "keywords": ["Pithora Painting", "Rathwa", "Chhota Udepur", "Lakhara", "Baba Pithora", "Tribal Art", "પીઠોરા ચિત્રકળા", "રાઠવા", "છોટા ઉદેપુર", "લખારા"],
        "source": "Tribal Research and Training Institute, Gujarat / Crafts Council of India",
        "source_type": "Tribal Heritage Art",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "folk_04",
        "category": "Folk Culture",
        "title": "અજરખ બ્લોક પ્રિન્ટિંગ (Ajrakh Block Printing Dhamadka/Ajrakhpur)",
        "title_en": "Ajrakh Block Printing",
        "district": "Kutch",
        "question_gu": "કચ્છની અજરખ બ્લોક પ્રિન્ટિંગ કળા અને કુદરતી રંગો વિશે જણાવો.",
        "question_hi": "कच्छ की अजरक ब्लॉक प्रिंटिंग और प्राकृतिक रंगों के बारे में बताएं।",
        "question_mr": "कच्छच्या अजरक ब्लॉक प्रिंटिंगविषयी सांगा.",
        "question_en": "Tell me about Ajrakh block printing of Kutch and its natural dye process.",
        "question_roman_gu": "Kutch ni Ajrakh block printing kala vishe janavo.",
        "answer_gu": "અજરખ એ કચ્છના અજરખપુર અને ધામડકા ગામમાં ખત્રી સમુદાય દ્વારા સદીઓથી થતી પ્રાકૃતિક રંગોની બ્લોક પ્રિન્ટિંગ કળા છે. 'અજરખ' શબ્દ અરબી શબ્દ 'અઝરક' (નીલો/વાદળી રંગ) પરથી આવ્યો છે. આ કળામાં સાગના લાકડાના બ્લોક વડે ૧૬ જેટલા જટિલ તબક્કાઓમાં કાપડને ધોઈને, ગળી (Indigo), હરડે, દાડમની છાલ અને ફટકડી જેવા કુદરતી રંગોથી બંને બાજુ સરખી ભૌમિતિક ભાત છાપવામાં આવે છે. અજરખ શાલ, સ્ટોલ અને સાડીઓ વિશ્વભરમાં પ્રખ્યાત છે અને જીઆઈ ટેગ (GI Tag) પ્રાપ્ત છે.",
        "short_answer_gu": "કચ્છના અજરખપુરમાં કુદરતી ગળી અને વનસ્પતિ રંગોથી લાકડાના બ્લોક વડે થતી સદીઓ જૂની જીઆઈ ટેગ ધરાવતી છાપકામ કળા.",
        "short_answer_en": "Ajrakh is a traditional 16-step natural-dye hand-block printing textile craft from Ajrakhpur, Kutch, protected with a GI tag.",
        "short_answer_hi": "कच्छ के अजरखपुर में प्राकृतिक नील और वानस्पतिक रंगों से लकड़ी के ठप्पों द्वारा की जाने वाली अजरक ब्लॉक प्रिंटिंग विश्वप्रसिद्ध है।",
        "keywords": ["Ajrakh", "Block Printing", "Kutch", "Ajrakhpur", "Natural Dye", "GI Tag", "અજરખ", "કચ્છ", "અજરખપુર", "બ્લોક પ્રિન્ટ"],
        "source": "Geographical Indications Registry / Gujarat Tourism",
        "source_type": "GI Tagged Craft",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "folk_05",
        "category": "Folk Culture",
        "title": "સુરતનું ઝરીકામ (Surat Zari Craft - Gold & Silver Embroidery)",
        "title_en": "Surat Zari Craft",
        "district": "Surat",
        "question_gu": "સુરતના ઐતિહાસિક ઝરીકામ અને તેના પ્રકારો વિશે જણાવો.",
        "question_hi": "सूरत के ऐतिहासिक जरी काम और इसके प्रकारों के बारे में बताएं।",
        "question_mr": "सुरतच्या जरीकामाविषयी माहिती द्या.",
        "question_en": "Tell me about the historic Surat Zari embroidery craft.",
        "question_roman_gu": "Surat na Zari kaam vishe janavo.",
        "answer_gu": "સુરતનું ઝરીકામ મુઘલ કાળથી (૧૬મી સદીથી) ભારત અને વિશ્વમાં અગ્રણી સ્થાન ધરાવે છે. સોના અને ચાંદીના અતિ સૂક્ષ્મ તારને રેશમ કે સુતરાઉ દોરા સાથે વણીને ચમકદાર ઝરી બનાવવામાં આવે છે. તેના મુખ્ય બે પ્રકાર છે: 'રીયલ ઝરી' (શુદ્ધ સોના-ચાંદીમાંથી) અને 'ઇમિટેશન ઝરી' (કોપર અને ઇલેક્ટ્રોપ્લેટિંગથી). સુરતની ઝરીનો ઉપયોગ બનારસી સાડીઓ, કાંજીવરમ સાડીઓ, પાનેતર, વરરાજાના સાફા અને શાહી પોશાકોમાં સદીઓથી થાય છે. સુરત ઝરી ક્રાફ્ટને ભારત સરકાર દ્વારા જીઆઈ ટેગ (GI Tag) મળેલો છે.",
        "short_answer_gu": "મુઘલ કાળથી સુરતમાં સોના-ચાંદીના તારમાંથી બનતું ઝરીકામ, જે સાડીઓ અને શાહી પોશાકો માટે જીઆઈ ટેગ ધરાવે છે.",
        "short_answer_en": "Surat Zari Craft is a Mughal-era heritage craft of drawing fine gold and silver threads for textiles, holding a registered GI tag.",
        "short_answer_hi": "सूरत का जरी उद्योग १६वीं सदी से प्रसिद्ध है जहाँ सोने-चांदी के तारों से साड़ियों और परिधानों के लिए जरी बनाई जाती है।",
        "keywords": ["Surat Zari", "Zari Craft", "Gold Silver Thread", "Surat", "GI Tag", "સુરત ઝરી", "ઝરીકામ", "સોના ચાંદી તાર"],
        "source": "Geographical Indications Registry",
        "source_type": "GI Tagged Craft",
        "source_url": "https://www.gujarattourism.com"
    },

    # =========================================================================
    # ADDITIONAL WILDLIFE & RAMSAR WETLANDS (83-92)
    # =========================================================================
    {
        "id": "wild_06",
        "category": "Wildlife",
        "title": "થોળ તળાવ પક્ષી અભયારણ્ય (Thol Lake Bird Sanctuary - Ramsar Site)",
        "title_en": "Thol Lake Bird Sanctuary",
        "district": "Mehsana / Ahmedabad",
        "question_gu": "થોળ પક્ષી અભયારણ્ય અને રામસર સાઇટ વિશે જણાવો.",
        "question_hi": "थोल पक्षी अभयारण्य और रामसर स्थल के बारे में बताएं।",
        "question_mr": "थोल तलाव पक्षी अभयारण्याविषयी सांगा.",
        "question_en": "Tell me about Thol Lake Bird Sanctuary and its Ramsar designation.",
        "question_roman_gu": "Thol Lake Bird Sanctuary Ramsar site vishe janavo.",
        "answer_gu": "થોળ તળાવ પક્ષી અભયારણ્ય ઉત્તર ગુજરાતના મહેસાણા જિલ્લામાં (અમદાવાદથી માત્ર ૩૦ કિમી) આવેલું ૭ ચોરસ કિમીનું છીછરું જળાશય છે. વર્ષ ૨૦૨૧માં તેને આંતરરાષ્ટ્રીય મહત્વ ધરાવતી 'રામસર સાઇટ' (Ramsar Wetland Site) જાહેર કરવામાં આવી. શિયાળામાં અહીં ૧૫૦થી વધુ પ્રજાતિઓના હજારો યાયાવર પક્ષીઓ આવે છે. આ અભયારણ્ય ખાસ કરીને દુર્લભ સારસ ક્રેન (Sarus Crane - વિશ્વનું સૌથી ઊંચું ઊડતું પક્ષી), ગ્રેટ વ્હાઇટ પેલિકન, ફ્લેમિંગો અને બતકની વિવિધ પ્રજાતિઓ માટે પ્રખ્યાત છે.",
        "short_answer_gu": "અમદાવાદ પાસે આવેલી આંતરરાષ્ટ્રીય રામસર સાઇટ, જે સારસ ક્રેન અને શિયાળુ યાયાવર પક્ષીઓ માટે જાણીતું છે.",
        "short_answer_en": "Thol Lake in Mehsana is a Ramsar wetland bird sanctuary near Ahmedabad hosting over 150 bird species including the majestic Sarus Crane.",
        "short_answer_hi": "अहमदाबाद के पास स्थित थोल झील एक अंतरराष्ट्रीय रामसर पक्षी अभयारण्य है जो सारस क्रेन और प्रवासी पक्षियों के लिए प्रसिद्ध है।",
        "keywords": ["Thol Lake", "Ramsar Site", "Bird Sanctuary", "Sarus Crane", "Mehsana", "Ahmedabad", "થોળ તળાવ", "રામસર સાઇટ", "સારસ"],
        "source": "Ramsar Convention / Gujarat Forest Department",
        "source_type": "Ramsar Wetland Site",
        "source_url": "https://rsis.ramsar.org"
    },
    {
        "id": "wild_07",
        "category": "Wildlife",
        "title": "ખીજડીયા પક્ષી અભયારણ્ય (Khijadiya Bird Sanctuary - Ramsar Site)",
        "title_en": "Khijadiya Bird Sanctuary",
        "district": "Jamnagar",
        "question_gu": "જામનગરના ખીજડીયા પક્ષી અભયારણ્યની વિશેષતા શું છે?",
        "question_hi": "जामनगर के खीजड़िया पक्षी अभयारण्य की क्या विशेषता है?",
        "question_mr": "जामनगरच्या खिजडिया पक्षी अभयारण्याविषयी सांगा.",
        "question_en": "What is the unique ecosystem of Khijadiya Bird Sanctuary in Jamnagar?",
        "question_roman_gu": "Jamnagar na Khijadiya pakshi abhayaranya ni visheshata shu chhe?",
        "answer_gu": "ખીજડીયા પક્ષી અભયારણ્ય જામનગર પાસે કચ્છના અખાતના કિનારે આવેલું અનોખું પક્ષીતીર્થ છે, જેને ૨૦૨૨માં 'રામસર વેટલેન્ડ સાઇટ' જાહેર કરાયું હતું. તેની સૌથી મોટી વિશેષતા એ છે કે અહીં એક બાજુ મીઠા પાણીનું તળાવ અને બીજી બાજુ દરિયાનું ખારું પાણી આવેલું છે. આ અનોખી ઇકોસિસ્ટમને કારણે અહીં ૩૦૦થી વધુ પ્રજાતિઓનાં જળચર અને દરિયાઈ પક્ષીઓ જોવા મળે છે, જેમાં કાળી ડોકવાળી ઢોંક (Black-necked Stork), ગ્રેટ ક્રેસ્ટેડ ગ્રીબ, પેલિકન અને સુરખાબ પ્રમુખ છે.",
        "short_answer_gu": "જામનગરમાં આવેલી રામસર સાઇટ, જ્યાં મીઠા અને ખારા પાણીની અનોખી ઇકોસિસ્ટમમાં ૩૦૦થી વધુ પક્ષી પ્રજાતિઓ વસે છે.",
        "short_answer_en": "Khijadiya Bird Sanctuary near Jamnagar is a Ramsar site featuring a unique combination of fresh water and marine coastal habitats.",
        "short_answer_hi": "जामनगर का खीजड़िया अभयारण्य मीठे और खारे पानी के अनूठे संगम वाला रामसर स्थल है जहाँ ३०० से अधिक पक्षी प्रजातियां पाई जाती हैं।",
        "keywords": ["Khijadiya", "Bird Sanctuary", "Jamnagar", "Ramsar Site", "Freshwater and Marine", "ખીજડીયા", "પક્ષી અભયારણ્ય", "જામનગર"],
        "source": "Ramsar Convention / Gujarat Forest Department",
        "source_type": "Ramsar Wetland Site",
        "source_url": "https://rsis.ramsar.org"
    },
    {
        "id": "wild_08",
        "category": "Wildlife",
        "title": "વાંસદા રાષ્ટ્રીય ઉદ્યાન (Vansda National Park)",
        "title_en": "Vansda National Park",
        "district": "Navsari",
        "question_gu": "વાંસદા રાષ્ટ્રીય ઉદ્યાન અને ડાંગના ગાઢ જંગલો વિશે જણાવો.",
        "question_hi": "वांसदा राष्ट्रीय उद्यान और डांग के घने जंगलों के बारे में बताएं।",
        "question_mr": "वांसदा राष्ट्रीय उद्यानाविषयी माहिती द्या.",
        "question_en": "Tell me about Vansda National Park in Navsari.",
        "question_roman_gu": "Vansda National Park Navsari vishe janavo.",
        "answer_gu": "વાંસદા રાષ્ટ્રીય ઉદ્યાન દક્ષિણ ગુજરાતના નવસારી જિલ્લામાં અંબિકા નદીના કિનારે આવેલું ૨૪ ચોરસ કિમીનું અત્યંત ગાઢ ભેજવાળું પાનખર જંગલ છે, જે ૧૯૭૯માં રાષ્ટ્રીય ઉદ્યાન બન્યું હતું. આ જંગલ એટલું ગાઢ છે કે દિવસના સમયે પણ સૂર્યપ્રકાશ જમીન સુધી પહોંચવો મુશ્કેલ બને છે. અહીં દીપડા, ઝરખ, સાબર, ચોસિંગા, ઉડતી ખિસકોલી (Flying Squirrel), અજગર અને ૪૪૦થી વધુ પ્રજાતિઓની વનસ્પતિઓ અને ઔષધિઓ જોવા મળે છે.",
        "short_answer_gu": "નવસારીમાં અંબિકા નદી તટે આવેલું અતિ ગાઢ પાનખર રાષ્ટ્રીય ઉદ્યાન, જે ઉડતી ખિસકોલી અને દીપડા માટે જાણીતું છે.",
        "short_answer_en": "Vansda National Park in Navsari is a dense, lush deciduous forest sanctuary famous for leopards, flying squirrels, and rich flora.",
        "short_answer_hi": "नवसारी जिले में स्थित वांसदा राष्ट्रीय उद्यान अपने घने जंगलों, तेंदुओं और उड़ने वाली गिलहरियों के लिए जाना जाता है।",
        "keywords": ["Vansda National Park", "Navsari", "Ambika River", "Flying Squirrel", "Leopard", "વાંસદા", "રાષ્ટ્રીય ઉદ્યાન", "નવસારી"],
        "source": "Gujarat Forest Department",
        "source_type": "National Park",
        "source_url": "https://forests.gujarat.gov.in"
    },
    {
        "id": "wild_09",
        "category": "Wildlife",
        "title": "રતનમહાલ રીંછ અભયારણ્ય (Ratanmahal Sloth Bear Sanctuary)",
        "title_en": "Ratanmahal Sloth Bear Sanctuary",
        "district": "Dahod",
        "question_gu": "દાહોદના રતનમહાલ સ્લોથ રીંછ અભયારણ્ય વિશે જણાવો.",
        "question_hi": "दाहोद के रतनमहाल सुस्त भालू (स्लॉथ बेयर) अभयारण्य के बारे में बताएं।",
        "question_mr": "रतनमहाल अस्वल अभयारण्याविषयी सांगा.",
        "question_en": "Tell me about Ratanmahal Sloth Bear Sanctuary in Dahod.",
        "question_roman_gu": "Ratanmahal Sloth Bear Sanctuary Dahod vishe janavo.",
        "answer_gu": "રતનમહાલ વન્યજીવ અભયારણ્ય ગુજરાતના દાહોદ જિલ્લાના લીમખેડા તાલુકામાં મધ્યપ્રદેશની સરહદ પર આવેલું ૫૫ ચોરસ કિમીનું પર્વતીય જંગલ છે. આ અભયારણ્ય ખાસ કરીને ભારતીય સ્લોથ રીંછ (Sloth Bear)ના સંરક્ષણ માટે ૧૯૮૨માં સ્થાપવામાં આવ્યું હતું. અહીં મહુડાના પુષ્કળ વૃક્ષો હોવાથી રીંછોને કુદરતી ખોરાક મળે છે. આ ઉપરાંત અહીંથી પાનમ નદીનું ઉદ્ગમ સ્થાન છે અને રમણીય ઝરણાં આવેલાં છે.",
        "short_answer_gu": "દાહોદમાં આવેલું સ્લોથ રીંછ (Sloth Bear)નું વિશેષ અભયારણ્ય, જ્યાં પાનમ નદીનું ઉદ્ગમ સ્થાન આવેલું છે.",
        "short_answer_en": "Ratanmahal Wildlife Sanctuary in Dahod district is dedicated to the conservation of Sloth Bears amidst scenic teak and mahua forests.",
        "short_answer_hi": "दाहोद में स्थित रतनमहाल अभयारण्य स्लॉथ भालू (रीछ) के संरक्षण के लिए प्रसिद्ध पहाड़ी वन क्षेत्र है।",
        "keywords": ["Ratanmahal", "Sloth Bear", "Dahod", "Panam River", "Mahuda", "રતનમહાલ", "રીંછ અભયારણ્ય", "દાહોદ"],
        "source": "Gujarat Forest Department",
        "source_type": "Wildlife Sanctuary",
        "source_url": "https://forests.gujarat.gov.in"
    },

    # =========================================================================
    # ADDITIONAL GEOGRAPHY, HILLS & WATERFALLS (93-100)
    # =========================================================================
    {
        "id": "geo_04",
        "category": "Geography",
        "title": "કાળો ડુંગર - કચ્છ (Kalo Dungar Black Hill - Highest Point of Kutch)",
        "title_en": "Kalo Dungar",
        "district": "Kutch",
        "question_gu": "કચ્છના કાળા ડુંગર અને દત્તાત્રેય મંદિર વિશે જણાવો.",
        "question_hi": "कच्छ के काले डूंगर (कालो डूंगर) और दत्तात्रेय मंदिर के बारे में बताएं।",
        "question_mr": "कच्छच्या काळा डोंगर (कालो डुंगर) याविषयी माहिती द्या.",
        "question_en": "Tell me about Kalo Dungar (Black Hill), the highest point in Kutch.",
        "question_roman_gu": "Kutch na Kalo Dungar ane Dattatreya mandir vishe janavo.",
        "answer_gu": "કાળો ડુંગર (Black Hill) કચ્છ જિલ્લાના ખાવડા નજીક આવેલો ૪૬૨ મીટર (૧૫૧૬ ફૂટ) ઊંચો કચ્છનો સર્વોચ્ચ પહાડ છે. આ શિખર પરથી કચ્છના સફેદ રણ અને ભારત-પાકિસ્તાન આંતરરાષ્ટ્રીય સરહદનો મનોહર વિહંગમ નજારો જોવા મળે છે. પહાડની ટોચ પર ૪૦૦ વર્ષ જૂનું ભગવાન દત્તાત્રેયનું ઐતિહાસિક મંદિર આવેલું છે, જ્યાં સાંજની આરતી પછી જંગલી શિયાળો (Jackals)ને પ્રસાદ આપવાની અનોખી પ્રાચીન પરંપરા આજે પણ જીવંત છે. અહીં મેગ્નેટિક હિલ (ગુરુત્વાકર્ષણ વિરોધી ઢોળાવ)નો ભ્રમ પણ અનુભવાય છે.",
        "short_answer_gu": "કચ્છનો સૌથી ઊંચો પહાડ (૪૬૨ મીટર), જ્યાં દત્તાત્રેય મંદિર અને શિયાળોને પ્રસાદ આપવાની પરંપરા છે.",
        "short_answer_en": "Kalo Dungar is the highest peak in Kutch (462m), offering panoramic views of the Great Rann and hosting the 400-year-old Dattatreya temple.",
        "short_answer_hi": "कालो डूंगर कच्छ का सबसे ऊंचा शिखर (४६२ मी) है जहाँ से सफेद रण का विहंगम दृश्य और सियार को प्रसाद देने की परंपरा प्रसिद्ध है।",
        "keywords": ["Kalo Dungar", "Black Hill", "Kutch", "Dattatreya Temple", "Jackals", "Magnetic Hill", "કાળો ડુંગર", "કચ્છ", "દત્તાત્રેય"],
        "source": "Gujarat Tourism",
        "source_type": "Geographical Landmark",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "geo_05",
        "category": "Geography",
        "title": "ગીરા ધોધ - ડાંગ (Gira Waterfalls Waghai Dang)",
        "title_en": "Gira Waterfalls",
        "district": "Dang",
        "question_gu": "ડાંગના ગીરા ધોધ વિશે માહિતી આપો.",
        "question_hi": "डांग के गीरा जलप्रपात के बारे में बताएं।",
        "question_mr": "डांग येथील गिरा धबधब्याविषयी सांगा.",
        "question_en": "Give information about Gira Waterfalls in Waghai, Dang.",
        "question_roman_gu": "Dang na Gira Dhodh vishe mahiti aapo.",
        "answer_gu": "ગીરા ધોધ દક્ષિણ ગુજરાતના ડાંગ જિલ્લાના વઘઈ પાસે અંબિકા નદી પર આવેલો આશરે ૩૦ મીટર (૧૦૦ ફૂટ) ઊંચો ભવ્ય કુદરતી ધોધ છે. ચોમાસાની ઋતુમાં જ્યારે અંબિકા નદી બે કાંઠે વહે છે ત્યારે ગીરા ધોધનું રૌદ્ર અને રમણીય સ્વરૂપ લાખો પ્રવાસીઓને આકર્ષે છે. ધોધની આસપાસ ડાંગના ગાઢ સાગ અને વાંસના જંગલો તથા વઘઈ બોટાનિકલ ગાર્ડન આવેલાં છે.",
        "short_answer_gu": "ડાંગ જિલ્લાના વઘઈ પાસે અંબિકા નદી પર ૧૦૦ ફૂટની ઊંચાઈએથી પડતો ગુજરાતનો સૌથી સુંદર કુદરતી જળધોધ.",
        "short_answer_en": "Gira Falls is a breathtaking 100-foot waterfall on the Ambika River near Waghai in the forested Dang district.",
        "short_answer_hi": "डांग जिले में वाघई के पास अंबिका नदी पर स्थित १०० फीट ऊंचा गीरा जलप्रपात मानसून में बेहद मनोरम दृश्य प्रस्तुत करता है।",
        "keywords": ["Gira Falls", "Waterfall", "Dang", "Waghai", "Ambika River", "Saputara", "ગીરા ધોધ", "ડાંગ", "વઘઈ", "અંબિકા નદી"],
        "source": "Gujarat Tourism",
        "source_type": "Natural Waterfall",
        "source_url": "https://www.gujarattourism.com"
    },

    # =========================================================================
    # ADDITIONAL HISTORICAL EVENTS & MOVEMENTS (101-105)
    # =========================================================================
    {
        "id": "event_04",
        "category": "Historical Events",
        "title": "ખેડા સત્યાગ્રહ ૧૯૧૮ (Kheda Satyagraha 1918 - First Non-Cooperation)",
        "title_en": "Kheda Satyagraha",
        "district": "Kheda",
        "question_gu": "૧૯૧૮ના ખેડા સત્યાગ્રહનો ઇતિહાસ અને પરિણામ જણાવો.",
        "question_hi": "१९१८ के खेड़ा सत्याग्रह का इतिहास और परिणाम बताएं।",
        "question_mr": "१९१८ च्या खेडा सत्याग्रहाविषयी सांगा.",
        "question_en": "Explain the 1918 Kheda Satyagraha led by Mahatma Gandhi and Sardar Patel.",
        "question_roman_gu": "1918 Kheda Satyagraha no itihas ane parinam janavo.",
        "answer_gu": "ખેડા સત્યાગ્રહ ઈ.સ. ૧૯૧૮માં ગુજરાતના ખેડા જિલ્લામાં પાક નિષ્ફળ જવા છતાં બ્રિટિશ સરકાર દ્વારા ખેડૂતો પાસેથી બળજબરીપૂર્વક જમીન મહેસૂલ વસૂલવા સામે થયો હતો. મહાત્મા ગાંધી અને સરદાર વલ્લભભાઈ પટેલે ખેડૂતોને સંગઠિત કરી કર ન ભરવાની અહિંસક લડત ચલાવી. ખેડૂતોની અતૂટ એકતા આગળ અંગ્રેજ સરકારે ઝૂકીને ગરીબ ખેડૂતોનું મહેસૂલ માફ કરવું પડ્યું હતું. આ આંદોલનથી સરદાર પટેલ ગાંધીજીના મુખ્ય સાથીદાર તરીકે ઉભરી આવ્યા.",
        "short_answer_gu": "૧૯૧૮માં ખેડાના ખેડૂતોના સમર્થનમાં ગાંધીજી અને સરદાર પટેલની આગેવાનીમાં થયેલો સફળ મહેસૂલ માફી સત્યાગ્રહ.",
        "short_answer_en": "The 1918 Kheda Satyagraha was a major peasant non-tax movement in Gujarat led by Gandhi and Patel resulting in revenue suspension.",
        "short_answer_hi": "१९१८ में अकाल के बावजूद कर वसूली के खिलाफ गांधीजी और सरदार पटेल के नेतृत्व में खेड़ा किसान सत्याग्रह सफल रहा।",
        "keywords": ["Kheda Satyagraha", "1918", "Mahatma Gandhi", "Sardar Patel", "Farmers", "ખેડા સત્યાગ્રહ", "ગાંધીજી", "સરદાર પટેલ"],
        "source": "National Gandhi Museum / National Archives",
        "source_type": "Historical Satyagraha",
        "source_url": "https://gandhiheritageportal.org"
    },
    {
        "id": "event_05",
        "category": "Historical Events",
        "title": "જૂનાગઢનું ભારત સંઘમાં વિલિનીકરણ ૧૯૪૭ (Integration of Junagadh into India 1947)",
        "title_en": "Integration of Junagadh",
        "district": "Junagadh",
        "question_gu": "જૂનાગઢનું ભારત સંઘમાં જોડાણ અને આરઝી હકૂમત વિશે જણાવો.",
        "question_hi": "जूनागढ़ का भारत संघ में विलय और आरज़ी हुकूमत के बारे में बताएं।",
        "question_mr": "जुनागढचे भारतात विलीनीकरण आणि आरझी हुकूमतविषयी सांगा.",
        "question_en": "Explain the 1947 integration of Junagadh state into the Indian Union and Aarzi Hukumat.",
        "question_roman_gu": "Junagadh nu Bharat sangh ma vilinikaran ane Aarzi Hukumat vishe janavo.",
        "answer_gu": "આઝાદી સમયે જૂનાગઢના નવાબ મુહમ્મદ મહાબત ખાન ત્રીજાએ ૧૫ ઓગસ્ટ ૧૯૪૭ના રોજ જૂનાગઢનું પાકિસ્તાન સાથે જોડાણ જાહેર કર્યું, જ્યારે જૂનાગઢની ૮૦%થી વધુ જનતા ભારત સાથે જોડાવા માંગતી હતી. આ સામે મુંબઈમાં શામળદાસ ગાંધીની આગેવાનીમાં 'આરઝી હકૂમત' (કામચલાઉ સરકાર)ની રચના થઈ. સરદાર વલ્લભભાઈ પટેલના દ્રઢ નેતૃત્વ અને લોકજુવાળ આગળ નવાબ કરાચી ભાગી ગયા. ૯ નવેમ્બર ૧૯૪૭ના રોજ ભારત સરકારે જૂનાગઢનો કબજો લીધો અને લોકમત (Plebiscite)માં ૯૯% થી વધુ લોકોએ ભારત સાથે જોડાવાની તરફેણ કરી.",
        "short_answer_gu": "૧૯૪૭માં નવાબના પાકિસ્તાન જોડાણ સામે શામળદાસ ગાંધીની આરઝી હકૂમત અને સરદાર પટેલના નેતૃત્વથી જૂનાગઢનું ભારતમાં વિલિનીકરણ થયું.",
        "short_answer_en": "In 1947, Junagadh was unified into India through Sardar Patel's decisive leadership and the Aarzi Hukumat movement led by Samaldas Gandhi.",
        "short_answer_hi": "१९४७ में जूनागढ़ के नवाब के पाकिस्तान में विलय के फैसले के खिलाफ सरदार पटेल और आरज़ी हुकूमत के संघर्ष से जूनागढ़ भारत का अभिन्न अंग बना।",
        "keywords": ["Junagadh Integration", "Aarzi Hukumat", "Samaldas Gandhi", "Sardar Patel", "Nawab Mahabat Khan", "જૂનાગઢ વિલિનીકરણ", "આરઝી હકૂમત", "શામળદાસ ગાંધી"],
        "source": "Ministry of Home Affairs / National Archives",
        "source_type": "Historical Milestone",
        "source_url": "https://www.gujarattourism.com"
    }
]

def build_all():
    all_records = BASE_RECORDS + ADDITIONAL_RECORDS
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    
    data_path = DATA_DIR / "knowledge_base.json"
    root_path = ROOT_DIR / "knowledge_base.json"
    
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(all_records, f, ensure_ascii=False, indent=2)
        
    with open(root_path, "w", encoding="utf-8") as f:
        json.dump(all_records, f, ensure_ascii=False, indent=2)
        
    print(f"Total Knowledge Records generated: {len(all_records)}")
    print(f"Main output: {data_path}")

if __name__ == "__main__":
    build_all()
