"""Comprehensive dataset generator for GUJJUVAANI with 110 authentic records across 13 categories.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
ROOT_DIR = Path(__file__).resolve().parent.parent

# Import the existing base records
from src.build_kb import KNOWLEDGE_RECORDS as R1
from src.build_full_kb import ADDITIONAL_RECORDS as R2

# Part 3: Records 49 to 110
PART3_RECORDS = [
    # -------------------------------------------------------------------------
    # HISTORICAL MONUMENTS & PALACES (49-58)
    # -------------------------------------------------------------------------
    {
        "id": "hist_19",
        "category": "Historical Places",
        "title": "દીવ કિલ્લો અને સેન્ટ પોલ ચર્ચ (Diu Fort & St. Paul's Church)",
        "title_en": "Diu Fort",
        "district": "Diu Coast",
        "question_gu": "દીવના ઐતિહાસિક પોર્ટુગીઝ કિલ્લા અને સેન્ટ પોલ ચર્ચ વિશે જણાવો.",
        "question_hi": "दीव के ऐतिहासिक पुर्तगाली किले और सेंट पॉल चर्च के बारे में बताएं।",
        "question_mr": "दीवचा किल्ला आणि सेंट पॉल चर्च याविषयी सांगा.",
        "question_en": "Tell me about the historic Portuguese Fort and St. Paul's Church in Diu.",
        "question_roman_gu": "Diu killa ane St Paul Church vishe janavo.",
        "answer_gu": "દીવ કિલ્લો ગુજરાતના દરિયાકાંઠે અરબી સમુદ્રમાં સ્થિત ૧૬મી સદીનો ભવ્ય પોર્ટુગીઝ દરિયાઈ કિલ્લો છે. તેનું નિર્માણ ઈ.સ. ૧૫૩૫માં ગુજરાતના સુલતાન બહાદુર શાહ અને પોર્ટુગીઝો વચ્ચેના સંરક્ષણ કરાર બાદ શરૂ થયું હતું. કિલ્લો ત્રણ બાજુથી સમુદ્રથી ઘેરાયેલો છે અને તેના પર ઐતિહાસિક તોપો, દીવાદાંડી (Lighthouse) અને જેલ આવેલી છે. નજીકમાં ૧૬૧૦માં બનેલું સેન્ટ પોલ ચર્ચ બરોક સ્થાપત્ય શૈલી (Baroque architecture) અને અદભુત લાકડાની કોતરણી માટે જાણીતું છે. નજીકમાં કુદરતી નાયડા ગુફાઓ (Naida Caves) પણ આવેલી છે.",
        "short_answer_gu": "અરબી સમુદ્રથી ઘેરાયેલો ૧૬મી સદીનો પોર્ટુગીઝ કિલ્લો, સેન્ટ પોલ ચર્ચ અને અદભુત નાયડા ગુફાઓ.",
        "short_answer_en": "Diu Fort is a 16th-century sea-facing Portuguese fortress known for stone ramparts, historic cannons, and the nearby Baroque-style St. Paul's Church.",
        "short_answer_hi": "दीव का किला १६वीं सदी का ऐतिहासिक पुर्तगाली किला है जो तीन ओर से समुद्र से घिरा है और अपनी तोपों व सेंट पॉल चर्च के लिए प्रसिद्ध है।",
        "keywords": ["Diu Fort", "Portuguese", "St Paul Church", "Naida Caves", "Lighthouse", "દીવ કિલ્લો", "સેન્ટ પોલ ચર્ચ", "નાયડા ગુફાઓ"],
        "source": "Archaeological Survey of India / Gujarat Tourism",
        "source_type": "Coastal Fortress Heritage",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_20",
        "category": "Historical Places",
        "title": "અશોકનો શિલાલેખ - જૂનાગઢ (Ashoka Rock Edicts Junagadh)",
        "title_en": "Ashoka Rock Edict Junagadh",
        "district": "Junagadh",
        "question_gu": "જૂનાગઢમાં આવેલા સમ્રાટ અશોકના શિલાલેખ વિશે જણાવો.",
        "question_hi": "जूनागढ़ में सम्राट अशोक के शिलालेख के बारे में बताएं।",
        "question_mr": "जुनागढ येथील सम्राट अशोकाच्या शिलालेखाविषयी माहिती द्या.",
        "question_en": "Tell me about Emperor Ashoka's Rock Edict at the foothills of Girnar in Junagadh.",
        "question_roman_gu": "Junagadh na Ashoka shilalekh vishe janavo.",
        "answer_gu": "સમ્રાટ અશોકનો શિલાલેખ જૂનાગઢમાં ગિરનાર પર્વત તરફ જતા રસ્તા પર આવેલો ઈ.સ. પૂર્વે ૨૫૦ (૨૨૦૦ વર્ષથી વધુ પ્રાચીન) સમયનો ઐતિહાસિક શિલાલેખ છે. એક વિશાળ કાળા ગ્રેનાઇટ પથ્થર પર બ્રાહ્મી લિપિ અને પાલી/પ્રાકૃત ભાષામાં સમ્રાટ અશોકની ૧૪ ધર્માજ્ઞાઓ કોતરાયેલી છે, જેમાં અહિંસા, જીવદયા, પરોપકાર અને ધર્મવિજયનો સંદેશ છે. આ જ શિલા પર પાછળથી મહાક્ષત્રપ રુદ્રદામા (સંસ્કૃત ભાષાનો પ્રથમ લાંબો અભિલેખ - સુદર્શન તળાવ સમારકામ) અને ગુપ્ત સમ્રાટ સ્કંદગુપ્તના શિલાલેખો પણ અંકિત છે.",
        "short_answer_gu": "ગિરનાર તળેટીમાં બ્રાહ્મી લિપિમાં અશોકની ૧૪ ધર્માજ્ઞાઓ ધરાવતો ૨૨૦૦ વર્ષ જૂનો ઐતિહાસિક શિલાલેખ.",
        "short_answer_en": "Emperor Ashoka's Rock Edicts in Junagadh contain 14 moral edicts in Brahmi script dating back to 250 BCE on a single granite boulder.",
        "short_answer_hi": "जूनागढ़ में गिरनार की तलहटी में स्थित सम्राट अशोक का शिलालेख ब्राह्मी लिपि में २२०० वर्ष प्राचीन १४ धर्माज्ञाओं का दुर्लभ संग्रह है।",
        "keywords": ["Ashoka Edict", "Junagadh", "Brahmi Script", "Rudradaman", "Skandagupta", "Sudarshan Lake", "અશોક શિલાલેખ", "જૂનાગઢ", "બ્રાહ્મી લિપિ"],
        "source": "Archaeological Survey of India",
        "source_type": "ASI National Heritage Monument",
        "source_url": "https://asi.nic.in"
    },
    {
        "id": "hist_21",
        "category": "Historical Places",
        "title": "રુદ્ર મહાલય - સિદ્ધપુર (Rudra Mahalaya Temple Ruins Siddhpur)",
        "title_en": "Rudra Mahalaya",
        "district": "Patan (Siddhpur)",
        "question_gu": "સિદ્ધપુરના રુદ્ર મહાલય અને બિંદુ સરોવર વિશે જણાવો.",
        "question_hi": "सिद्धपुर के रुद्र महालय और बिंदु सरोवर के बारे में बताएं।",
        "question_mr": "सिद्धपूरच्या रुद्र महालय आणि बिंदू सरोवराविषयी सांगा.",
        "question_en": "Tell me about the ancient Rudra Mahalaya temple and Bindu Sarovar in Siddhpur.",
        "question_roman_gu": "Siddhpur na Rudra Mahalaya ane Bindu Sarovar vishe janavo.",
        "answer_gu": "રુદ્ર મહાલય પાટણ જિલ્લાના સિદ્ધપુરમાં સરસ્વતી નદીના કિનારે આવેલું ૧૨મી સદીનું ભવ્યાતિભવ્ય શિવમંદિર હતું. તેનું નિર્માણ સોલંકી વંશના સ્થાપક મૂળરાજ સોલંકીએ શરૂ કરાવ્યું હતું અને સિદ્ધરાજ જયસિંહે ઈ.સ. ૧૧૪૦માં પૂર્ણ કરાવ્યું હતું. આ મંદિર ત્રિમાળીય અને અગિયાર રુદ્રોને સમર્પિત હતું, જેમાં વિશાળ કલાત્મક સ્તંભો અને તોરણો હતાં. અલાઉદ્દીન ખીલજી અને અહમદ શાહના આક્રમણોમાં તે ખંડિત થયું છતાં તેના ઊભા તોરણો સોલંકી સ્થાપત્યની ભવ્યતા દર્શાવે છે. સિદ્ધપુરમાં બિંદુ સરોવર આવેલું છે જે સમગ્ર ભારતમાં 'માતૃ શ્રાદ્ધ' (માતૃ તર્પણ) માટે એકમાત્ર પવિત્ર તીર્થ ગણાય છે (જ્યાં ભગવાન પરશુરામે માતા રેણુકાનું શ્રાદ્ધ કર્યું હતું).",
        "short_answer_gu": "સિદ્ધપુરમાં સિદ્ધરાજ જયસિંહે બંધાવેલું ૧૨મી સદીનું ભવ્ય શિવમંદિર અને માતૃ શ્રાદ્ધ માટે પવિત્ર બિંદુ સરોવર.",
        "short_answer_en": "Rudra Mahalaya in Siddhpur is a grand 12th-century Solanki Shiva temple complex built by Siddhraj Jaisinh; Siddhpur is also holy for Bindu Sarovar Matru Shradh.",
        "short_answer_hi": "सिद्धपुर में सरस्वती नदी किनारे स्थित रुद्र महालय सोलंकी कालीन विशाल शिव मंदिर है; यहाँ बिंदु सरोवर मातृ श्राद्ध के लिए प्रसिद्ध है।",
        "keywords": ["Rudra Mahalaya", "Siddhpur", "Patan", "Siddhraj Jaisinh", "Bindu Sarovar", "Matru Shradh", "રુદ્ર મહાલય", "સિદ્ધપુર", "બિંદુ સરોવર"],
        "source": "Archaeological Survey of India / Gujarat Tourism",
        "source_type": "ASI Monument of National Importance",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_22",
        "category": "Historical Places",
        "title": "હઠીસિંહના દહેરાં - અમદાવાદ (Hutheesing Jain Temple Ahmedabad)",
        "title_en": "Hutheesing Jain Temple",
        "district": "Ahmedabad",
        "question_gu": "અમદાવાદના હઠીસિંહના જૈન મંદિરની સ્થાપત્ય કળા વિશે જણાવો.",
        "question_hi": "अहमदाबाद के हठीसिंह जैन मंदिर की शिल्पकला के बारे में बताएं।",
        "question_mr": "अहमदाबादच्या हठीसिंग जैन मंदिराविषयी सांगा.",
        "question_en": "Tell me about the marble architecture of Hutheesing Jain Temple in Ahmedabad.",
        "question_roman_gu": "Ahmedabad na Hatheesing na Dehra vishe janavo.",
        "answer_gu": "હઠીસિંહના દહેરાં અમદાવાદના દિલ્હી દરવાજા બહાર આવેલું શ્વેત આરસપહાણનું અતિ ભવ્ય અને કલાત્મક જૈન મંદિર છે. તેનું નિર્માણ ધનાઢ્ય જૈન વેપારી શેઠ હઠીસિંહ કેસરીસિંહ દ્વારા શરૂ કરાયું હતું અને તેમના અવસાન બાદ તેમના પત્ની શેઠાણી હરકુંવરબાઈએ ઈ.સ. ૧૮૪૮માં ૧૦ લાખ રૂપિયાના ખર્ચે પૂર્ણ કરાવ્યું હતું. પ્રેમચંદ સલાટ દ્વારા ડિઝાઇન કરાયેલું આ મંદિર ૧૫મા તીર્થંકર ભગવાન ધર્મનાથને સમર્પિત છે. તેમાં ૫૨ દેરીઓ (નાના મંદિરો), બે માળનું ગર્ભગૃહ, કોતરણીદાર સ્તંભો અને પશ્ચિમમાં ૭૮ ફૂટ ઊંચો કીર્તિસ્તંભ (માનસ્તંભ) આવેલાં છે.",
        "short_answer_gu": "અમદાવાદમાં ૧૮૪૮માં સફેદ આરસમાંથી બનેલું ભવ્ય ૫૨ દેરીઓવાળું જૈન મંદિર, જે ભગવાન ધર્મનાથને સમર્પિત છે.",
        "short_answer_en": "Built in 1848 by Sheth Hutheesing and Harkunwarbai, this white marble temple in Ahmedabad is dedicated to Lord Dharmanath and features 52 subsidiary shrines.",
        "short_answer_hi": "अहमदाबाद में १८४८ में सफेद संगमरमर से बना हठीसिंह जैन मंदिर अपनी ५२ देवरियों और नक्काशी के लिए प्रसिद्ध है।",
        "keywords": ["Hutheesing Temple", "Jain Temple", "Ahmedabad", "Harkunwarbai", "Dharmanath", "Marble", "હઠીસિંહના દહેરાં", "અમદાવાદ", "આરસ"],
        "source": "Hutheesing Temple Trust / Gujarat Tourism",
        "source_type": "Architectural Heritage",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_23",
        "category": "Historical Places",
        "title": "નવલખા મહેલ - ગોંડલ (Naulakha Palace Gondal)",
        "title_en": "Naulakha Palace Gondal",
        "district": "Rajkot (Gondal)",
        "question_gu": "ગોંડલના નવલખા પેલેસ અને મહારાજા ભગવતસિંહજી વિશે જણાવો.",
        "question_hi": "गोंडल के नवलखा पैलेस और महाराजा भगवतसिंह जी के बारे में बताएं।",
        "question_mr": "गोंडलच्या नवलखा पॅलेसविषयी सांगा.",
        "question_en": "Tell me about Naulakha Palace in Gondal and Maharaja Bhagvatsinhji.",
        "question_roman_gu": "Gondal na Naulakha Palace ane Bhagvatsinhji vishe janavo.",
        "answer_gu": "નવલખા પેલેસ ગોંડલમાં ગોંડલી નદીના કિનારે આવેલો ૧૭મી સદીનો (ઈ.સ. ૧૭૪૮) સૌથી જૂનો ભવ્ય મહેલ છે. તે સમયે તેના બાંધકામમાં ૯ લાખ રૂપિયાનો ખર્ચ થયો હોવાથી તેને 'નવલખા' કહેવામાં આવે છે. મહેલમાં અદભુત પથ્થરના ઝરૂખા, કોતરણીદાર થાંભલા, દરબાર હોલ અને પ્રાચીન ઘડિયાળો તથા શસ્ત્રોનો સંગ્રહ છે. ગોંડલના પ્રજાવત્સલ મહારાજા ભગવતસિંહજી (૧૮૬૫ - ૧૯૪૪)એ રાજ્યમાં ફરજિયાત કન્યા કેળવણી શરૂ કરી હતી અને ગુજરાતી ભાષાનો સુપ્રસિદ્ધ ૯ ભાગનો જ્ઞાનકોશ-શબ્દકોશ 'ભગવદ્ગોમંડલ' (Bhagavadgomandal) રચાવ્યો હતો.",
        "short_answer_gu": "ગોંડલમાં ગોંડલી નદી તટે આવેલો ૧૭૪૮નો ઐતિહાસિક મહેલ; ગોંડલના રાજા ભગવતસિંહજીએ 'ભગવદ્ગોમંડલ' શબ્દકોશ રચાવ્યો હતો.",
        "short_answer_en": "Naulakha Palace is a 1748 riverside palace in Gondal; its ruler Maharaja Bhagvatsinhji pioneered female education and created the 9-volume 'Bhagavadgomandal' encyclopedia.",
        "short_answer_hi": "गोंडल का १७४८ का नवलखा पैलेस अपनी वास्तुकला के लिए प्रसिद्ध है; यहाँ के महाराजा भगवतसिंह जी ने विशाल 'भगवद्गोमंडल' शब्दकोश बनवाया।",
        "keywords": ["Naulakha Palace", "Gondal", "Bhagvatsinhji", "Bhagavadgomandal", "Rajkot", "નવલખા પેલેસ", "ગોંડલ", "ભગવતસિંહજી", "ભગવદ્ગોમંડલ"],
        "source": "Gondal Royal Heritage / Gujarat Tourism",
        "source_type": "Heritage Palace",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_24",
        "category": "Historical Places",
        "title": "રણજીત વિલાસ પેલેસ - વાંકાનેર (Ranjit Vilas Palace Wankaner)",
        "title_en": "Ranjit Vilas Palace Wankaner",
        "district": "Morbi (Wankaner)",
        "question_gu": "વાંકાનેરના રણજીત વિલાસ પેલેસની સ્થાપત્ય વિશેષતા જણાવો.",
        "question_hi": "वांकानेर के रणजीत विलास पैलेस की स्थापत्य विशेषताएं बताएं।",
        "question_mr": "वांकानेरच्या रणजीत विलास पॅलेसविषयी सांगा.",
        "question_en": "What are the architectural highlights of Ranjit Vilas Palace in Wankaner?",
        "question_roman_gu": "Wankaner na Ranjit Vilas Palace vishe janavo.",
        "answer_gu": "રણજીત વિલાસ પેલેસ મોરબી જિલ્લાના વાંકાનેરમાં પહાડી ટેકરી પર આવેલો ૨૦મી સદીની શરૂઆતનો (ઈ.સ. ૧૯૦૭) ભવ્ય રાજમહેલ છે, જેનું નિર્માણ મહારાણા અમરસિંહજીએ કરાવ્યું હતું. આ મહેલ ગોથિક, મુઘલ, રાજપૂત, ડચ અને વિક્ટોરિયન સ્થાપત્ય શૈલીઓનું અદભુત મિશ્રણ છે. મહેલમાં ૭ માળ ઊંચો ક્લોક ટાવર, ઇટાલિયન માર્બલ સ્ટેચ્યુ, વિન્ટેજ કારોનો કલેક્શન અને ભારતના રજવાડાંઓના તલવારો-બંદૂકોનો મોટો શસ્ત્રાગાર (Armoury) આવેલો છે.",
        "short_answer_gu": "વાંકાનેરમાં ૧૯૦૭માં ટેકરી પર બનેલો મહેલ જે ગોથિક-રાજપૂત સ્થાપત્ય, વિન્ટેજ કારો અને શસ્ત્રાગાર માટે પ્રખ્યાત છે.",
        "short_answer_en": "Ranjit Vilas Palace (1907) in Wankaner blends Gothic, Mughal, and Rajput architecture, featuring an iconic clock tower, vintage cars, and royal armory.",
        "short_answer_hi": "वांकानेर में पहाड़ी पर १९०७ में निर्मित रणजीत विलास पैलेस अपनी अनूठी गॉथिक-राजपूत शैली और विंटेज कारों के लिए प्रसिद्ध है।",
        "keywords": ["Ranjit Vilas Palace", "Wankaner", "Morbi", "Amarsinhji", "Vintage Cars", "Clock Tower", "રણજીત વિલાસ પેલેસ", "વાંકાનેર", "મોરબી"],
        "source": "Gujarat Tourism",
        "source_type": "Heritage Palace",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_25",
        "category": "Historical Places",
        "title": "લાખોટા કિલ્લો અને તળાવ - જામનગર (Lakhota Fort & Lake Jamnagar)",
        "title_en": "Lakhota Fort Jamnagar",
        "district": "Jamnagar",
        "question_gu": "જામનગરના લાખોટા તળાવ અને લાખોટા મહેલ સંગ્રહાલય વિશે જણાવો.",
        "question_hi": "जामनगर के लाखोटा किले और झील के बारे में बताएं।",
        "question_mr": "जामनगरच्या लाखोटा किल्ला आणि तलावाविषयी माहिती द्या.",
        "question_en": "Tell me about Lakhota Fort and Lake in Jamnagar.",
        "question_roman_gu": "Jamnagar na Lakhota Fort ane talav vishe janavo.",
        "answer_gu": "લાખોટા કિલ્લો (લાખોટા મહેલ) જામનગર શહેરની મધ્યમાં આવેલા રણમલ તળાવ (લાખોટા તળાવ)ના ટાપુ પર સ્થિત અર્ધચંદ્રાકાર કિલ્લો છે. તેનું નિર્માણ ૧૯મી સદીમાં (૧૮૩૯-૧૮૪૫) જામ રણમલજી બીજા દ્વારા દુષ્કાળ રાહત કાર્ય તરીકે કરાવવામાં આવ્યું હતું. આ કિલ્લા સુધી પહોંચવા માટે પથ્થરનો સુંદર પુલ છે. કિલ્લામાં પુરાતત્વ સંગ્રહાલય છે જેમાં ૯મી થી ૧૮મી સદીના શિલ્પો, મધ્યકાલીન તોપો, બંદૂકો અને જામનગર રિયાસતનો ઇતિહાસ સચવાયેલો છે. શિયાળામાં લાખોટા તળાવ પર હજારો યાયાવર પક્ષીઓ (ગુલ, પેલિકન) આવે છે.",
        "short_answer_gu": "જામનગરમાં રણમલ તળાવના ટાપુ પર આવેલો ૧૯મી સદીનો જળદુર્ગ, જે પુરાતત્વીય સંગ્રહાલય અને પક્ષીદર્શન માટે જાણીતો છે.",
        "short_answer_en": "Lakhota Fort is an island fortress built in 1845 in the middle of Ranmal Lake in Jamnagar, now housing a museum of medieval weapons and sculptures.",
        "short_answer_hi": "जामनगर के रणमल (लाखोटा) तालाब के बीच स्थित लाखोटा किला एक द्वीप दुर्ग है जिसमें ऐतिहासिक संग्रहालय स्थित है।",
        "keywords": ["Lakhota Fort", "Ranmal Lake", "Jamnagar", "Jam Ranmalji", "Museum", "લાખોટા કિલ્લો", "જામનગર", "રણમલ તળાવ"],
        "source": "Archaeology Department of Gujarat / Gujarat Tourism",
        "source_type": "Heritage Monument",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_26",
        "category": "Historical Places",
        "title": "સુદામા મંદિર - પોરબંદર (Sudama Temple Porbandar - Only in India)",
        "title_en": "Sudama Temple Porbandar",
        "district": "Porbandar",
        "question_gu": "પોરબંદરમાં આવેલું ભારતનું એકમાત્ર સુદામા મંદિર વિશે જણાવો.",
        "question_hi": "पोरबंदर में स्थित भारत के एकमात्र सुदामा मंदिर के बारे में बताएं।",
        "question_mr": "पोरबंदर येथील भारतातील एकमेव सुदामा मंदिराविषयी सांगा.",
        "question_en": "Tell me about Sudama Temple in Porbandar, dedicated to Lord Krishna's childhood friend.",
        "question_roman_gu": "Porbandar na Sudama Mandir vishe janavo.",
        "answer_gu": "સુદામા મંદિર ગુજરાતના પોરબંદરમાં (જેનું પ્રાચીન પૌરાણિક નામ 'સુદામાપુરી' છે) આવેલું સમગ્ર ભારતમાં ભગવાન શ્રીકૃષ્ણના પરમ મિત્ર સુદામાજીને સમર્પિત એકમાત્ર ઐતિહાસિક મંદિર છે. આ મંદિરનું નિર્માણ ઈ.સ. ૧૯૦૨ થી ૧૯૦૭ દરમિયાન પોરબંદરના જેઠવા રાજવી રાણા ભાવસિંહજી દ્વારા સફેદ આરસપહાણથી કરાવવામાં આવ્યું હતું. મંદિરમાં સુદામાજી અને તેમની પત્ની સુશીલાની મૂર્તિઓ છે અને ભીંત પર શ્રીકૃષ્ણ-સુદામાની મૈત્રીના પ્રસંગો અંકિત છે. અહીં નવવિવાહિત યુગલો સુખી દાંપત્યજીવનના આશીર્વાદ લેવા આવે છે.",
        "short_answer_gu": "પોરબંદર (સુદામાપુરી)માં આવેલું સમગ્ર ભારતમાં સુદામાજીને સમર્પિત એકમાત્ર ઐતિહાસિક આરસનું મંદિર.",
        "short_answer_en": "Located in Porbandar (ancient Sudamapuri), this is the only temple in India dedicated to Sudama, the beloved childhood friend of Lord Krishna.",
        "short_answer_hi": "पोरबंदर में स्थित सुदामा मंदिर पूरे भारत में भगवान श्रीकृष्ण के बालसखा सुदामा को समर्पित एकमात्र मंदिर है।",
        "keywords": ["Sudama Temple", "Porbandar", "Sudamapuri", "Krishna Friend", "ભાવસિંહજી", "સુદામા મંદિર", "પોરબંદર"],
        "source": "Gujarat Tourism",
        "source_type": "Unique Spiritual Landmark",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_27",
        "category": "Historical Places",
        "title": "ખંભાલીડા બૌદ્ધ ગુફાઓ (Khambhalida Buddhist Caves Rajkot)",
        "title_en": "Khambhalida Buddhist Caves",
        "district": "Rajkot (Gondal)",
        "question_gu": "રાજકોટના ખંભાલીડા ખાતે આવેલી ૪થી-૫મી સદીની બૌદ્ધ ગુફાઓ વિશે જણાવો.",
        "question_hi": "राजकोट के खंभालीड़ा की चौथी-पांचवीं सदी की बौद्ध गुफाओं के बारे में बताएं।",
        "question_mr": "राजकोटच्या खंभालीडा बौद्ध गुंफांविषयी सांगा.",
        "question_en": "Tell me about the 4th-5th century Khambhalida Buddhist rock-cut caves in Rajkot.",
        "question_roman_gu": "Rajkot na Khambhalida Buddhist caves vishe janavo.",
        "answer_gu": "ખંભાલીડા બૌદ્ધ ગુફાઓ રાજકોટ જિલ્લાના ગોંડલ તાલુકાના ખંભાલીડા ગામ નજીક ભાદર નદીની શાખા કિનારે આવેલી ઈ.સ. ચોથી-પાંચમી સદીની પ્રાચીન શૈલકૃત (Rock-cut) બૌદ્ધ ગુફાઓ છે. તેની શોધ ૧૯૫૮માં પ્રસિદ્ધ પુરાતત્વવિદ્ પી.પી. પંડ્યા દ્વારા કરવામાં આવી હતી. અહીં ત્રણ મુખ્ય ગુફાઓ છે, જેમાં કેન્દ્રીય ચૈત્યગૃહના પ્રવેશદ્વાર પર ભગવાન બુદ્ધના બે વિશાળ બોધિસત્વ શિલ્પો - પદ્મપાણી (કમળધારી અવલોકિતેશ્વર) અને વજ્રપાણીનું અદભુત આલેખન છે, જે ગુજરાતમાં બૌદ્ધ ધર્મના સુવર્ણકાળનું પ્રતીક છે.",
        "short_answer_gu": "ગોંડલ પાસે આવેલી ૪થી સદીની પ્રાચીન બૌદ્ધ શૈલ ગુફાઓ, જેમાં બોધિસત્વ પદ્મપાણી અને વજ્રપાણીના શિલ્પો છે.",
        "short_answer_en": "Khambhalida Caves near Gondal are 4th-5th century rock-cut Buddhist caves featuring life-size carvings of Bodhisattvas Padmapani and Vajrapani.",
        "short_answer_hi": "गोंडल के पास खंभालीड़ा में स्थित चौथी सदी की बौद्ध गुफाएं बोधिसत्व पद्मपाणि और वज्रपाणि की विशाल प्रतिमाओं के लिए प्रसिद्ध हैं।",
        "keywords": ["Khambhalida Caves", "Buddhist Caves", "Rajkot", "Gondal", "Bodhisattva", "Padmapani", "ખંભાલીડા", "બૌદ્ધ ગુફાઓ", "બોધિસત્વ"],
        "source": "Archaeological Survey of India / Gujarat Archaeology",
        "source_type": "Ancient Rock-Cut Heritage",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "hist_28",
        "category": "Historical Places",
        "title": "કોટરેશ્વર મહાદેવ અને નારાયણ સરોવર (Koteshwar Mahadev & Narayan Sarovar Kutch)",
        "title_en": "Koteshwar Mahadev Kutch",
        "district": "Kutch",
        "question_gu": "કચ્છના પશ્ચિમ છેવાડે આવેલા કોટેશ્વર મહાદેવ અને પવિત્ર નારાયણ સરોવર વિશે જણાવો.",
        "question_hi": "कच्छ के पश्चिमी छोर पर स्थित कोटेश्वर महादेव और पवित्र नारायण सरोवर के बारे में बताएं।",
        "question_mr": "कच्छमधील कोटेश्वर महादेव आणि नारायण सरोवराविषयी सांगा.",
        "question_en": "Tell me about Koteshwar Mahadev Temple on India's western tip and holy Narayan Sarovar.",
        "question_roman_gu": "Kutch na Koteshwar Mahadev ane Narayan Sarovar vishe janavo.",
        "answer_gu": "કોટેશ્વર મહાદેવ મંદિર ગુજરાતના કચ્છ જિલ્લાના લખપત તાલુકામાં ભારતની પશ્ચિમી સીમા પર અરબી સમુદ્રના કિનારે આવેલું અતિ પ્રાચીન શિવમંદિર છે. પૌરાણિક કથા અનુસાર રાવણે શિવજી પાસેથી મેળવેલું આત્મલિંગ અહીં જમીન પર મૂકી દેતાં કરોડો લિંગો પ્રગટ થયાં હતાં. મંદિર સમુદ્ર તરફ એક પથ્થરની ટેકરી પર છે જ્યાંથી સૂર્યાસ્ત અદભુત દેખાય છે. નજીકમાં 'નારાયણ સરોવર' આવેલું છે, જે હિન્દુ ધર્મના ૫ પરમ પવિત્ર સરોવરો (માનસરોવર, બિંદુ સરોવર, પુષ્કર, પંપા અને નારાયણ સરોવર)માંનું એક છે, જ્યાં ભગવાન વિષ્ણુના મંદિરો આવેલાં છે.",
        "short_answer_gu": "ભારતના પશ્ચિમ છેવાડે સમુદ્રતટે કોટેશ્વર શિવમંદિર અને પંચ પવિત્ર સરોવરોમાંનું એક નારાયણ સરોવર.",
        "short_answer_en": "Koteshwar Mahadev is an ancient seaside Shiva temple at India's western border in Kutch, located next to holy Narayan Sarovar (one of the 5 sacred lakes).",
        "short_answer_hi": "भारत की पश्चिमी सीमा पर अरब सागर किनारे स्थित कोटेश्वर महादेव और पंच पवित्र सरोवरों में शामिल नारायण सरोवर कच्छ के प्रमुख तीर्थ हैं।",
        "keywords": ["Koteshwar", "Narayan Sarovar", "Kutch", "Western Border", "Ravana", "Shiva", "કોટેશ્વર", "નારાયણ સરોવર", "કચ્છ"],
        "source": "Gujarat Tourism",
        "source_type": "Sacred Coastal Border Pilgrimage",
        "source_url": "https://www.gujarattourism.com"
    },

    # -------------------------------------------------------------------------
    # ADDITIONAL PERSONALITIES (59-68)
    # -------------------------------------------------------------------------
    {
        "id": "pers_14",
        "category": "Historical Personalities",
        "title": "ધીરૂભાઈ અંબાણી (Dhirubhai Ambani - Industrial Visionary)",
        "title_en": "Dhirubhai Ambani",
        "district": "Junagadh (Chorwad)",
        "question_gu": "ધીરૂભાઈ અંબાણી અને રિલાયન્સ ઇન્ડસ્ટ્રીઝની સ્થાપના વિશે જણાવો.",
        "question_hi": "धीरूभाई अंबानी और रिलायंस इंडस्ट्रीज की स्थापना के बारे में बताएं।",
        "question_mr": "धीरूभाई अंबानी आणि रिलायन्सच्या स्थापनेविषयी सांगा.",
        "question_en": "Tell me about Dhirubhai Ambani, born in Chorwad, Gujarat, who founded Reliance Industries.",
        "question_roman_gu": "Dhirubhai Ambani Chorwad ane Reliance vishe janavo.",
        "answer_gu": "ધીરજલાલ હીરાચંદ અંબાણી 'ધીરૂભાઈ' (૨૮ ડિસેમ્બર ૧૯૩૨ - ૬ જુલાઈ ૨૦૦૨)નો જન્મ જૂનાગઢ જિલ્લાના ચોરવાડ ગામમાં એક સામાન્ય શિક્ષકના ઘરમાં થયો હતો. યમનના એડનમાં પેટ્રોલ પંપ પર કામ કર્યા બાદ તેમણે માત્ર ૫૦૦ રૂપિયાની મૂડી સાથે મુંબઈ આવીને મસાલા અને પોલિએસ્ટર યાર્નનો વેપાર શરૂ કર્યો અને 'રિલાયન્સ ઇન્ડસ્ટ્રીઝ'નું નિર્માણ કર્યું. તેમણે ભારતીય શેરબજારમાં સામાન્ય મધ્યમવર્ગીય નાગરિકોને ઇક્વિટી રોકાણકાર બનાવી મૂડીબજારમાં ક્રાંતિ સર્જી. જામનગરમાં વિશ્વની સૌથી મોટી ઓઇલ રિફાઇનરી તેમની દૂરંદેશીનું પરિણામ છે. ૨૦૧૬માં તેમને મરણોત્તર પદ્મવિભૂષણ એનાયત થયો હતો. ચોરવાડ ખાતે તેમનું પૈતૃક ઘર સ્મારક બન્યું છે.",
        "short_answer_gu": "ચોરવાડમાં જન્મેલા ભારતના મહાન ઉદ્યોગ સાહસિક, જેમણે રિલાયન્સ ઇન્ડસ્ટ્રીઝની સ્થાપના કરી અને શેરબજાર ક્રાંતિ લાવી.",
        "short_answer_en": "Born in Chorwad, Gujarat, Dhirubhai Ambani founded Reliance Industries, democratized equity investing in India, and built the world's largest oil refinery at Jamnagar.",
        "short_answer_hi": "चोरवाड़ (जूनागढ़) में जन्मे धीरूभाई अंबानी ने रिलायंस इंडस्ट्रीज की स्थापना कर भारत के कॉर्पोरेट और शेयर बाजार में अभूतपूर्व क्रांति की।",
        "keywords": ["Dhirubhai Ambani", "Reliance", "Chorwad", "Jamnagar Refinery", "Entrepreneur", "ધીરૂભાઈ અંબાણી", "ચોરવાડ", "રિલાયન્સ"],
        "source": "Corporate & Industrial History of Gujarat",
        "source_type": "Industrial Visionary Biography",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "pers_15",
        "category": "Historical Personalities",
        "title": "ડૉ. વર્ગીસ કુરિયન અને ત્રિભુવનદાસ પટેલ - શ્વેત ક્રાંતિ (Amul & White Revolution)",
        "title_en": "Dr. Verghese Kurien & Tribhuvandas Patel",
        "district": "Anand",
        "question_gu": "આણંદમાં અમૂલ ડેરીની સ્થાપના અને શ્વેત ક્રાંતિ (દૂધ ક્રાંતિ) વિશે જણાવો.",
        "question_hi": "आनंद में अमूल डेयरी की स्थापना और श्वेत क्रांति (दुग्ध क्रांति) के बारे में बताएं।",
        "question_mr": "आनंद येथील अमूल डेअरीची स्थापना आणि श्वेतक्रांती याविषयी सांगा.",
        "question_en": "Explain the establishment of Amul in Anand and the White Revolution led by Dr. Kurien and Tribhuvandas Patel.",
        "question_roman_gu": "Anand ma Amul Dairy ane Shwet Kranti vishe janavo.",
        "answer_gu": "અમૂલ (આણંદ મિલ્ક યુનિયન લિમિટેડ - AMUL)ની સ્થાપના ૧૪ ડિસેમ્બર ૧૯૪૬ના રોજ સરદાર વલ્લભભાઈ પટેલની પ્રેરણાથી અને ત્રિભુવનદાસ પટેલના નેતૃત્વમાં દૂધ ઉત્પાદક ખેડૂતોને વચેટિયાઓના શોષણમાંથી મુક્ત કરવા માટે સહકારી ધોરણે થઈ હતી. ત્યારબાદ ડૉ. વર્ગીસ કુરિયન ('ભારતમાં શ્વેત ક્રાંતિના પિતા' - Milkman of India) અને એચ.એમ. દલાયા આણંદ આવ્યા અને તેમણે ભેંસના દૂધમાંથી પાવડર બનાવવાની વિશ્વની પ્રથમ ટેકનોલોજી વિકસાવી. અમૂલના સફળ 'આણંદ પેટર્ન' મોડેલથી ભારત સમગ્ર વિશ્વમાં દૂધ ઉત્પાદનમાં પ્રથમ ક્રમે પહોંચ્યો અને 'ઓપરેશન ફ્લડ' (Operation Flood) સફળ બન્યું.",
        "short_answer_gu": "આણંદમાં ૧૯૪૬માં સ્થપાયેલી અમૂલ ડેરી અને ડૉ. કુરિયન-ત્રિભુવનદાસ પટેલનું સહકારી મોડેલ, જેણે દેશમાં શ્વેત ક્રાંતિ સર્જી.",
        "short_answer_en": "Amul was established in Anand in 1946 through Tribhuvandas Patel and Dr. Verghese Kurien under Sardar Patel's vision, sparking India's Operation Flood White Revolution.",
        "short_answer_hi": "आनंद में १९४६ में स्थापित अमूल और डॉ. वर्गीज कुरियन के नेतृत्व ने 'ऑपरेशन फ्लड' के जरिए भारत को विश्व का सबसे बड़ा दुग्ध उत्पादक बनाया।",
        "keywords": ["Amul", "Verghese Kurien", "Tribhuvandas Patel", "Anand", "White Revolution", "Operation Flood", "અમૂલ", "શ્વેત ક્રાંતિ", "આણંદ"],
        "source": "GCMMF (Amul) / National Dairy Development Board (NDDB)",
        "source_type": "Cooperative & Agricultural Milestone",
        "source_url": "https://amul.com"
    },
    {
        "id": "pers_16",
        "category": "Historical Personalities",
        "title": "કવિ દલપતરામ (Kavi Dalpatram - Pioneer of Social Reform Poetry)",
        "title_en": "Kavi Dalpatram",
        "district": "Surendranagar (Wadhwan) / Ahmedabad",
        "question_gu": "કવિ દલપતરામ અને ફાર્બસ સાહેબ સાથેની તેમની મિત્રતા વિશે જણાવો.",
        "question_hi": "कवि दलपतराम और फारबिस साहब के साथ उनकी मित्रता के बारे में बताएं।",
        "question_mr": "कवी दलपतराम यांच्याविषयी सांगा.",
        "question_en": "Tell me about Kavi Dalpatram, his social reform poems, and his bond with Alexander Kinloch Forbes.",
        "question_roman_gu": "Kavi Dalpatram ane Forbes saheb vishe janavo.",
        "answer_gu": "કવિ દલપતરામ ડાહ્યાભાઈ ત્રિવેદી (૧૮૨૦ - ૧૮૯૮) સુરેન્દ્રનગરના વઢવાણમાં જન્મેલા અર્વાચીન ગુજરાતી સાહિત્યના અગ્રણી કવિ, નાટ્યકાર અને સુધારક હતા. તેમણે બ્રિટિશ અધિકારી એલેક્ઝાન્ડર કિનલોક ફાર્બસ સાથે મળીને ૧૮૪૮માં 'ગુજરાત વર્નાક્યુલર સોસાયટી' (હાલની ગુજરાત વિદ્યાસભા)ની સ્થાપના કરી હતી અને 'બુદ્ધિપ્રકાશ' સામયિક શરૂ કર્યું હતું. તેમણે અંધશ્રદ્ધા અને બાળલગ્ન સામે કટાક્ષ કરતું પ્રથમ ગુજરાતી નાટક 'લક્ષ્મી' અને 'મિથ્યાભિમાન' (જીવરામ ભટ્ટનું પાત્ર) લખ્યાં. તેમની હાસ્ય-કવિતા 'ઊંટ કહે આ સભામાં વાંકાં અંગવાળાં ભૂંડા' અને બાળગીતો આજે પણ ખૂબ લોકપ્રિય છે.",
        "short_answer_gu": "વઢવાણમાં જન્મેલા સુધારક કવિ, જેમણે ફાર્બસ સાહેબ સાથે મળી ગુજરાત વિદ્યાસભા સ્થાપી અને 'મિથ્યાભિમાન' નાટક રચ્યું.",
        "short_answer_en": "Kavi Dalpatram was a 19th-century reformist poet who co-founded Gujarat Vernacular Society with A.K. Forbes and wrote the satirical play 'Mithyabhiman'.",
        "short_answer_hi": "कवि दलपतराम ने अलेक्जेंडर फोर्ब्स के साथ मिलकर गुजरात विद्यासभा की स्थापना की और 'मिथ्याभिमान' नाटक लिखा।",
        "keywords": ["Dalpatram", "Wadhwan", "Forbes", "Gujarat Vidya Sabha", "Mithyabhiman", "Buddhiprakash", "દલપતરામ", "મિથ્યાભિમાન", "બુદ્ધિપ્રકાશ"],
        "source": "Gujarat Sahitya Parishad / Gujarat Vidya Sabha",
        "source_type": "Literary Pioneer Biography",
        "source_url": "https://gujaratisahityaparishad.com"
    },
    {
        "id": "pers_17",
        "category": "Historical Personalities",
        "title": "મહાકવિ પ્રેમાનંદ ભટ્ટ (Premanand Bhatt - Master of Akhyan)",
        "title_en": "Premanand Bhatt",
        "district": "Vadodara",
        "question_gu": "વડોદરાના મહાકવિ પ્રેમાનંદ અને માણભટ્ટ પરંપરા વિશે જણાવો.",
        "question_hi": "वडोदरा के महाकवि प्रेमानंद और माणभट्ट परंपरा के बारे में बताएं।",
        "question_mr": "महाकवी प्रेमानंद आणि माणभट्ट परंपरेविषयी सांगा.",
        "question_en": "Tell me about Mahakavi Premanand Bhatt of Vadodara and the Manbhatt musical storytelling tradition.",
        "question_roman_gu": "Premanand Bhatt Vadodara ane Manbhatt parampara vishe janavo.",
        "answer_gu": "પ્રેમાનંદ ભટ્ટ (૧૬૩૬ - ૧૭૩૪) ૧૭મી સદીના વડોદરાના સર્વોચ્ચ ગુજરાતી આખ્યાનકાર અને મહાકવિ હતા. તેઓ વ્યવસાયે 'માણભટ્ટ' (તાંબાની મોટી માણ/ઘડા પર આંગળીઓમાં પહેરેલી વીંટીઓ વગાડીને સંગીતમય વાર્તા કહેનાર) હતા. તેમણે પ્રતિજ્ઞા લીધી હતી કે 'જ્યાં સુધી ગુજરાતી ભાષાને અન્ય ભાષાઓ સમકક્ષ ગૌરવ નહીં મળે ત્યાં સુધી હું પાઘડી નહીં પહેરું.' તેમણે 'ઓખાહરણ', 'નળાખ્યાન', 'સુદામાચરિત્ર', 'કુંવરબાઈનું મામેરું' અને 'દશમસ્કંધ' જેવાં અદભુત આખ્યાનો રચી ગુજરાતી ભાષાને અત્યંત સમૃદ્ધ બનાવી.",
        "short_answer_gu": "વડોદરાના ૧૭મી સદીના આખ્યાન શિરોમણી કવિ, જેમણે તાંબાની માણ વગાડીને 'નળાખ્યાન' અને 'ઓખાહરણ' જેવાં અમર આખ્યાનો રચ્યાં.",
        "short_answer_en": "Premanand Bhatt of Vadodara (17th century) was the greatest composer of Akhyana poetry and a master of the Manbhatt musical pot-playing tradition.",
        "short_answer_hi": "वडोदरा के १७वीं सदी के महाकवि प्रेमानंद ने तांबे की 'माण' बजाकर 'नळाख्यान' और 'ओखाहरण' जैसे अमर आख्यान रचे।",
        "keywords": ["Premanand Bhatt", "Manbhatt", "Akhyan", "Vadodara", "Okhaharan", "Nalakhyan", "પ્રેમાનંદ", "માણભટ્ટ", "આખ્યાન", "વડોદરા"],
        "source": "Gujarati Sahitya Parishad",
        "source_type": "Classical Literary Giant",
        "source_url": "https://gujaratisahityaparishad.com"
    },
    {
        "id": "pers_18",
        "category": "Historical Personalities",
        "title": "ભક્તકવિ દયારામ - ગરબીના પિતા (Dayaram - Master of Garbi)",
        "title_en": "Dayaram",
        "district": "Vadodara (Chandod / Dabhoi)",
        "question_gu": "ભક્તકવિ દયારામ અને તેમની શ્રીકૃષ્ણ પ્રેમલક્ષણા ભક્તિની ગરબીઓ વિશે જણાવો.",
        "question_hi": "भक्तकवि दयाराम और उनकी गरबी काव्य शैली के बारे में बताएं।",
        "question_mr": "भक्तकवी दयाराम आणि त्यांच्या गरबी काव्याविषयी सांगा.",
        "question_en": "Tell me about the medieval saint-poet Dayaram and his Krishna-bhakti Garbi compositions.",
        "question_roman_gu": "Bhaktakavi Dayaram ane Garbi vishe janavo.",
        "answer_gu": "દયારામ (૧૭૭૭ - ૧૮૫૨) નર્મદા કિનારે ચાંદોદ-ડભોઈના વતની અને મધ્યકાલીન ગુજરાતી સાહિત્યના અંતિમ પ્રમુખ ભક્તકવિ હતા. તેઓ પુષ્ટિમાર્ગીય વૈષ્ણવ સંપ્રદાયના અનુયાયી હતા. તેમણે શ્રીકૃષ્ણ અને ગોપીઓના મધુર પ્રણય-સંવાદો પર આધારિત અતિ લોકપ્રિય 'ગરબી' કાવ્યપ્રકારનું સર્જન કર્યું. તેમની ગરબીઓ જેમ કે 'શ્યામ રંગ સમીપે ન જાવું', 'હવે સખી નહીં બોલું રે નંદકુંવર સાથે', અને 'ઓ વાંસલડી વેરણ થઈ લાગી રે' આજે પણ ગુજરાતમાં ગરબા મહોત્સવમાં અત્યંત ભાવથી ગવાય છે.",
        "short_answer_gu": "મધ્યકાલીન યુગના છેલ્લા મહાન વૈષ્ણવ કવિ, જેઓ તેમની શ્રીકૃષ્ણ પ્રેમભક્તિની મધુર 'ગરબીઓ' માટે જાણીતા છે.",
        "short_answer_en": "Dayaram (1777-1852) of Dabhoi was the last great medieval Gujarati poet, famed for his melodious Krishna-devotion lyric poems called 'Garbi'.",
        "short_answer_hi": "चांदोद-डभोई के भक्तकवि दयाराम मध्यकालीन गुजराती साहित्य के अंतिम बड़े कवि थे, जिन्होंने मधुर 'गरबी' पदों की रचना की।",
        "keywords": ["Dayaram", "Garbi", "Krishna Bhakti", "Dabhoi", "Chandod", "Pushtimarg", "દયારામ", "ગરબી", "કૃષ્ણ ભક્તિ"],
        "source": "Gujarati Sahitya Parishad",
        "source_type": "Medieval Lyric Poet",
        "source_url": "https://gujaratisahityaparishad.com"
    },
    {
        "id": "pers_19",
        "category": "Historical Personalities",
        "title": "મીરાંબાઈ - દ્વારકામાં ભક્તિ અને વિલીનીકરણ (Mirabai in Dwarka)",
        "title_en": "Mirabai at Dwarka",
        "district": "Devbhumi Dwarka",
        "question_gu": "મીરાંબાઈના જીવનના અંતિમ વર્ષો અને દ્વારકામાં શ્રીકૃષ્ણ મૂર્તિમાં સમાઈ જવાની ઘટના જણાવો.",
        "question_hi": "मीराबाई के अंतिम वर्ष और द्वारका में श्रीकृष्ण मूर्ति में समाने की घटना बताएं।",
        "question_mr": "मीराबाईंचे द्वारकेतील दिवस आणि श्रीकृष्णाच्या मूर्तीत विलीन होण्याविषयी सांगा.",
        "question_en": "Tell me about saint Mirabai's final years in Dwarka and her devotion to Lord Krishna.",
        "question_roman_gu": "Mirabai na Dwarka ma antim varsho vishe janavo.",
        "answer_gu": "સંત કવયિત્રી મીરાંબાઈ (૧૪૯૮ - ૧૫૪૬) ભગવાન શ્રીકૃષ્ણની પરમ પ્રેમલક્ષણા ભક્ત હતાં. મેવાડના રાણા પરિવારનો ત્યાગ કરીને તેઓ વૃંદાવન થઈને પોતાના જીવનના અંતિમ વર્ષોમાં ગુજરાતના દ્વારકામાં આવી વસ્યાં હતાં. દ્વારકામાં તેમણે દ્વારકાધીશજીના ચરણોમાં રહીને અસંખ્ય ગુજરાતી, વ્રજ અને રાજસ્થાની ભક્તિપદો રચ્યાં. માન્યતા અનુસાર ઈ.સ. ૧૫૪૬માં દ્વારકાના જગતમંદિરમાં એકતારા સાથે ભજન ગાતાં ગાતાં મીરાંબાઈ સાક્ષાત્ શ્રીકૃષ્ણની મૂર્તિમાં જ્યોતિ સ્વરૂપે સમાઈ ગયાં હતાં અને માત્ર તેમની સાડીનો છેડો મૂર્તિના હાથમાં રહ્યો હતો.",
        "short_answer_gu": "મહાન કૃષ્ણભક્ત કવયિત્રી, જેમણે અંતિમ વર્ષો દ્વારકામાં વિતાવ્યા અને દ્વારકાધીશની મૂર્તિમાં લીન થઈ ગયાં.",
        "short_answer_en": "Saint-poetess Mirabai spent her final years in Dwarka, where she composed immortal padas and merged into the idol of Lord Dwarkadhish.",
        "short_answer_hi": "भक्तिकाल की अमर संत मीराबाई ने अपने अंतिम वर्ष द्वारका में बिताए और मान्यता है कि वे द्वारकाधीश की मूर्ति में समा गईं।",
        "keywords": ["Mirabai", "Dwarka", "Krishna Bhakti", "Dwarkadhish", "Ek Tara", "મીરાંબાઈ", "દ્વારકા", "ભક્તિપદ"],
        "source": "Bhakti Literature Heritage / Dwarkadhish Devasthan",
        "source_type": "Saint & Bhakti Poetess",
        "source_url": "https://dwarkadhish.org"
    },
    {
        "id": "pers_20",
        "category": "Historical Personalities",
        "title": "જામ રાવળ - જામનગરના સ્થાપક (Jam Rawal - Founder of Nawanagar)",
        "title_en": "Jam Rawal",
        "district": "Jamnagar",
        "question_gu": "જામ રાવળ અને જામનગર (નવાનગર)ની સ્થાપના (૧૫૪૦) વિશે જણાવો.",
        "question_hi": "जाम रावल और जामनगर (नवानगर) की स्थापना (१५४०) के बारे में बताएं।",
        "question_mr": "जाम रावळ आणि जामनगरच्या स्थापनेविषयी सांगा.",
        "question_en": "Explain how Jam Rawal founded Nawanagar (modern Jamnagar) in 1540.",
        "question_roman_gu": "Jam Rawal ane Jamnagar ni sthapana vishe janavo.",
        "answer_gu": "જામ રાવળ જાડેજા રાજપૂત વંશના પરાક્રમી યોદ્ધા હતા, જેમણે ઈ.સ. ૧૫૪૦માં (શ્રાવણ સુદ સાતમ) સૌરાષ્ટ્રના ઉત્તર-પશ્ચિમ કિનારે રંગમતી અને નાગમતી નદીઓના સંગમ પર 'નવાનગર' (હાલનું જામનગર) રાજ્યની સ્થાપના કરી હતી. કચ્છથી સૌરાષ્ટ્રમાં આવીને તેમણે નવાનગરને રાજધાની બનાવી અને જામ વંશનું શાસન સ્થાપ્યું. જામનગરમાં તેમણે કુળદેવી માં આશાપુરાનું મંદિર બંધાવ્યું. પાછળથી ક્રિકેટ દિગ્ગજ જામ રણજીતસિંહજી (જેમના નામ પરથી રણજી ટ્રોફી છે) અને જામ દિગ્વિજયસિંહજી આ જ રાજવંશના ગૌરવવંતા શાસકો રહ્યા.",
        "short_answer_gu": "૧૫૪૦માં રંગમતી-નાગમતી નદી કિનારે નવાનગર (જામનગર) રજવાડાની સ્થાપના કરનાર જાડેજા શાસક.",
        "short_answer_en": "Jam Rawal founded the princely state of Nawanagar (present-day Jamnagar) in 1540 on the banks of rivers Nagmati and Rangmati.",
        "short_answer_hi": "जाम रावल ने १५४० में नागमती और रंगमती नदियों के संगम पर नवानगर (जामनगर) की स्थापना की थी।",
        "keywords": ["Jam Rawal", "Jamnagar", "Nawanagar", "Jadeja", "Ranji Trophy", "Ashapura", "જામ રાવળ", "જામનગર", "નવાનગર"],
        "source": "State Gazetteer of Gujarat / Jamnagar Municipal Corporation",
        "source_type": "Historical Founder Biography",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "pers_21",
        "category": "Historical Personalities",
        "title": "કસ્તૂરબા ગાંધી (Kasturba Gandhi - Ba)",
        "title_en": "Kasturba Gandhi",
        "district": "Porbandar",
        "question_gu": "કસ્તૂરબા ગાંધી ('બા')નું સ્વાતંત્ર્ય સંગ્રામમાં યોગદાન જણાવો.",
        "question_hi": "कस्तूरबा गांधी ('बा') का स्वतंत्रता संग्राम में योगदान बताएं।",
        "question_mr": "कस्तुरबा गांधी यांचे स्वातंत्र्य लढ्यातील योगदान सांगा.",
        "question_en": "Explain Kasturba Gandhi's role and sacrifice in India's freedom struggle.",
        "question_roman_gu": "Kasturba Gandhi Ba nu swatantrya sangram ma yogdan janavo.",
        "answer_gu": "કસ્તૂરબા મોહનદાસ ગાંધી ('બા'; ૧૧ એપ્રિલ ૧૮૬૯ - ૨૨ ફેબ્રુઆરી ૧૯૪૪)નો જન્મ પોરબંદરમાં ગોકુલદાસ કાપડિયાના ઘરમાં થયો હતો. તેઓ મહાત્મા ગાંધીના ધર્મપત્ની હોવા સાથે ભારતના સ્વાતંત્ર્ય સંગ્રામના અડગ વીરાંગના હતાં. દક્ષિણ આફ્રિકાના સત્યાગ્રહથી માંડીને ૧૯૧૭ના ચંપારણ, ખેડા અને ૧૯૩૦ની દાંડી કૂચમાં તેમણે મહિલાઓનું નેતૃત્વ કર્યું અને અસંખ્ય વાર જેલવાસ ભોગવ્યો. ૧૯૪૨ના 'ભારત છોડો આંદોલન' દરમિયાન પુણેના આગા ખાન પેલેસમાં જેલવાસ દરમિયાન તેમનું નિર્વાણ થયું હતું.",
        "short_answer_gu": "પોરબંદરમાં જન્મેલાં 'બા', જેમણે સ્વાતંત્ર્ય સંગ્રામમાં મહિલાઓનું નેતૃત્વ કર્યું અને અહિંસક લડતમાં મોખરે રહ્યાં.",
        "short_answer_en": "Kasturba Gandhi ('Ba'), born in Porbandar, was a courageous leader in India's freedom struggle who stood alongside Mahatma Gandhi across all satyagrahas.",
        "short_answer_hi": "पोरबंदर में जन्मीं कस्तूरबा गांधी ('बा') ने भारतीय स्वतंत्रता आंदोलन में महिलाओं का नेतृत्व किया और अपना जीवन न्योछावर किया।",
        "keywords": ["Kasturba Gandhi", "Ba", "Porbandar", "Aga Khan Palace", "Freedom Fighter", "કસ્તૂરબા", "બા", "પોરબંદર"],
        "source": "National Gandhi Museum",
        "source_type": "Historical Biography",
        "source_url": "https://www.gandhiheritageportal.org"
    },
    {
        "id": "pers_22",
        "category": "Historical Personalities",
        "title": "મહારાજા સયાજીરાવ ગાયકવાડ ત્રીજા (Maharaja Sayajirao Gaekwad III of Baroda)",
        "title_en": "Maharaja Sayajirao Gaekwad III",
        "district": "Vadodara",
        "question_gu": "વડોદરાના પ્રગતિશીલ મહારાજા સયાજીરાવ ગાયકવાડના સુધારાઓ જણાવો.",
        "question_hi": "वडोदरा के प्रगतिशील महाराजा सयाजीराव गायकवाड़ तृतीय के सुधार बताएं।",
        "question_mr": "वडोदराचे महाराजा सयाजीराव गायकवाड यांचे कार्य सांगा.",
        "question_en": "Detail the progressive reforms of Maharaja Sayajirao Gaekwad III of Baroda.",
        "question_roman_gu": "Vadodara na Maharaja Sayajirao Gaekwad III na sudharao janavo.",
        "answer_gu": "મહારાજા સયાજીરાવ ગાયકવાડ ત્રીજા (૧૮૬૩ - ૧૯૩૯) વડોદરા (બરોડા) રિયાસતના અત્યંત દુરંદેશી, વિદ્વાન અને પ્રગતિશીલ રાજવી હતા. તેમણે ૧૯૦૬માં ભારતમાં સૌપ્રથમ વખત વડોદરા રાજ્યમાં પ્રાથમિક શિક્ષણ મફત અને ફરજિયાત બનાવ્યું. તેમણે બાળલગ્ન પ્રતિબંધ ધારો, પુસ્તકાલય પ્રવૃત્તિ (સેન્ટ્રલ લાઇબ્રેરી), બેંક ઓફ બરોડા (૧૯૦૮)ની સ્થાપના અને મહારાજા સયાજીરાવ યુનિવર્સિટી (MSU)નો પાયો નાખ્યો. તેમણે ડૉ. બાબાસાહેબ આંબેડકરને ઉચ્ચ અભ્યાસ માટે કોલંબિયા યુનિવર્સિટી લંડન મોકલવા સ્કોલરશિપ આપી હતી.",
        "short_answer_gu": "વડોદરાના પ્રજાવત્સલ રાજવી જેમણે ભારતમાં સૌપ્રથમ મફત-ફરજિયાત પ્રાથમિક શિક્ષણ લાગુ કર્યું અને ડૉ. આંબેડકરને સ્કોલરશિપ આપી.",
        "short_answer_en": "Maharaja Sayajirao Gaekwad III of Baroda was a visionary reformer who introduced India's first free compulsory primary education in 1906 and funded Dr. B.R. Ambedkar's higher studies.",
        "short_answer_hi": "बड़ौदा के महाराजा सयाजीराव गायकवाड़ ने १९०६ में भारत में पहली बार मुफ्त प्राथमिक शिक्षा लागू की और डॉ. आंबेडकर को छात्रवृत्ति दी।",
        "keywords": ["Sayajirao Gaekwad", "Baroda", "Vadodara", "Compulsory Education", "Bank of Baroda", "Dr Ambedkar", "સયાજીરાવ ગાયકવાડ", "વડોદરા", "શિક્ષણ"],
        "source": "Baroda Royal Archives / MSU Baroda",
        "source_type": "Visionary Monarch Biography",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "pers_23",
        "category": "Historical Personalities",
        "title": "દર્શક - મનુભાઈ પંચોળી (Manubhai Pancholi 'Darshak')",
        "title_en": "Manubhai Pancholi Darshak",
        "district": "Morbi (Panchasia) / Bhavnagar (Sanosara)",
        "question_gu": "સાહિત્યકાર અને કેળવણીકાર મનુભાઈ પંચોળી 'દર્શક' અને તેમની નવલકથાઓ વિશે જણાવો.",
        "question_hi": "साहित्यकार और शिक्षाविद् मनुभाई पंचोली 'दर्शक' के बारे में बताएं।",
        "question_mr": "मनुभाई पंचोली 'दर्शक' यांच्याविषयी सांगा.",
        "question_en": "Tell me about Gujarati litterateur and educationist Manubhai Pancholi 'Darshak'.",
        "question_roman_gu": "Manubhai Pancholi Darshak ane temni navalkathao vishe janavo.",
        "answer_gu": "મનુભાઈ રાજારામ પંચોળી 'દર્શક' (૧૯૧૪ - ૨૦૦૧) ગુજરાતી સાહિત્યના સમર્થ નવલકથાકાર, નાટ્યકાર, ચિંતક, સ્વાતંત્ર્ય સેનાની અને મહાન કેળવણીકાર હતા. તેમણે ભાવનગરના સણોસરા ખાતે 'લોકભારતી' ગ્રામવિદ્યાપીઠની સ્થાપના કરી ગ્રામીણ ઉચ્ચ શિક્ષણનો નવો રાહ ચીંધ્યો હતો. તેમની અમર નવલકથા 'ઝેર તો પીધાં છે જાણી જાણી' (ત્રણ ભાગમાં સોક્રેટિસ અને ભારતીય મૂલ્યોનું દર્શન) અને 'સોક્રેટિસ' ગુજરાતી ક્લાસિક ગણાય છે. તેમને મૂર્તિદેવી પુરસ્કાર અને સરસ્વતી સન્માન એનાયત થયા હતા.",
        "short_answer_gu": "લોકભારતી સણોસરાના સ્થાપક અને 'ઝેર તો પીધાં છે જાણી જાણી' તથા 'સોક્રેટિસ' જેવી અમર નવલકથાઓના સર્જક.",
        "short_answer_en": "Manubhai Pancholi 'Darshak' was a renowned novelist and rural educationist who founded Lokbharti Sanosara and wrote classics like 'Jher To Pidhan Chhe Jani Jani'.",
        "short_answer_hi": "लोकभारती सणोसरा के संस्थापक और मूर्धन्य साहित्यकार मनुभाई पंचोली 'दर्शक' ने 'झेर तो पीधां छे जाणी जाणी' जैसी कालजयी कृतियां रचीं।",
        "keywords": ["Darshak", "Manubhai Pancholi", "Lokbharti", "Sanosara", "Jher To Pidhan Chhe", "Socrates", "દર્શક", "મનુભાઈ પંચોળી", "લોકભારતી"],
        "source": "Gujarati Sahitya Parishad / Lokbharti",
        "source_type": "Literary & Educational Giant",
        "source_url": "https://gujaratisahityaparishad.com"
    },

    # -------------------------------------------------------------------------
    # ADDITIONAL FESTIVALS & FAIRS (69-78)
    # -------------------------------------------------------------------------
    {
        "id": "fest_07",
        "category": "Festivals",
        "title": "અમદાવાદ જગન્નાથ રથયાત્રા (Ahmedabad Rath Yatra - Jagannath Temple)",
        "title_en": "Ahmedabad Rath Yatra",
        "district": "Ahmedabad",
        "question_gu": "અમદાવાદની જગન્નાથ રથયાત્રા (અષાઢી બીજ) વિશે જણાવો.",
        "question_hi": "अहमदाबाद की जगन्नाथ रथयात्रा (आषाढ़ी दूज) के बारे में बताएं।",
        "question_mr": "अहमदाबादच्या जगन्नाथ रथयात्रेविषयी सांगा.",
        "question_en": "Tell me about the historic Jagannath Rath Yatra in Ahmedabad on Ashadhi Beej.",
        "question_roman_gu": "Ahmedabad Jagannath Rath Yatra Ashadhi Beej vishe janavo.",
        "answer_gu": "અમદાવાદની જગન્નાથ રથયાત્રા દર વર્ષે અષાઢ સુદ બીજ (અષાઢી બીજ)ના પવિત્ર દિવસે જમાલપુર સ્થિત ૪૦૦ વર્ષ જૂના જગન્નાથજી મંદિરેથી નીકળે છે. પુરી પછી તે ભારતની બીજા ક્રમની સૌથી મોટી અને ભવ્ય રથયાત્રા છે. સંત નરસિંહદાસજીએ ઈ.સ. ૧૮૭૮માં આ પરંપરા શરૂ કરી હતી. ભગવાન જગન્નાથ (નંદીઘોષ રથ), ભાઈ બલભદ્ર (તાલધ્વજ રથ) અને બહેન સુભદ્રાજી (પદ્મધ્વજ રથ)ના સુશોભિત રથો ૧૪ કિમી લાંબા ઐતિહાસિક કોટ વિસ્તારના માર્ગો પર ફરે છે. રથયાત્રા પૂર્વે મુખ્યમંત્રી દ્વારા સોનાની સાવરણીથી રસ્તો સાફ કરવાની 'પહિંદ વિધિ' થાય છે. પ્રસાદમાં જાંબુ અને અંકુરિત મગ વહેંચાય છે.",
        "short_answer_gu": "અષાઢી બીજે અમદાવાદમાં નીકળતી ભારતની બીજા ક્રમની સૌથી મોટી રથયાત્રા, જે ૧૮૭૮થી અવિરત યોજાય છે.",
        "short_answer_en": "Ahmedabad Jagannath Rath Yatra on Ashadhi Beej is India's second largest chariot procession after Puri, held annually since 1878.",
        "short_answer_hi": "आषाढ़ी दूज को अहमदाबाद में निकलने वाली जगन्नाथ रथयात्रा पुरी के बाद भारत की दूसरी सबसे बड़ी ऐतिहासिक रथयात्रा है।",
        "keywords": ["Rath Yatra", "Ahmedabad", "Jagannath Temple", "Ashadhi Beej", "Jamalpur", "Pahind Vidhi", "રથયાત્રા", "અમદાવાદ", "જગન્નાથ મંદિર", "અષાઢી બીજ"],
        "source": "Shree Jagannath Mandir Trust / Gujarat Tourism",
        "source_type": "Major State Religious Festival",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "fest_08",
        "category": "Festivals",
        "title": "ડાંગ દરબાર મહોત્સવ (Dang Darbar Festival Ahwa)",
        "title_en": "Dang Darbar",
        "district": "Dang (Ahwa)",
        "question_gu": "ડાંગ દરબાર આદિવાસી ઉત્સવ અને હોળી પર્વ વિશે જણાવો.",
        "question_hi": "डांग दरबार आदिवासी उत्सव और होली पर्व के बारे में बताएं।",
        "question_mr": "डांग दरबार आदिवासी उत्सवाविषयी माहिती द्या.",
        "question_en": "Tell me about the tribal cultural festival Dang Darbar in Ahwa.",
        "question_roman_gu": "Dang Darbar adivasi utsav Ahwa vishe janavo.",
        "answer_gu": "ડાંગ દરબાર એ દક્ષિણ ગુજરાતના ડાંગ જિલ્લાના મુખ્ય મથક આહવા ખાતે હોળી (ધૂળેટી) પહેલાં યોજાતો ત્રણ દિવસીય ઐતિહાસિક આદિવાસી સાંસ્કૃતિક ઉત્સવ છે. બ્રિટિશ કાળથી (૧૮૪૨થી) શરૂ થયેલી પરંપરા અનુસાર ડાંગના પાંચ આદિવાસી રાજાઓ (ગઢવી, દહેર, આમલા, વાસુર્ણા અને પિમ્પરી)નું સરકાર દ્વારા વાર્ષિક સાલિયાણું (Political Pension) આપીને જાહેર સન્માન કરવામાં આવે છે. આ ઉત્સવમાં હજારો આદિવાસીઓ પરંપરાગત વસ્ત્રોમાં કહાળિયા અને તડપું વાજિંત્રો સાથે વાઘ્યા નૃત્ય, ઠાકર્યા નૃત્ય અને ડાંગી લોકનૃત્યો રજૂ કરે છે.",
        "short_answer_gu": "આહવા (ડાંગ)માં હોળી સમયે યોજાતો ઐતિહાસિક ઉત્સવ, જ્યાં ડાંગના પાંચ આદિવાસી રાજાઓનું સન્માન અને પરંપરાગત નૃત્યો થાય છે.",
        "short_answer_en": "Dang Darbar is a historic tribal gathering held in Ahwa before Holi where the five tribal Rajas of Dang are honored alongside vibrant tribal folk dances.",
        "short_answer_hi": "डांग के अहवा में होली पर आयोजित डांग दरबार में पांच आदिवासी राजाओं का राजकीय सम्मान और पारंपरिक नृत्यों की प्रस्तुति होती है।",
        "keywords": ["Dang Darbar", "Ahwa", "Dang Rajas", "Tribal Festival", "Holi", "Kahaliya", "ડાંગ દરબાર", "આહવા", "આદિવાસી ઉત્સવ"],
        "source": "Gujarat Tourism / District Administration Dang",
        "source_type": "Tribal Heritage Festival",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "fest_09",
        "category": "Festivals",
        "title": "મોઢેરા ઉત્તરાર્ધ નૃત્ય મહોત્સવ (Modhera Dance Festival - Uttarardh Mahotsav)",
        "title_en": "Modhera Dance Festival",
        "district": "Mehsana",
        "question_gu": "મોઢેરા સૂર્ય મંદિર ખાતે યોજાતા ઉત્તરાર્ધ શાસ્ત્રીય નૃત્ય મહોત્સવ વિશે જણાવો.",
        "question_hi": "मोढेरा सूर्य मंदिर में आयोजित उत्तरार्ध शास्त्रीय नृत्य महोत्सव के बारे में बताएं।",
        "question_mr": "मोढेरा शास्त्रीय नृत्य महोत्सवाविषयी सांगा.",
        "question_en": "Tell me about the annual Modhera Classical Dance Festival (Uttarardh Mahotsav).",
        "question_roman_gu": "Modhera Uttarardh classical dance festival vishe janavo.",
        "answer_gu": "મોઢેરા નૃત્ય મહોત્સવ (ઉત્તરાર્ધ મહોત્સવ) દર વર્ષે જાન્યુઆરી મહિનાના ત્રીજા સપ્તાહમાં (ઉત્તરાયણ પછી) મહેસાણા જિલ્લાના ૧૧મી સદીના ઐતિહાસિક મોઢેરા સૂર્ય મંદિરના પરિસરમાં ગુજરાત પ્રવાસન નિગમ દ્વારા યોજવામાં આવે છે. સૂર્યદેવ જ્યારે ઉત્તર તરફ પ્રયાણ કરે છે તે ઉત્તરાર્ધ કાળની ઉજવણી રૂપે આ ત્રિદિવસીય મહોત્સવ થાય છે. રાત્રિના સમયે રોશનીથી ઝળહળતા સૂર્ય મંદિરના રંગમંડપ અને સૂર્યકુંડના પૃષ્ઠભૂમિમાં દેશના શ્રેષ્ઠ શાસ્ત્રીય કલાકારો ભરતનાટ્યમ, કથક, ઓડિસી, કુચીપુડી અને મોહિનીઅટ્ટમ નૃત્યો રજૂ કરે છે.",
        "short_answer_gu": "મોઢેરા સૂર્ય મંદિર ખાતે જાન્યુઆરીમાં યોજાતો ભવ્ય રાષ્ટ્રીય શાસ્ત્રીય નૃત્ય મહોત્સવ.",
        "short_answer_en": "Modhera Dance Festival (Uttarardh Mahotsav) is a prestigious 3-day classical dance festival held every January against the illuminated backdrop of the Sun Temple.",
        "short_answer_hi": "मोढेरा सूर्य मंदिर की पृष्ठभूमि में जनवरी में आयोजित उत्तरार्ध महोत्सव देश के शीर्ष शास्त्रीय नृत्य समारोहों में से एक है।",
        "keywords": ["Modhera Dance Festival", "Uttarardh Mahotsav", "Sun Temple", "Classical Dance", "Mehsana", "મોઢેરા નૃત્ય મહોત્સવ", "ઉત્તરાર્ધ મહોત્સવ", "શાસ્ત્રીય નૃત્ય"],
        "source": "Tourism Corporation of Gujarat Limited (TCGL)",
        "source_type": "Official Cultural Festival",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "fest_10",
        "category": "Festivals",
        "title": "ચિત્ર વિચિત્ર મેળો (Chitra Vichitra Fair Gunbhakhari)",
        "title_en": "Chitra Vichitra Fair",
        "district": "Sabarkantha (Khedbrahma)",
        "question_gu": "સાબરકાંઠાના ગુણભાખરી ખાતે ભરાતા ચિત્ર વિચિત્ર મેળા વિશે જણાવો.",
        "question_hi": "साबरकांठा के गुणभाखरी में आयोजित चित्र विचित्र मेले के बारे में बताएं।",
        "question_mr": "चित्र विचित्र जत्रेविषयी माहिती द्या.",
        "question_en": "Tell me about the unique Chitra Vichitra tribal fair held at Gunbhakhari.",
        "question_roman_gu": "Sabarkantha Gunbhakhari Chitra Vichitra melo vishe janavo.",
        "answer_gu": "ચિત્ર વિચિત્ર મેળો સાબરકાંઠા જિલ્લાના પોશીના/ખેડબ્રહ્મા નજીક ગુણભાખરી ગામે ત્રણ નદીઓના સંગમ (સાબરમતી, આકળ અને વ્યાકળ) પર હોળીના ૧૪ દિવસ પછી (ચૈત્ર વદ અમાસે) ભરાતો આદિવાસીઓનો સૌથી મોટો મેળો છે. મહાભારત કાળના રાજા શાંતનુના પુત્રો ચિત્રવીર્ય અને વિચિત્રવીર્યના પ્રાયશ્ચિત અને મુક્તિ સાથે આ સ્થળ જોડાયેલું છે. મેળો પ્રથમ દિવસે પૂર્વજોના અસ્થિ વિસર્જન અને વિલાપથી શરૂ થાય છે અને બીજા દિવસે રંગબેરંગી પરંપરાગત વસ્ત્રો, ઢોલના તાલ અને ઉત્સાહપૂર્ણ આદિવાસી રાસ-મેળામાં ફેરવાઈ જાય છે.",
        "short_answer_gu": "ગુણભાખરીમાં ત્રિવેણી સંગમે હોળી પછી ભરાતો આદિવાસી મેળો, જે પિતૃતર્પણ અને અનોખી લોકસંસ્કૃતિ માટે જાણીતો છે.",
        "short_answer_en": "Chitra Vichitra Fair in Gunbhakhari is a major tribal gathering at the confluence of three rivers, combining ancestral remembrance with vibrant celebration.",
        "short_answer_hi": "साबरकांठा के गुणभाखरी में तीन नदियों के संगम पर लगने वाला चित्र विचित्र मेला आदिवासियों की अनूठी सांस्कृतिक धरोहर है।",
        "keywords": ["Chitra Vichitra Fair", "Gunbhakhari", "Sabarkantha", "Tribal Fair", "Chitravirya", "ચિત્ર વિચિત્ર મેળો", "ગુણભાખરી", "સાબરકાંઠા"],
        "source": "Gujarat Tourism",
        "source_type": "Tribal Folk Fair",
        "source_url": "https://www.gujarattourism.com"
    },

    # -------------------------------------------------------------------------
    # ADDITIONAL CUISINE, SNACKS & BEVERAGES (79-88)
    # -------------------------------------------------------------------------
    {
        "id": "food_13",
        "category": "Gujarati Cuisine",
        "title": "અમદાવાદી દાળવડા (Amdavadi Dalwada - Moong Dal Fritters)",
        "title_en": "Amdavadi Dalwada",
        "district": "Ahmedabad",
        "question_gu": "અમદાવાદના પ્રખ્યાત દાળવડા અને ચોમાસાની પરંપરા વિશે જણાવો.",
        "question_hi": "अहमदाबाद के प्रसिद्ध दालवड़ा और मानसून की परंपरा के बारे में बताएं।",
        "question_mr": "अहमदाबादी डाळवडे याविषयी सांगा.",
        "question_en": "Tell me about Ahmedabad's iconic Dalwada and its monsoon connection.",
        "question_roman_gu": "Ahmedabad na Dalwada ane chomasu vishe janavo.",
        "answer_gu": "અમદાવાદી દાળવડા એ મગની ફોતરાવાળી દાળમાંથી બનતું અતિ ક્રિસ્પી, મસાલેદાર અને ગરમાગરમ તળેલું ફરસાણ છે. મગની દાળને પલાળીને કરકરી વાટી તેમાં પુષ્કળ લીલાં મરચાં, આદુ, હિંગ, કાળા મરી અને મીઠું ઉમેરીને તેલમાં કુરકુરા તળવામાં આવે છે. અમદાવાદમાં ચોમાસામાં વરસાદ પડતાં જ દાળવડાની દુકાનો બહાર સેંકડો મીટર લાંબી લાઈનો લાગે છે. ગરમાગરમ દાળવડાને ઝીણી સમારેલી કાચી ડુંગળી અને તળેલાં તીખાં લીલાં મરચાં સાથે ખાવાની ખાસ મજા છે.",
        "short_answer_gu": "ચોમાસામાં અમદાવાદનું સૌથી પ્રિય તીખું-ક્રિસ્પી ફરસાણ, જે મગની દાળ, આદુ-મરચાં અને ડુંગળી સાથે ખવાય છે.",
        "short_answer_en": "Amdavadi Dalwada are crispy, spicy golden fritters made from coarsely ground green moong dal, a quintessential monsoon craving in Ahmedabad.",
        "short_answer_hi": "अहमदाबाद में बारिश के मौसम में मूंग की दाल से बने कुरकुरे और तीखे दालवड़े प्याज व हरी मिर्च के साथ बेहद चाव से खाए जाते हैं।",
        "keywords": ["Dalwada", "Ahmedabad", "Moong Dal", "Monsoon Snack", "Green Chillies", "દાળવડા", "અમદાવાદ", "મગની દાળ", "ચોમાસું"],
        "source": "Ahmedabad Street Food Culture",
        "source_type": "Regional Street Food Icon",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_14",
        "category": "Gujarati Cuisine",
        "title": "ભાવનગરી ગાંઠિયા અને વણેલા ગાંઠિયા (Bhavnagari Ganthiya)",
        "title_en": "Bhavnagari Ganthiya",
        "district": "Bhavnagar / Rajkot",
        "question_gu": "ભાવનગરી ગાંઠિયા અને વણેલા ગાંઠિયાની વિશેષતા શું છે?",
        "question_hi": "भावनगरी गांठिया और वणेला गांठिया की क्या विशेषता है?",
        "question_mr": "भावनगरी गाठिया याविषयी माहिती द्या.",
        "question_en": "What makes Bhavnagari Ganthiya and Vanela Ganthiya so famous?",
        "question_roman_gu": "Bhavnagari Ganthiya ane Vanela Ganthiya vishe janavo.",
        "answer_gu": "ભાવનગરી ગાંઠિયા એ ચણાના લોટ (બેસન), અજમો, કાળા મરી, તેલ અને પાપડખારાના મિશ્રણમાંથી બનતું અત્યંત પોચું અને મુલાયમ ફરસાણ છે જે મોઢામાં મૂકતાં જ ઓગળી જાય છે. ભાવનગરનું પાણી અને કારીગરોની હથેળીથી વણવાની કળા (વણેલા ગાંઠિયા) તેને અજોડ સ્વાદ આપે છે. સૌરાષ્ટ્રમાં સવારનો નાસ્તો ગરમાગરમ ગાંઠિયા, તળેલી કઢી, પપૈયાનો સંભારો, તળેલાં મરચાં અને ગરમ ચા વગર અધૂરો માનવામાં આવે છે. ભાવનગરના ગાંઠિયાને જીઆઈ ટેગની શ્રેણીમાં પણ અગ્રણી સ્થાન મળેલું છે.",
        "short_answer_gu": "ભાવનગરનું વિશ્વપ્રસિદ્ધ મુલાયમ બેસનનું ફરસાણ, જે સવારે કઢી, સંભારો અને મરચાં સાથે નાસ્તામાં ખવાય છે.",
        "short_answer_en": "Bhavnagari Ganthiya are ultra-soft, melt-in-mouth spiced gram flour strings that form the cornerstone of Saurashtra's morning breakfast.",
        "short_answer_hi": "भावनगर का गांठिया बेसन, काली मिर्च और अजवाइन से बना बेहद कोमल और लोकप्रिय नाश्ता है।",
        "keywords": ["Bhavnagari Ganthiya", "Vanela Ganthiya", "Bhavnagar", "Besan", "Farsan", "Sambharo", "ગાંઠિયા", "ભાવનગરી ગાંઠિયા", "વણેલા ગાંઠિયા"],
        "source": "Farsan Heritage of Gujarat",
        "source_type": "Iconic Farsan",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_15",
        "category": "Gujarati Cuisine",
        "title": "મહુડીની સુખડી (Sukhdi of Mahudi Jain Tirth)",
        "title_en": "Sukhdi of Mahudi",
        "district": "Gandhinagar (Mahudi)",
        "question_gu": "મહુડી ઘંટાકર્ણ મહાવીર જૈન તીર્થ અને સુખડીના પ્રસાદનો નિયમ જણાવો.",
        "question_hi": "महुडी घंटाकर्ण महावीर जैन तीर्थ और सुखड़ी प्रसाद के नियम बताएं।",
        "question_mr": "महुडी येथील सुखडीच्या प्रसादाविषयी सांगा.",
        "question_en": "Tell me about the famous Sukhdi prasad of Mahudi Ghantakarna Mahavir Jain temple.",
        "question_roman_gu": "Mahudi ni Sukhdi ane Ghantakarna Mahavir vishe janavo.",
        "answer_gu": "મહુડી ગુજરાતના ગાંધીનગર જિલ્લાના માણસા તાલુકામાં સાબરમતી નદીના કિનારે આવેલું સુપ્રસિદ્ધ જૈન તીર્થ છે, જે શ્રી ઘંટાકર્ણ મહાવીર દેવ માટે જાણીતું છે. મહુડીની 'સુખડી' (ઘઉંનો લોટ, શુદ્ધ દેશી ઘી અને ઓર્ગેનિક ગોળમાંથી બનતી ગરમાગરમ મિઠાઈ) વિશ્વભરમાં પ્રખ્યાત છે. આ પ્રસાદનો એક અપરિવર્તનીય ચમત્કારિક નિયમ છે કે સુખડીનો પ્રસાદ માત્ર મંદિર પરિસરની અંદર જ આરોગી શકાય છે, કોઈપણ ભક્ત એક નાનો ટુકડો પણ મંદિર પરિસરની બહાર લઈ જઈ શકતો નથી.",
        "short_answer_gu": "મહુડી જૈન તીર્થમાં ઘી, ગોળ અને ઘઉંમાંથી બનતી સુખડી, જે મંદિર પરિસરની બહાર લઈ જઈ શકાતી નથી.",
        "short_answer_en": "Sukhdi is a warm fudge made of wheat flour, pure ghee, and jaggery served as holy prasad at Mahudi Jain Tirth, strictly prohibited from being taken outside temple premises.",
        "short_answer_hi": "गांधीनगर के महुडी तीर्थ में शुद्ध घी और गुड़ से बनी सुखड़ी का प्रसाद प्रसिद्ध है जिसे मंदिर परिसर से बाहर ले जाना वर्जित है।",
        "keywords": ["Mahudi", "Sukhdi", "Ghantakarna Mahavir", "Gandhinagar", "Prasad", "Jain Tirth", "મહુડી", "સુખડી", "ઘંટાકર્ણ મહાવીર"],
        "source": "Mahudi Jain Devasthan Trust / Gujarat Tourism",
        "source_type": "Sacred Temple Sweet Tradition",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_16",
        "category": "Gujarati Cuisine",
        "title": "પાત્રા અને મુઠિયાં (Patra and Muthia - Steamed Delicacies)",
        "title_en": "Patra and Muthia",
        "district": "All Gujarat",
        "question_gu": "અળવીના પાનના પાત્રા અને મુઠિયાં કેવી રીતે બને છે?",
        "question_hi": "अरबी के पत्तों के पात्रा और मुठिया कैसे बनते हैं?",
        "question_mr": "अळूची वडी (पात्रा) आणि मुठिया याविषयी सांगा.",
        "question_en": "How are Patra (colocasia leaf rolls) and Muthia prepared in Gujarati cuisine?",
        "question_roman_gu": "Alvi na paan na Patra ane Muthia kevi rite bane chhe?",
        "answer_gu": "પાત્રા અને મુઠિયાં ગુજરાતના અત્યંત પૌષ્ટિક અને લોકપ્રિય બાફેલાં ફરસાણ છે: ૧) પાત્રા અળવીના લીલાં મોટાં પાન પર ચણાનો લોટ (બેસન), આંબલીનો પલ્પ, ગોળ, આદુ-મરચાં અને મસાલાનો પેસ્ટ લગાવી, રોલ વાળીને વરાળમાં બાફી, ગોળ ટુકડા કાપીને તલ-રાઈના વઘારમાં સાંતળીને બનાવાય છે. ૨) મુઠિયાં ઘઉંના કરકરા લોટ અથવા ચણાના લોટમાં તાજી મેથી, દૂધી કે પાલક, મસાલા અને તેલ મેળવીને મુઠ્ઠી વાળીને વરાળમાં બાફી, રાઈ-તલનો વઘાર કરીને ગરમ ચા કે ચટણી સાથે પીરસાય છે.",
        "short_answer_gu": "અળવીના પાનમાંથી બનતાં ખાટાં-મીઠાં પાત્રા અને મેથી-દૂધીમાંથી બનતાં વરાળમાં બાફેલાં સ્વાદિષ્ટ મુઠિયાં.",
        "short_answer_en": "Patra (spiced colocasia leaf rolls) and Muthia (steamed fenugreek or bottle gourd dumplings) are healthy, tempered traditional Gujarati snacks.",
        "short_answer_hi": "अरबी के पत्तों से बने पात्रा और मेथी/लौकी से बने मुठिया भाप में पकाए जाने वाले पौष्टिक गुजराती फरसाण हैं।",
        "keywords": ["Patra", "Muthia", "Colocasia Leaves", "Methi Muthia", "Steamed Farsan", "પાત્રા", "મુઠિયાં", "અળવીના પાન"],
        "source": "Traditional Gujarati Food Culture",
        "source_type": "Healthy Steamed Farsan",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "food_17",
        "category": "Gujarati Cuisine",
        "title": "સેવ ખમણી અને સેવ ઉસળ (Sev Khamani & Sev Usal)",
        "title_en": "Sev Khamani and Sev Usal",
        "district": "Surat / Vadodara",
        "question_gu": "સુરતની સેવ ખમણી અને વડોદરાનું સેવ ઉસળ જણાવો.",
        "question_hi": "सूरत की सेव खमणी और वडोदरा का सेव उसल बताएं।",
        "question_mr": "सुरतची सेव खमणी आणि वडोदराचे सेव उसळ याविषयी सांगा.",
        "question_en": "Tell me about Surti Sev Khamani and Baroda's iconic Sev Usal.",
        "question_roman_gu": "Surat ni Sev Khamani ane Vadodara nu Sev Usal vishe janavo.",
        "answer_gu": "સેવ ખમણી અને સેવ ઉસળ ગુજરાતના બે શહેરોની આગવી ઓળખ છે: ૧) સુરતી સેવ ખમણી (અમીરી ખમણ) ચણાની દાળના ખમણને ચૂરો કરીને, તેમાં તેલ, રાઈ, હિંગ, આદુ, લીલાં લસણનો વઘાર કરી, દાડમના દાણા, કોપરાનું છીણ અને નાયલોન સેવ ભભરાવીને બનાવાતી ખાટી-મીઠી વાનગી છે. ૨) વડોદરાનું સેવ ઉસળ એ સૂકા લીલા વટાણાની અત્યંત તીખી-મસાલેદાર ગ્રેવી (તરી/ઉસળ) છે જેની ઉપર પુષ્કળ સેવ, ડુંગળી અને લીંબુ નાખીને પાંઉ સાથે ખાવામાં આવે છે.",
        "short_answer_gu": "સુરતની દાડમ-સેવવાળી સ્વાદિષ્ટ સેવ ખમણી અને વડોદરાનું તીખું-મસાલેદાર વટાણાનું સેવ ઉસળ.",
        "short_answer_en": "Surti Sev Khamani (crumbled spiced khaman with pomegranate and sev) and Baroda's Sev Usal (spicy dried-pea curry topped with sev and buns).",
        "short_answer_hi": "सूरत की सेव खमणी और वडोदरा का तीखा-चटपटा सेव उसल गुजरात के दो अलग-अलग शहरों के मशहूर व्यंजन हैं।",
        "keywords": ["Sev Khamani", "Sev Usal", "Surat", "Vadodara", "Street Food", "સેવ ખમણી", "સેવ ઉસળ", "સુરત", "વડોદરા"],
        "source": "Regional Culinary Legends",
        "source_type": "City Street Food Icons",
        "source_url": "https://www.gujarattourism.com"
    },

    # -------------------------------------------------------------------------
    # ADDITIONAL FOLK CRAFTS & TRADITIONS (89-98)
    # -------------------------------------------------------------------------
    {
        "id": "craft_06",
        "category": "Handicrafts",
        "title": "માતાની પછેડી - અમદાવાદ (Mata ni Pachedi - Sacred Textile Art)",
        "title_en": "Mata ni Pachedi",
        "district": "Ahmedabad",
        "question_gu": "અમદાવાદની ૩૦૦ વર્ષ જૂની 'માતાની પછેડી' કળા અને જીઆઈ ટેગ વિશે જણાવો.",
        "question_hi": "अहमदाबाद की ३०० वर्ष पुरानी 'माता नी पछेड़ी' कला और जीआई टैग के बारे में बताएं।",
        "question_mr": "माता नी पछेडी या कापडी चित्रकलेविषयी माहिती द्या.",
        "question_en": "Tell me about Mata ni Pachedi, the 300-year-old sacred textile art of Ahmedabad.",
        "question_roman_gu": "Mata ni Pachedi Ahmedabad GI tag vishe janavo.",
        "answer_gu": "માતાની પછેડી (Mata ni Pachedi) એ અમદાવાદમાં સાબરમતી નદીના કિનારે વસતા વાઘરી/દેવીપૂજક સમુદાય દ્વારા ૩૦૦ વર્ષથી વધુ સમયથી સાચવી રખાયેલી પવિત્ર હસ્તચિત્રિત વસ્ત્રકળા છે, જેને 'ગુજરાતની કલમકારી' પણ કહેવામાં આવે છે. 'પછેડી'નો અર્થ પાછળ રાખવાનું વસ્ત્ર થાય છે. પ્રાચીન કાળમાં જ્યારે વંચિત સમુદાયોને મંદિરમાં પ્રવેશ ન હતો, ત્યારે તેમણે સુતરાઉ કાપડ પર વાંસની કલમ અને લાકડાના બ્લોક વડે કુદરતી રંગો (લાલ, કાળો, સફેદ)થી મા આદ્યશક્તિના સ્વરૂપો, વાહનો અને પૌરાણિક કથાઓ દોરીને હરતા-ફરતા મંદિરનું સર્જન કર્યું હતું. તેને જીઆઈ ટેગ (GI Tag) પ્રાપ્ત છે.",
        "short_answer_gu": "અમદાવાદની ૩૦૦ વર્ષ જૂની જીઆઈ ટેગ ધરાવતી પવિત્ર કાપડ ચિત્રકળા, જેને 'ગુજરાતની કલમકારી' કહેવામાં આવે છે.",
        "short_answer_en": "Mata ni Pachedi is a 300-year-old GI-tagged sacred textile art from Ahmedabad depicting Mother Goddess manifestations using bamboo pens and natural dyes.",
        "short_answer_hi": "अहमदाबाद की 'माता नी पछेड़ी' ३०० वर्ष पुरानी पवित्र वस्त्र चित्रकला है जिसे जीआई टैग प्राप्त है और 'गुजरात की कलमकारी' कहा जाता है।",
        "keywords": ["Mata ni Pachedi", "Sacred Textile", "Ahmedabad", "GI Tag", "Kalamkari", "માતાની પછેડી", "અમદાવાદ", "જીઆઈ ટેગ"],
        "source": "Geographical Indications Registry / Ministry of Textiles",
        "source_type": "GI Tagged Sacred Craft",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "craft_07",
        "category": "Handicrafts",
        "title": "તાંગલિયા શાલ - સુરેન્દ્રનગર (Tangaliya Shawl - Daana Weaving)",
        "title_en": "Tangaliya Shawl",
        "district": "Surendranagar",
        "question_gu": "સુરેન્દ્રનગરની તાંગલિયા શાલ અને 'દાણા' વણાટકામ વિશે જણાવો.",
        "question_hi": "सुरेंद्रनगर की तांगलिया शॉल और 'दाना' बुनाई के बारे में बताएं।",
        "question_mr": "तांगलिया शॉल आणि दाणा विणकामाविषयी सांगा.",
        "question_en": "What is the unique 700-year-old Tangaliya Shawl (Daana weaving) craft of Surendranagar?",
        "question_roman_gu": "Tangaliya Shawl Surendranagar Daana weaving vishe janavo.",
        "answer_gu": "તાંગલિયા શાલ એ સુરેન્દ્રનગર જિલ્લાના વઢવાણ, ચોટીલા અને ધ્રાંગધ્રા વિસ્તારમાં ડાંગસિયા સમુદાય દ્વારા ૭૦૦ વર્ષથી વણાતી વિશિષ્ટ શાલ છે. આ કળાની અનોખી ખાસિયત 'દાણા કામ' (Daana Weaving) છે, જેમાં વણકર વણાટ કરતી વખતે કાચા ઊન કે સુતરના નાના-નાના ગૂંચળા (દાણા) આંગળીના ટેરવે દોરામાં ગૂંથીને કાપડની સપાટી પર મોતી જેવા ઉપસેલા ભૌમિતિક આકારો સર્જે છે. તાંગલિયા શાલ, દુપટ્ટા અને ચણિયા વિશ્વભરમાં જાણીતાં છે અને તેને જીઆઈ ટેગ (GI Tag) પ્રાપ્ત છે.",
        "short_answer_gu": "સુરેન્દ્રનગરના ડાંગસિયા સમુદાય દ્વારા આંગળીના ટેરવે 'દાણા' ગૂંથીને બનતી ૭૦૦ વર્ષ જૂની જીઆઈ ટેગ શાલ.",
        "short_answer_en": "Tangaliya Shawl is a 700-year-old GI-tagged weaving craft from Surendranagar where raised dots ('Daana') are hand-twisted into geometric patterns.",
        "short_answer_hi": "सुरेंद्रनगर की तांगलिया शॉल ७०० वर्ष पुरानी जीआई टैग कला है जिसमें उंगलियों से 'दाना' गूंथकर ज्यामितीय डिजाइन बनाए जाते हैं।",
        "keywords": ["Tangaliya Shawl", "Daana Weaving", "Surendranagar", "Dangasia", "GI Tag", "તાંગલિયા શાલ", "દાણા કામ", "સુરેન્દ્રનગર"],
        "source": "Geographical Indications Registry / Ministry of Textiles",
        "source_type": "GI Tagged Textile Craft",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "craft_08",
        "category": "Handicrafts",
        "title": "ખંભાતનું અકીક કામ (Agate / Akik Stone Craft of Khambhat)",
        "title_en": "Khambhat Agate Craft",
        "district": "Anand (Khambhat)",
        "question_gu": "ખંભાતના અકીક ઉદ્યોગ અને રત્નકળાનો ઇતિહાસ જણાવો.",
        "question_hi": "खंभात के अकीक (एगेट) उद्योग और रत्न शिल्प का इतिहास बताएं।",
        "question_mr": "खंभातच्या अकीक दगडाच्या कलेविषयी सांगा.",
        "question_en": "Tell me about the ancient Agate (Akik) stone crafting industry of Khambhat.",
        "question_roman_gu": "Khambhat na Akik kaam vishe janavo.",
        "answer_gu": "અકીક (Agate) કામ એ ખંભાત (પ્રાચીન કેમ્બે) બંદરમાં હડપ્પન કાળથી (૪૦૦૦ વર્ષથી) ચાલી આવતી કિંમતી પથ્થર ઘસવાની અને આભૂષણ બનાવવાની ઐતિહાસિક કળા છે. નર્મદા અને મહી નદીની ખીણમાંથી મળતા અકીકના કાચા પથ્થરોને તડકામાં તપાવી, ગરમ કરી, ટીપીને અને ઘસીને ચળકતા મણકા, માળા, મોસ એગેટ અને સુશોભન વસ્તુઓ બનાવાય છે. મધ્યકાળમાં ખંભાતથી આખા વિશ્વમાં અકીકના મણકા નિકાસ થતા હતા. ખંભાતના અકીક ક્રાફ્ટને જીઆઈ ટેગ (GI Tag) મળેલો છે.",
        "short_answer_gu": "ખંભાતમાં હડપ્પન કાળથી અકીકના કુદરતી પથ્થરોને તપાવી-ઘસીને મણકા અને ઘરેણાં બનાવવાની જીઆઈ ટેગ કળા.",
        "short_answer_en": "Khambhat Agate Craft is a 4,000-year-old GI-tagged gemstone craft where natural agate stones are baked, chiseled, and polished into shining beads.",
        "short_answer_hi": "खंभात का अकीक उद्योग हड़प्पा काल से प्रसिद्ध है जहाँ प्राकृतिक पत्थरों को तराशकर मनके और आभूषण बनाए जाते हैं।",
        "keywords": ["Akik", "Agate", "Khambhat", "Cambay", "Gemstone Beads", "GI Tag", "અકીક", "ખંભાત", "જીઆઈ ટેગ"],
        "source": "Geographical Indications Registry",
        "source_type": "GI Tagged Craft Heritage",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "craft_09",
        "category": "Handicrafts",
        "title": "કચ્છી એમ્બ્રોઈડરી અને ભરતકામ (Kutch Embroidery - Rabari & Mutwa Styles)",
        "title_en": "Kutch Embroidery",
        "district": "Kutch",
        "question_gu": "કચ્છના રબારી, આહીર અને મુતવા સમુદાયના વિવિધ ભરતકામ વિશે જણાવો.",
        "question_hi": "कच्छ के रबारी, अहीर और मुतवा समुदायों की कढ़ाई (कशीदाकारी) के बारे में बताएं।",
        "question_mr": "कच्छच्या पारंपरिक भरतकामाविषयी सांगा.",
        "question_en": "Explain the distinct styles of Kutch embroidery including Rabari, Ahir, and Mutwa work.",
        "question_roman_gu": "Kutch nu Bharatkam ane embroidery vishe janavo.",
        "answer_gu": "કચ્છી ભરતકામ એ કચ્છના રબારી, આહીર, મુતવા, જાટ અને સોઢા રાજપૂત સમુદાયોની મહિલાઓ દ્વારા હાથથી થતું વિશ્વપ્રસિદ્ધ સુશોભન ભરતકામ છે. તેમાં આભલા (Mirrors), ચેઈન સ્ટીચ, હેરિંગબોન સ્ટીચ અને તેજસ્વી રેશમી દોરાઓથી મોર, પોપટ, ફૂલો અને ભૌમિતિક ભાત કંડારાય છે. રબારી ભરતમાં ત્રિકોણાકાર આભલા, આહીર ભરતમાં ગોળાકાર આભલા અને મુતવા ભરતમાં અતિ બારીક સુઈકામ પ્રમુખ છે. કચ્છી ભરતકામને જીઆઈ ટેગ (GI Tag) પ્રાપ્ત છે અને તે ચણિયા-ચોળી, તોરણ અને બેગમાં વિશ્વવ્યાપી ઓળખ ધરાવે છે.",
        "short_answer_gu": "કચ્છના વિવિધ સમુદાયો દ્વારા આભલા અને રંગીન દોરાથી હાથથી થતું જીઆઈ ટેગ ધરાવતું સુંદર ભરતકામ.",
        "short_answer_en": "Kutch Embroidery is a world-renowned GI-tagged needlecraft tradition featuring mirrorwork and vibrant silk threads practiced by Rabari, Ahir, and Mutwa women.",
        "short_answer_hi": "कच्छ की कशीदाकारी शीशे (आभला) और रंग-बिरंगे धागों से की जाने वाली विश्वप्रसिद्ध हस्तकला है जिसे जीआई टैग प्राप्त है।",
        "keywords": ["Kutch Embroidery", "Rabari Embroidery", "Ahir Work", "Mirrorwork", "GI Tag", "કચ્છી ભરતકામ", "આભલા", "રબારી ભરત"],
        "source": "Geographical Indications Registry / Gujarat Handicrafts",
        "source_type": "GI Tagged Folk Craft",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "craft_10",
        "category": "Handicrafts",
        "title": "કચ્છી કોપર બેલ અને લેધર ક્રાફ્ટ (Kutch Copper Bells & Leather Craft)",
        "title_en": "Kutch Copper Bells",
        "district": "Kutch (Zura & Hodka)",
        "question_gu": "કચ્છના ઝુરા ગામની કોપર બેલ (તાંબાની ઘંટડી) અને હોડકાના લેધર ક્રાફ્ટ વિશે જણાવો.",
        "question_hi": "कच्छ के जुरा गांव की कॉपर बेल और होड़का के लेदर क्राफ्ट के बारे में बताएं।",
        "question_mr": "कच्छच्या तांब्याच्या घंटा आणि लेदर क्राफ्टविषयी सांगा.",
        "question_en": "Tell me about traditional Kutch Copper Bells from Zura and Leather craft from Hodka.",
        "question_roman_gu": "Kutch Copper Bell Zura ane Hodka leather craft vishe janavo.",
        "answer_gu": "કચ્છના ઝુરા અને નિરોણા ગામમાં લુહાર મુસ્લિમ કારીગરો દ્વારા લોખંડ અને તાંબાના ભંગારમાંથી વેલ્ડિંગ કર્યા વિના હાથથી જોડીને, માટી અને તાંબાની ભસ્મમાં ભઠ્ઠીમાં તપાવીને 'કોપર બેલ' (તાંબાની ઘંટડીઓ) બનાવાય છે. લાકડાના લોલકથી વાગતી આ ઘંટડીઓ અત્યંત મધુર અને શાંત સૂર રેલાવે છે જે પ્રાચીન સમયમાં પશુઓના ગળામાં બાંધવામાં આવતી હતી. આ સાથે હોડકા ગામમાં આભલા અને ભરત ભરેલા કચ્છી ચામડાના પગરખાં (મોજડી), પાકીટ અને બેલ્ટ બનાવવાનું લેધર ક્રાફ્ટ પણ પ્રખ્યાત છે.",
        "short_answer_gu": "ઝુરા ગામમાં કોઈ વેલ્ડિંગ વગર બનતી મધુર રણકારવાળી તાંબાની ઘંટડીઓ અને હોડકાનું પરંપરાગત લેધરકામ.",
        "short_answer_en": "Kutch Copper Bells from Zura village are crafted without welding using copper coating, tuned for melodic chiming; Hodka is known for embroidered leather mojris.",
        "short_answer_hi": "कच्छ के जुरा गांव में बिना वेल्डिंग के तांबे की परत चढ़ाकर सुरीली घंटियां बनाई जाती हैं और होड़का चमड़े की जूतियों के लिए प्रसिद्ध है।",
        "keywords": ["Copper Bells", "Zura", "Kutch", "Leather Craft", "Hodka", "Mojri", "કોપર બેલ", "તાંબાની ઘંટડી", "હોડકા"],
        "source": "Gujarat Handicrafts Development Corporation",
        "source_type": "Folk Craft Heritage",
        "source_url": "https://www.gujarattourism.com"
    },

    # -------------------------------------------------------------------------
    # ADDITIONAL GEOGRAPHY, REGIONAL IDENTITY & LANGUAGE (99-106)
    # -------------------------------------------------------------------------
    {
        "id": "geo_06",
        "category": "Geography",
        "title": "ભાલ પ્રદેશ અને ભાલિયા ઘઉં (Bhal Region & Bhalia Wheat - GI Tag)",
        "title_en": "Bhal Region Bhalia Wheat",
        "district": "Ahmedabad / Bhavnagar (Bhal)",
        "question_gu": "ભાલ પ્રદેશ અને તેના મીઠા ભાલિયા ઘઉં (દાઉદખાની ઘઉં) વિશે જણાવો.",
        "question_hi": "भाल क्षेत्र और इसके मीठे भालिया गेहूं (जीआई टैग) के बारे में बताएं।",
        "question_mr": "भाल प्रदेश आणि भालिया गव्हाविषयी सांगा.",
        "question_en": "Tell me about the Bhal region of Gujarat and its GI-tagged sweet Bhalia wheat.",
        "question_roman_gu": "Bhal pradesh ane Bhalia ghau GI tag vishe janavo.",
        "answer_gu": "ભાલ પ્રદેશ ગુજરાતના ખંભાતના અખાત નજીક અમદાવાદ, ભાવનગર અને આણંદ જિલ્લા વચ્ચે ફેલાયેલો સપાટ કાંપાળ જમીનનો પ્રદેશ છે. આ વિસ્તાર તેના સુપ્રસિદ્ધ 'ભાલિયા ઘઉં' (દાઉદખાની ઘઉં) માટે વિશ્વવિખ્યાત છે, જેને જીઆઈ ટેગ (GI Tag) પ્રાપ્ત છે. ભાલિયા ઘઉંની અનોખી ખાસિયત એ છે કે તે ચોમાસાના સંગ્રહિત ભેજમાં કોઈપણ વધારાના સિંચાઈ કે ખાતર વગર કુદરતી રીતે પાકે છે. તેમાં પ્રોટીનનું પ્રમાણ વધુ હોય છે અને તે કુદરતી રીતે સ્વાદમાં મીઠા હોય છે, જેમાંથી સુજી, રવો અને પાસ્તા બને છે.",
        "short_answer_gu": "ભાલ વિસ્તારમાં કોઈપણ સિંચાઈ વિના ચોમાસાના ભેજમાં પાકતા કુદરતી મીઠા ભાલિયા ઘઉં, જે જીઆઈ ટેગ ધરાવે છે.",
        "short_answer_en": "Bhalia Wheat from Gujarat's Bhal region is a GI-tagged durum wheat grown rainfed without irrigation, renowned for high protein and natural sweetness.",
        "short_answer_hi": "भाल क्षेत्र में बिना सिंचाई के प्राकृतिक नमी से पैदा होने वाला भालिया गेहूं अपनी मिठास और जीआई टैग के लिए जाना जाता है।",
        "keywords": ["Bhalia Wheat", "Bhal Region", "GI Tag", "Daudkhani", "Ahmedabad", "Bhavnagar", "ભાલિયા ઘઉં", "ભાલ પ્રદેશ", "જીઆઈ ટેગ"],
        "source": "Geographical Indications Registry / Agriculture Department of Gujarat",
        "source_type": "GI Tagged Agricultural Heritage",
        "source_url": "https://agri.gujarat.gov.in"
    },
    {
        "id": "geo_07",
        "category": "Geography",
        "title": "ચરોતર પ્રદેશ - સોનેરી પાનનો મુલક (Charotar Region - Golden Leaf Land)",
        "title_en": "Charotar Region",
        "district": "Anand / Kheda",
        "question_gu": "ચરોતર પ્રદેશને 'સોનેરી પાનનો મુલક' કેમ કહેવાય છે?",
        "question_hi": "चरोतर क्षेत्र को 'सुनहरे पत्तों की भूमि' क्यों कहा जाता है?",
        "question_mr": "चरोतर प्रदेशाविषयी सांगा.",
        "question_en": "Why is the Charotar region (Anand/Kheda) called the 'Land of Golden Leaf'?",
        "question_roman_gu": "Charotar pradesh ne soneri paan no mulak kem kahevaay chhe?",
        "answer_gu": "ચરોતર પ્રદેશ મધ્ય ગુજરાતના મહી અને વાત્રક/શેઢી નદીઓ વચ્ચે આવેલા આણંદ અને ખેડા જિલ્લાનો અત્યંત ફળદ્રુપ વિસ્તાર છે. 'ચરોતર' શબ્દ 'ચારુતર' (અતિ સુંદર) પરથી આવ્યો છે. આ વિસ્તારમાં તમાકુ (તંબાકુ)નો વિપુલ પાક થતો હોવાથી તેના પાકેલાં પીળાં પાંદડાં સોના જેવાં ચમકતાં હોવાથી તેને 'સોનેરી પાનનો મુલક' કહેવામાં આવે છે. ચરોતર પ્રદેશ સરદાર વલ્લભભાઈ પટેલની જન્મભૂમિ છે અને તે કેળવણી (વલ્લભ વિદ્યાનગર) તથા અમૂલ શ્વેત ક્રાંતિનું વડુંમથક છે.",
        "short_answer_gu": "આણંદ-ખેડાનો ફળદ્રુપ વિસ્તાર જે તમાકુના પાકને કારણે 'સોનેરી પાનનો મુલક' કહેવાય છે અને સરદાર પટેલનું વતન છે.",
        "short_answer_en": "Charotar in Anand-Kheda is called the 'Land of Golden Leaf' due to its rich tobacco farming; it is the homeland of Sardar Patel and cradle of Amul.",
        "short_answer_hi": "आनंद और खेड़ा का उपजाऊ चरोतर क्षेत्र तंबाकू की खेती के कारण 'सुनहरे पत्तों की भूमि' कहलाता है और सरदार पटेल का गृहक्षेत्र है।",
        "keywords": ["Charotar", "Anand", "Kheda", "Golden Leaf", "Tobacco", "Sardar Patel", "ચરોતર", "સોનેરી પાન", "આણંદ"],
        "source": "State Gazetteer of Gujarat",
        "source_type": "Regional Geographic & Cultural Profile",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "geo_08",
        "category": "Geography",
        "title": "સાબરમતી અને તાપી નદીઓ (Sabarmati & Tapi Rivers)",
        "title_en": "Sabarmati and Tapi Rivers",
        "district": "Ahmedabad / Surat",
        "question_gu": "સાબરમતી અને તાપી નદીઓનું ગુજરાતમાં મહત્વ જણાવો.",
        "question_hi": "साबरमती और तापी नदियों का गुजरात में महत्व बताएं।",
        "question_mr": "साबरमती आणि तापी नद्यांविषयी सांगा.",
        "question_en": "Explain the historical and economic importance of the Sabarmati and Tapi rivers in Gujarat.",
        "question_roman_gu": "Sabarmati ane Tapi nadio nu Gujarat ma mahatva janavo.",
        "answer_gu": "સાબરમતી અને તાપી ગુજરાતની બે અત્યંત મહત્વપૂર્ણ ઐતિહાસિક નદીઓ છે: ૧) સાબરમતી નદી રાજસ્થાનના અરવલ્લી પર્વતોમાંથી નીકળી અમદાવાદ અને ગાંધીનગર થઈને ખંભાતના અખાતને મળે છે; તેના કિનારે મહાત્મા ગાંધીએ સાબરમતી આશ્રમ સ્થાપ્યો હતો અને અમદાવાદમાં વિશ્વપ્રસિદ્ધ 'સાબરમતી રિવરફ્રન્ટ' નિર્મિત છે. ૨) તાપી નદી (સૂર્યપુત્રી) મધ્યપ્રદેશના બેતુલમાંથી નીકળી સુરત શહેરની મધ્યમાંથી વહીને અરબી સમુદ્રને મળે છે; તેના પર ઉકાઈ ડેમ આવેલો છે અને સુરતનો ઐતિહાસિક હીરા-કાપડ ઉદ્યોગ તેના તટે વિકસ્યો છે.",
        "short_answer_gu": "અમદાવાદની ઓળખ સમાન સાબરમતી નદી (રિવરફ્રન્ટ/ગાંધી આશ્રમ) અને સુરતની જીવનરેખા તાપી નદી (સૂર્યપુત્રી/ઉકાઈ ડેમ).",
        "short_answer_en": "Sabarmati flows through Ahmedabad hosting Gandhi Ashram and the Riverfront; Tapi flows through Surat powering its textile hub via Ukai Dam.",
        "short_answer_hi": "अहमदाबाद की साबरमती नदी (गांधी आश्रम, रिवरफ्रंट) और सूरत की तापी नदी (सूर्यपुत्री) गुजरात के विकास की प्रमुख नदियां हैं।",
        "keywords": ["Sabarmati", "Tapi", "Riverfront", "Surat", "Ahmedabad", "Ukai Dam", "સાબરમતી", "તાપી", "રિવરફ્રન્ટ"],
        "source": "Water Resources Department, Govt of Gujarat",
        "source_type": "Major Rivers of Gujarat",
        "source_url": "https://guj-nwrws.gujarat.gov.in"
    },
    {
        "id": "cult_01",
        "category": "Gujarati Culture",
        "title": "ગુજરાતી ભાષા અને બોલીઓ (Gujarati Language & Regional Dialects)",
        "title_en": "Gujarati Language & Dialects",
        "district": "All Gujarat",
        "question_gu": "ગુજરાતી ભાષાની ઉત્પત્તિ અને તેની પ્રમુખ બોલીઓ (સુરતી, કાઠિયાવાડી, ચરોતરી, કચ્છી) જણાવો.",
        "question_hi": "गुजराती भाषा की उत्पत्ति और इसकी प्रमुख बोलियां बताएं।",
        "question_mr": "गुजराती भाषा आणि तिच्या बोलींविषयी सांगा.",
        "question_en": "Explain the origin of Gujarati language and its distinct regional dialects.",
        "question_roman_gu": "Gujarati bhasha ane bolio Surti Kathiyawadi Charotari Kutchi vishe janavo.",
        "answer_gu": "ગુજરાતી ભાષા ઈન્ડો-આર્યન ભાષા કુટુંબની સમૃદ્ધ ભાષા છે, જેનો ઉદ્ભવ ગુર્જર અપભ્રંશમાંથી ૧૨મી સદી આસપાસ થયો હતો. ગુજરાતી લિપિ નાગરી લિપિમાંથી શિરોરેખા (ઉપરની આડી લીટી) મુક્ત થઈને બની છે. ગુજરાતમાં મુખ્ય ચાર પ્રાદેશિક બોલીઓ બોલાય છે: ૧) કાઠિયાવાડી બોલી (સૌરાષ્ટ્રની રણકાદાર અને મીઠી બોલી - 'બાપા', 'ભાયલા'), ૨) સુરતી બોલી (દક્ષિણ ગુજરાતની લહેકાવાળી સંગીતમય બોલી), ૩) ચરોતરી/પટ્ટણી બોલી (મધ્ય અને ઉત્તર ગુજરાતની ઝડપી બોલી - 'ચ્યમ'), ૪) કચ્છી ભાષા (સિંધુ અને રાજસ્થાની પ્રભાવ ધરાવતી આગવી ભાષા). ગુજરાતી ભાષાના ગૌરવ માટે કહેવાયું છે: 'જ્યાં જ્યાં વસે એક ગુજરાતી, ત્યાં ત્યાં સદાકાળ ગુજરાત!'.",
        "short_answer_gu": "ગુર્જર અપભ્રંશમાંથી ઉતરી આવેલી ભાષા, જેમાં કાઠિયાવાડી, સુરતી, ચરોતરી અને કચ્છી જેવી મધુર પ્રાદેશિક બોલીઓ છે.",
        "short_answer_en": "Gujarati evolved from Gurjar Apabhramsha in the 12th century; it is spoken through rich dialects like Kathiyawadi, Surti, Charotari, and Kutchi.",
        "short_answer_hi": "१२वीं सदी में गुर्जर अपभ्रंश से विकसित गुजराती भाषा अपनी काठियावाड़ी, सूरती, चरोतरी और कच्छी बोलियों के लिए प्रसिद्ध है।",
        "keywords": ["Gujarati Language", "Dialects", "Kathiyawadi", "Surti", "Charotari", "Kutchi", "ગુજરાતી ભાષા", "બોલીઓ", "કાઠિયાવાડી", "સુરતી"],
        "source": "Gujarat Sahitya Academy / Linguistic Survey of India",
        "source_type": "Linguistic Heritage",
        "source_url": "https://gujaratisahityaparishad.com"
    },
    {
        "id": "cult_02",
        "category": "Gujarati Culture",
        "title": "ગુજરાતી લગ્ન પરંપરા અને રીતરિવાજો (Gujarati Wedding Traditions - Pithi, Mameru)",
        "title_en": "Gujarati Wedding Traditions",
        "district": "All Gujarat",
        "question_gu": "ગુજરાતી લગ્નના મુખ્ય રીતરિવાજો જેવા કે પીઠી, મામેરું, જાન અને હસ્તમેળાપ જણાવો.",
        "question_hi": "गुजराती विवाह की प्रमुख रस्में जैसे पीठी, मामेरु और हस्तमिलाप के बारे में बताएं।",
        "question_mr": "गुजराती लग्न परंपरा आणि चालीरीती याविषयी सांगा.",
        "question_en": "Explain the colorful customs of a traditional Gujarati wedding (Pithi, Mameru, Hastamelap).",
        "question_roman_gu": "Gujarati lagna parampara Pithi Mameru Hastamelap vishe janavo.",
        "answer_gu": "ગુજરાતી લગ્ન એ ઉત્સાહ, પારિવારિક સ્નેહ અને સાંસ્કૃતિક વિધિઓથી ભરપૂર મંગલ ઉત્સવ છે. લગ્ન પૂર્વે 'ચાંદલો-માટલી' (સગાઈ), ગણેશ સ્થાપના અને મંડપ મુહૂર્ત થાય છે. વર-કન્યાને હળદર અને ચંદનનો લેપ લગાવવાની 'પીઠી' વિધિ થાય છે. મોસાળ પક્ષ તરફથી કન્યા માટે વસ્ત્રો અને ઘરેણાં લાવવાની 'મામેરું / મોસાળું' વિધિ અત્યંત ભાવુક હોય છે. લગ્નના દિવસે વરરાજાનું 'પોંખણું' (સાસુ દ્વારા સંબેલું, રવૈયો અને ત્રાકથી સ્વાગત), ચાર મંગળ ફેરા, હસ્તમેળાપ, કન્યાદાન અને છેલ્લે રમૂજી 'કોડા-કોડી'ની રમત રમાય છે.",
        "short_answer_gu": "પીઠી, મામેરું, પોંખણું, મંગળ ફેરા અને હસ્તમેળાપ જેવા પવિત્ર અને ઉત્સાહસભર પારંપરિક રીતરિવાજો ધરાવતો લગ્ન ઉત્સવ.",
        "short_answer_en": "A traditional Gujarati wedding features vibrant ceremonies like Pithi (haldi), Mameru (maternal gifts), Ponkhana (groom welcome), and four Mangal Pheras.",
        "short_answer_hi": "गुजराती विवाह पीठी, मामेरु, पोंखणा और चार मंगल फेरों जैसी सांस्कृतिक और पारिवारिक रस्मों से संपन्न होता है।",
        "keywords": ["Gujarati Wedding", "Pithi", "Mameru", "Ponkhana", "Mangal Phera", "Marriage Customs", "ગુજરાતી લગ્ન", "પીઠી", "મામેરું", "પોંખણું"],
        "source": "Cultural Heritage of Gujarat",
        "source_type": "Social & Cultural Traditions",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "cult_03",
        "category": "Gujarati Culture",
        "title": "પરંપરાગત પોશાક - ચણિયા-ચોળી, કેડિયું અને સાફો (Traditional Gujarati Attire)",
        "title_en": "Traditional Gujarati Attire",
        "district": "All Gujarat",
        "question_gu": "ગુજરાતના પરંપરાગત પોશાક ચણિયા-ચોળી, કેડિયું અને પાઘડી વિશે જણાવો.",
        "question_hi": "गुजरात के पारंपरिक परिधान चनिया-चोली, केडिया और पगड़ी के बारे में बताएं।",
        "question_mr": "गुजराती पारंपरिक पोशाख चनिया-चोली आणि केडियाविषयी सांगा.",
        "question_en": "Describe traditional Gujarati clothing including Chaniya Choli, Kedia, and Pheta.",
        "question_roman_gu": "Gujarati traditional dress Chaniya Choli Kediyu Paghdi vishe janavo.",
        "answer_gu": "ગુજરાતનો પરંપરાગત પોશાક તેના રંગબેરંગી ભરતકામ, આભલા અને બાંધણી માટે વિશ્વવિખ્યાત છે: ૧) સ્ત્રીઓ માટે 'ચણિયા-ચોળી' (ઘેરદાર ઘાઘરો, ભરતકામવાળી ચોળી અને બાંધણી ઓઢણી) અને લગ્નપ્રસંગે 'પાનેતર' (સફેદ-લાલ રેશમી સાડી) તથા 'ઘર્ચોળું' (લાલ-લીલી બાંધણી સાડી) પહેરાય છે. ૨) પુરુષો માટે 'કેડિયું' (કમરથી ઘેરવાળો કુર્તો), ચોયણી/ધોતી અને માથા પર બાંધણીનો રંગીન સાફો/પાઘડી પહેરાય છે. નવરાત્રી દરમિયાન યુવક-યુવતીઓ આ પરંપરાગત પોશાકમાં ગરબે ઘૂમે છે.",
        "short_answer_gu": "સ્ત્રીઓ માટે આભલાવાળા ચણિયા-ચોળી અને પાનેતર તથા પુરુષો માટે ઘેરદાર કેડિયું, ધોતી અને રંગબેરંગી પાઘડી.",
        "short_answer_en": "Traditional Gujarati dress features embroidered mirrorwork Chaniya Choli and Panetar sarees for women, and flared Kedia with turbans (Pheta) for men.",
        "short_answer_hi": "गुजरात का पारंपरिक पहनावा महिलाओं के लिए शीशे जड़ा चनिया-चोली व पानेतर और पुरुषों के लिए केडिया, धोती व पगड़ी है।",
        "keywords": ["Chaniya Choli", "Kedia", "Panetar", "Gharchola", "Paghdi", "Traditional Dress", "ચણિયા ચોળી", "કેડિયું", "પાનેતર", "પાઘડી"],
        "source": "Gujarat Cultural Heritage",
        "source_type": "Traditional Attire Heritage",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "cult_04",
        "category": "Gujarati Culture",
        "title": "અતિથિ દેવો ભવઃ અને ગુજરાતી આતિથ્ય સત્કાર (Gujarati Hospitality & Social Values)",
        "title_en": "Gujarati Hospitality",
        "district": "All Gujarat",
        "question_gu": "ગુજરાતી આતિથ્ય સત્કાર, મહેમાનગતિ અને વેપારી સંસ્કૃતિ વિશે જણાવો.",
        "question_hi": "गुजराती आतिथ्य सत्कार, मेहमाननवाजी और व्यापारिक संस्कृति के बारे में बताएं।",
        "question_mr": "गुजराती आदरातिथ्य आणि व्यापार संस्कृतीविषयी सांगा.",
        "question_en": "Explain the warmth of Gujarati hospitality and the entrepreneurial spirit of Gujaratis.",
        "question_roman_gu": "Gujarati hospitality ane vepari sanskriti vishe janavo.",
        "answer_gu": "ગુજરાતી સંસ્કૃતિ 'અતિથિ દેવો ભવઃ' (અતિથિ એ ભગવાન સમાન છે) અને આતિથ્ય સત્કાર માટે વિશ્વભરમાં જાણીતી છે. ઘરમાં આવનાર કોઈપણ અતિથિને સૌપ્રથમ ઠંડું પાણી, ગોળ-ધાણા કે શરબત આપી 'આવો, પધારો' કહીને સત્કારવામાં આવે છે અને ભોજનમાં આગ્રહપૂર્વક પીરસવામાં આવે છે. સૌરાષ્ટ્રમાં 'આવકારો મીઠો આપજે રે' કાગબાપુની રચના આતિથ્યનું ગીત છે. આ સાથે ગુજરાતીઓ તેમની સાહસિક વેપારી બુદ્ધિ (Entrepreneurial spirit), શાંતિપ્રિય સ્વભાવ અને દાનવીરતા (Philanthropy) માટે વિશ્વભરમાં આદર પામે છે.",
        "short_answer_gu": "'આવો, પધારો'નો મીઠો આવકારો, આગ્રહપૂર્વક ભોજન અને સાહસિક વેપારી સ્વભાવ એ ગુજરાતી સંસ્કૃતિની ઓળખ છે.",
        "short_answer_en": "Gujarati hospitality is defined by the warm welcome ('Aavo, Padharo'), generous serving of food, peaceful coexistence, and an entrepreneurial ethos.",
        "short_answer_hi": "गुजराती संस्कृति 'आओ, पधारो' के मीठे आवकार, उदार आतिथ्य और साहसी व्यापारिक स्वभाव के लिए पूरे विश्व में जानी जाती है।",
        "keywords": ["Gujarati Hospitality", "Aavo Padharo", "Aavkar", "Kag Bapu", "Entrepreneurship", "આતિથ્ય", "આવકારો", "વેપારી સંસ્કૃતિ"],
        "source": "Gujarat Cultural Studies",
        "source_type": "Social & Cultural Ethos",
        "source_url": "https://www.gujarattourism.com"
    },
    {
        "id": "event_06",
        "category": "Historical Events",
        "title": "નવનિર્માણ આંદોલન ૧૯૭૪ (Navnirman Andolan 1974 - Student Movement)",
        "title_en": "Navnirman Andolan",
        "district": "All Gujarat (Ahmedabad / Morbi)",
        "question_gu": "૧૯૭૪ના નવનિર્માણ આંદોલનનો ઇતિહાસ અને પરિણામ જણાવો.",
        "question_hi": "१९७४ के नवनिर्माण आंदोलन का इतिहास और परिणाम बताएं।",
        "question_mr": "१९७४ च्या नवनिर्माण आंदोलनाविषयी सांगा.",
        "question_en": "Explain the 1974 Navnirman Andolan, the first student movement in independent India to dissolve an elected government.",
        "question_roman_gu": "1974 Navnirman Andolan itihas ane parinam janavo.",
        "answer_gu": "નવનિર્માણ આંદોલન ડિસેમ્બર ૧૯૭૩ થી માર્ચ ૧૯૭૪ દરમિયાન ગુજરાતમાં વિદ્યાર્થીઓ અને યુવાનો દ્વારા મોંઘવારી, છાત્રાલયના ફૂડ બિલ વધારા અને ભ્રષ્ટાચાર સામે શરૂ થયેલું ઐતિહાસિક લોકઆંદોલન હતું. એલ.ડી. એન્જિનિયરિંગ કોલેજ અમદાવાદ અને મોરબી એન્જિનિયરિંગ કોલેજથી શરૂ થયેલા આ આંદોલનને જયપ્રકાશ નારાયણ (JP)નું સમર્થન મળ્યું હતું. આ આંદોલનના પરિણામે તત્કાલીન મુખ્યમંત્રી ચીમનભાઈ પટેલે રાજીનામું આપવું પડ્યું અને ભારતના ઇતિહાસમાં સૌપ્રથમ વખત ચૂંટાયેલી રાજ્ય વિધાનસભા ભંગ કરવામાં આવી હતી.",
        "short_answer_gu": "૧૯૭૪માં મોંઘવારી અને ભ્રષ્ટાચાર સામે ગુજરાતના વિદ્યાર્થીઓનું આંદોલન, જેના દબાણથી મુખ્યમંત્રીએ રાજીનામું આપવું પડ્યું હતું.",
        "short_answer_en": "Navnirman Andolan (1974) was a historic student-led socio-political movement in Gujarat that forced the resignation of the Chief Minister and dissolved the state assembly.",
        "short_answer_hi": "१९७४ का नवनिर्माण आंदोलन स्वतंत्र भारत का पहला छात्र आंदोलन था जिसके दबाव में राज्य सरकार और विधानसभा को भंग करना पड़ा।",
        "keywords": ["Navnirman Andolan", "1974", "Student Movement", "Jayaprakash Narayan", "Chimanbhai Patel", "નવનિર્માણ આંદોલન", "૧૯૭૪", "વિદ્યાર્થી આંદોલન"],
        "source": "State Historical Archives of Gujarat",
        "source_type": "Historical Socio-Political Movement",
        "source_url": "https://gujaratinformation.gujarat.gov.in"
    }
]

def build_full_dataset():
    full_dataset = R1 + R2 + PART3_RECORDS
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    
    # Save to data/knowledge_base.json and root knowledge_base.json
    data_kb = DATA_DIR / "knowledge_base.json"
    root_kb = ROOT_DIR / "knowledge_base.json"
    
    with open(data_kb, "w", encoding="utf-8") as f:
        json.dump(full_dataset, f, ensure_ascii=False, indent=2)
        
    with open(root_kb, "w", encoding="utf-8") as f:
        json.dump(full_dataset, f, ensure_ascii=False, indent=2)
        
    print(f"==================================================")
    print(f"GUJJUVAANI KNOWLEDGE BASE GENERATED SUCCESSFULLY!")
    print(f"Total authentic, verified records: {len(full_dataset)}")
    print(f"Saved to: {data_kb}")
    print(f"Saved to: {root_kb}")
    print(f"==================================================")
    
    # Print category distribution
    cat_counts = {}
    for r in full_dataset:
        c = r.get("category", "General")
        cat_counts[c] = cat_counts.get(c, 0) + 1
    for c, count in sorted(cat_counts.items()):
        print(f"  - {c:<25}: {count} records")

if __name__ == "__main__":
    build_full_dataset()
